// A generated client stub over a connection from New: does composing the two the
// way a service actually does still carry the selected correlation metadata and
// one client span per call?
//
// The other files here drive the connection directly, which would not catch a
// stub bypassing the interceptors this package installs.

package grpcclient_test

import (
	"testing"

	"github.com/example/go-service-template-rest/internal/infra/grpcclient"
	"github.com/example/go-service-template-rest/internal/infra/telemetry/telemetrytest"
	"github.com/example/go-service-template-rest/internal/reqctx"
	"google.golang.org/grpc/credentials/insecure"
	healthgrpc "google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/metadata"
)

func TestGeneratedClientCompositionUsesSharedConnection(t *testing.T) {
	t.Parallel()
	unaryMetadata, _, target := startMetadataCaptureServer(t)
	recorder, tracerProvider := telemetrytest.NewRecordingTracerProvider(t)

	connection, err := grpcclient.New(
		grpcclient.DefaultConfig(target),
		grpcclient.Options{
			TransportCredentials: insecure.NewCredentials(),
			TracerProvider:       tracerProvider,
			Propagation:          grpcclient.PropagationTrustedService,
		},
	)
	if err != nil {
		t.Fatalf("grpcclient.New() error = %v", err)
	}
	t.Cleanup(func() { _ = connection.Close() })

	const requestID = "generated_health_123"
	ctx := metadata.NewOutgoingContext(t.Context(), metadata.Pairs(
		"authorization", "Bearer retained",
		"baggage", "private=value",
	))
	ctx = reqctx.ContextWithRequestID(ctx, requestID)
	ctx, parent := tracerProvider.Tracer("grpcclient-generated-composition-test").Start(ctx, "parent")
	defer parent.End()

	// The standard health client is generated by protoc-gen-go-grpc and consumes
	// the same grpc.ClientConnInterface as any provider-generated client.
	client := healthgrpc.NewHealthClient(connection)
	response, err := client.Check(ctx, &healthgrpc.HealthCheckRequest{})
	if err != nil {
		t.Fatalf("generated Health.Check() error = %v", err)
	}
	if got := response.GetStatus(); got != healthgrpc.HealthCheckResponse_SERVING {
		t.Fatalf("Health.Check() status = %s, want %s", got, healthgrpc.HealthCheckResponse_SERVING)
	}

	assertWireCorrelation(t, "generated unary", <-unaryMetadata, wireCorrelation{
		traceID:       parent.SpanContext().TraceID().String(),
		requestID:     requestID,
		wantTrace:     true,
		wantRequestID: true,
	})
	if got := len(recorder.Ended()); got == 0 {
		t.Fatal("generated Health.Check() recorded no client span")
	}
	if err := connection.Close(); err != nil {
		t.Fatalf("ClientConn.Close() error = %v", err)
	}
}
