version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/build/docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/env"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
    groups:
      docker-compose:
        patterns:
          - "*"
