version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - errcheck
    - bidichk
    - bodyclose
    - durationcheck
    - errchkjson
    - sqlclosecheck
    - errorlint
    - gocheckcompilerdirectives
    - contextcheck
    - gocritic
    - loggercheck
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - thelper
    - gomoddirectives
    - unconvert
    - wastedassign
