version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - govet
    - staticcheck
    - errcheck
    - errname
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errchkjson
    - sqlclosecheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - contextcheck
    - gocritic
    - loggercheck
    - makezero
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - thelper
    - gomoddirectives
    - unconvert
    - unqueryvet
    - unparam
    - usetesting
    - usestdlibvars
    - wastedassign
  exclusions:
    generated: strict
    paths:
      - internal/api/openapi\.gen\.go
      - internal/infra/postgres/sqlcgen/.*
      - .*_mock_test\.go
      - .*_string\.go
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
