// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// InvalidParam defines model for InvalidParam.
type InvalidParam struct {
	// Name An RFC 6901 JSON pointer for a request-body member, or a `location.name` pair such as `query.limit` for a parameter.
	//
	// Example: /slug
	Name string `json:"name"`

	// Reason Why the contract rejected it. Names the constraint that failed and never echoes the submitted value.
	//
	// Example: maximum string length is 64
	Reason string `json:"reason"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	//
	// Example: bad_request
	Code string `json:"code"`

	// Detail Example: invalid request framing
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying this occurrence when the service exposes one.
	Instance *string `json:"instance,omitempty"`

	// InvalidParams Which parts of the request failed validation, following the RFC 9457 extension-member example. Present only on a validation rejection, and never carrying the submitted value.
	InvalidParams *[]InvalidParam `json:"invalid_params,omitempty"`

	// RequestId Example: 9ccecdfd92c94665a46406f8ba73cd77
	RequestId *string `json:"request_id,omitempty"`

	// Status Example: 400
	Status int32 `json:"status"`

	// Title Example: bad request
	Title string `json:"title"`

	// Type Stable URI reference identifying the problem class.
	//
	// Example: https://www.rfc-editor.org/rfc/rfc9110#section-15.5.1
	Type string `json:"type"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// RequestEntityTooLarge defines model for RequestEntityTooLarge.
type RequestEntityTooLarge = Problem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// HealthLive Liveness probe
	// (GET /health/live)
	HealthLive(w http.ResponseWriter, r *http.Request)
	// HealthReady Readiness probe
	// (GET /health/ready)
	HealthReady(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// HealthLive Liveness probe
// (GET /health/live)
func (_ Unimplemented) HealthLive(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HealthReady Readiness probe
// (GET /health/ready)
func (_ Unimplemented) HealthReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthLive operation middleware
func (siw *ServerInterfaceWrapper) HealthLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthReady operation middleware
func (siw *ServerInterfaceWrapper) HealthReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/live", wrapper.HealthLive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/ready", wrapper.HealthReady)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type RequestEntityTooLargeApplicationProblemPlusJSONResponse Problem

type HealthLiveRequestObject struct {
}

type HealthLiveResponseObject interface {
	VisitHealthLiveResponse(w http.ResponseWriter) error
}

type HealthLive200TextResponse string

func (response HealthLive200TextResponse) VisitHealthLiveResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type HealthLive400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response HealthLive400ApplicationProblemPlusJSONResponse) VisitHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type HealthLive413ApplicationProblemPlusJSONResponse struct {
	RequestEntityTooLargeApplicationProblemPlusJSONResponse
}

func (response HealthLive413ApplicationProblemPlusJSONResponse) VisitHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type HealthLive500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response HealthLive500ApplicationProblemPlusJSONResponse) VisitHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type HealthReadyRequestObject struct {
}

type HealthReadyResponseObject interface {
	VisitHealthReadyResponse(w http.ResponseWriter) error
}

type HealthReady200TextResponse string

func (response HealthReady200TextResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type HealthReady400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response HealthReady400ApplicationProblemPlusJSONResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type HealthReady413ApplicationProblemPlusJSONResponse struct {
	RequestEntityTooLargeApplicationProblemPlusJSONResponse
}

func (response HealthReady413ApplicationProblemPlusJSONResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type HealthReady500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response HealthReady500ApplicationProblemPlusJSONResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type HealthReady503TextResponse string

func (response HealthReady503TextResponse) VisitHealthReadyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(503)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// HealthLive Liveness probe
	// (GET /health/live)
	HealthLive(ctx context.Context, request HealthLiveRequestObject) (HealthLiveResponseObject, error)
	// HealthReady Readiness probe
	// (GET /health/ready)
	HealthReady(ctx context.Context, request HealthReadyRequestObject) (HealthReadyResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// HealthLive operation middleware
func (sh *strictHandler) HealthLive(w http.ResponseWriter, r *http.Request) {
	var request HealthLiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthLive(ctx, request.(HealthLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthLive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthLiveResponseObject); ok {
		if err := validResponse.VisitHealthLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthReady operation middleware
func (sh *strictHandler) HealthReady(w http.ResponseWriter, r *http.Request) {
	var request HealthReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthReady(ctx, request.(HealthReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthReadyResponseObject); ok {
		if err := validResponse.VisitHealthReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FZNbxs5D/4rhPreXn+l+dr41u22WBfdNki66KEIGlnieNRqpCnFSWwU/u8LasbjOHGb7WG72EOAjCWS",
	"Dx8+JPVVmVjVMWDgpKZfFWGqY0iYP37V9gK/NJhYvkwMjCH/q+vaO6PZxTCuKc49Vv//lGKQs2RKrLT8",
	"9z/CQk3Vk/E2xLg9TePz1kqt1+uBspgMuVrcqamiNiS4BJX2RaQKLUQCF260d1atB2oWGClof4l0g/SC",
	"KNLPRNgEXNZoGC2kjAAK7XxDKNg6xl4Edrx6F+NrTQv8N/ibR7sCXBpEm8DEULhFQ2jBu8qxErvOmcSa",
	"teSea9KVfNcUayR2rRCCrnIKu4GeBbh4+RxOziYH8Ory7Ruoo5PCQBEJNHQ4hhlHhdUcaQD55NrHNvmR",
	"OL6GWjuC1JgSdILrLw3SapRRXneuaoGFjDRSA4VLXdUe1VSNk28WaqB4VctnYnJhITUg1B2bu4jflyvg",
	"EoUNJm0YCD+1dXQ8gje6wrQ5T0zaBQYuNefyogUdLASUeqMpY3c3NfPKsfi40b7BXYSVXrqqqaCFBh7D",
	"gktR9snRQ9wZ+JfGEVo1/dCS3udy1V+Pc8EsaW5E8KBeJto99bpkPfcIlTalCzgk1Db/gNI/IDa74Ofa",
	"fuyKuI9ki6ydlzBbk65HN7WHgnQl1/eYu5BYB7MH558XMyAskDAYBGcxsCtWwh+XLkE0pqH27LbE0BYB",
	"6cYZBFzWMWGCGHIuMjw0S8eSG/Yu96PJwD9mpaV9ynGmFB1ygljkmH2OrTiyfVb1AIrofbxtEWNukrOj",
	"41PAJWNILoZh2w7QETeCc8KEgSEGv4IYQN9x14k0O94q0Gii1SbCHg06xio9NkV2un7d06KJ9Ep1csTE",
	"H53dLfOZMWhsYc+emrOjk5NjfXRyNDkpfpnr00NjT0/3MZxYc5N2/BxNJndq5AIfPt1ausC4QMqwHHvc",
	"RTDXvcj2BWt/+EYDfE9fCN08BuN1SrsNUTLXaToe397ejqgwQ7SOI40iLcZUGPk7OziYPElttYYHx6Pj",
	"0cEPyPDeAMhd3F3akNDz+HAeCMdoGnK8upT6tqNgjpqQnjVcbr9ebvC8ev9O3V8fr96/A20MpgQcP2MA",
	"l1KDFub96Nwskrez3563p+3Iz9357HwGurFOMhT2stRyxXLobdJCZru+XCiigPPOYEi4XTjqj5nga8jf",
	"IT/WGFJsyGAmvjNKY7m71YpaxGE3FIaMVe01y8TLarlBSm2uk9HBaCJW4lTXTk3V4WgyOlQDVWsuM4Hj",
	"ErXncuzdTYa2wLzCZdzm9pxZNVW/5zuv5cpg9w31dDK5t/wZlzyuvXb31v1WZ/HzHm082PPxsyA/mky+",
	"1eU9jvGdh5yYHBw+brL/GbMeqOO/E3DfA+2uQNX0w9VApaaqNK3UVAlzQSQn3ZfVrhdJeiCtEmMlal8O",
	"N8ZDi8a1FRTW6pgaQjVVdTP3zkgBcmF05rKmKFoe5skqMpBmBL+Jh8HmVwvcOi4hRLBYY7AYzAraBZda",
	"7jcykK25ekQHF/nOTxNCC+m/pQWxPfxhPkJkoI7cR2nZXv6e8qRW7h+S3kZt1Mfo5ZZtZeVkXS4wIDnT",
	"wgWZ8CgZ7cLeneUfrtaSR+Y05dPd7Ns3Evcvo0hu4UI/TcdqfdWnet/27UbT2veIUx7xfd/IQ6RPS+Z8",
	"N7E70tZX678GAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
