// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertOrderedOutboxEvents = `-- name: InsertOrderedOutboxEvents :batchone
WITH head AS (
    INSERT INTO outbox_ordering_heads (ordering_key, last_sequence, current_sequence)
    VALUES ($9, $10, $10)
    ON CONFLICT (ordering_key) DO UPDATE
    SET last_sequence = EXCLUDED.last_sequence,
        current_sequence = coalesce(
            outbox_ordering_heads.current_sequence,
            EXCLUDED.current_sequence
        ),
        updated_at = clock_timestamp()
    WHERE outbox_ordering_heads.last_sequence < EXCLUDED.last_sequence
    RETURNING current_sequence
)
INSERT INTO outbox_events (
    id,
    event_type,
    source,
    destination,
    schema_name,
    occurred_at,
    payload,
    metadata,
    ordering_key,
    ordering_sequence,
    ordering_ready
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    head.current_sequence IS NOT DISTINCT FROM $10
FROM head
RETURNING outbox_events.id
`

type InsertOrderedOutboxEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertOrderedOutboxEventsParams struct {
	ID               string
	EventType        string
	Source           string
	Destination      string
	SchemaName       string
	OccurredAt       pgtype.Timestamptz
	Payload          []byte
	Metadata         []byte
	OrderingKey      *string
	OrderingSequence *int64
}

// An ordered append advances its key's retained high-water mark and stores the
// event in one statement, so a feature transaction holds the head row lock for
// a single round trip. The head upsert changes nothing when the sequence is at
// or below the retained mark; the event insert then selects from an empty
// result and returns no row, which is how the caller recognizes a rejected
// sequence. `ordering_ready` records whether this event is its key's claimable
// head, which is true exactly when the head now points at this sequence.
//
// Pipelined like the unordered insert. Statements in one pipeline still execute
// in the order they were queued, so two appends to the same key inside one
// batch see each other's head exactly as two separate round trips would.
func (q *Queries) InsertOrderedOutboxEvents(ctx context.Context, arg []InsertOrderedOutboxEventsParams) *InsertOrderedOutboxEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.EventType,
			a.Source,
			a.Destination,
			a.SchemaName,
			a.OccurredAt,
			a.Payload,
			a.Metadata,
			a.OrderingKey,
			a.OrderingSequence,
		}
		batch.Queue(insertOrderedOutboxEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertOrderedOutboxEventsBatchResults{br, len(arg), false}
}

func (b *InsertOrderedOutboxEventsBatchResults) QueryRow(f func(int, string, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id string
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertOrderedOutboxEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertOutboxEvents = `-- name: InsertOutboxEvents :batchexec
INSERT INTO outbox_events (
    id,
    event_type,
    source,
    destination,
    schema_name,
    occurred_at,
    payload,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertOutboxEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertOutboxEventsParams struct {
	ID          string
	EventType   string
	Source      string
	Destination string
	SchemaName  string
	OccurredAt  pgtype.Timestamptz
	Payload     []byte
	Metadata    []byte
}

// An unordered event owns no ordering head, so it stores the envelope alone and
// leaves the ordering columns at their defaults.
//
// The append path always pipelines, even for a single event: a feature that
// emits several events in one transaction pays one round trip instead of one
// per event, and holds its own row locks for that much less time.
func (q *Queries) InsertOutboxEvents(ctx context.Context, arg []InsertOutboxEventsParams) *InsertOutboxEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.EventType,
			a.Source,
			a.Destination,
			a.SchemaName,
			a.OccurredAt,
			a.Payload,
			a.Metadata,
		}
		batch.Queue(insertOutboxEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertOutboxEventsBatchResults{br, len(arg), false}
}

func (b *InsertOutboxEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertOutboxEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
