// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: billing_microleases.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBillingOutbox = `-- name: ClaimBillingOutbox :many
UPDATE billing_outbox
SET
    state = 'publishing',
    attempt_count = attempt_count + 1,
    updated_at = $2
WHERE outbox_id IN (
    SELECT candidate.outbox_id
    FROM billing_outbox AS candidate
    WHERE candidate.state IN ('pending', 'failed')
      AND candidate.next_attempt_at <= $1
    ORDER BY candidate.next_attempt_at, candidate.outbox_id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
RETURNING outbox_id, event_type, aggregate_type, aggregate_id, event_fingerprint, safe_payload, state, attempt_count, next_attempt_at, published_at, created_at, updated_at
`

type ClaimBillingOutboxParams struct {
	NextAttemptAt pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Limit         int32
}

func (q *Queries) ClaimBillingOutbox(ctx context.Context, arg ClaimBillingOutboxParams) ([]BillingOutbox, error) {
	rows, err := q.db.Query(ctx, claimBillingOutbox, arg.NextAttemptAt, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingOutbox
	for rows.Next() {
		var i BillingOutbox
		if err := rows.Scan(
			&i.OutboxID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventFingerprint,
			&i.SafePayload,
			&i.State,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBillingEventInboxReceipt = `-- name: CreateBillingEventInboxReceipt :one
INSERT INTO billing_event_inbox (
    inbox_id,
    topic,
    partition_id,
    offset_value,
    event_id,
    producer_identity,
    business_identity_type,
    business_identity_value,
    event_fingerprint,
    state,
    failure_class,
    safe_metadata,
    received_at,
    applied_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'received', NULL, $10, $11, NULL, $11)
RETURNING inbox_id, topic, partition_id, offset_value, event_id, producer_identity, business_identity_type, business_identity_value, event_fingerprint, state, failure_class, safe_metadata, received_at, applied_at, updated_at
`

type CreateBillingEventInboxReceiptParams struct {
	InboxID               pgtype.UUID
	Topic                 string
	PartitionID           int32
	OffsetValue           int64
	EventID               string
	ProducerIdentity      string
	BusinessIdentityType  string
	BusinessIdentityValue string
	EventFingerprint      string
	SafeMetadata          []byte
	ReceivedAt            pgtype.Timestamptz
}

func (q *Queries) CreateBillingEventInboxReceipt(ctx context.Context, arg CreateBillingEventInboxReceiptParams) (BillingEventInbox, error) {
	row := q.db.QueryRow(ctx, createBillingEventInboxReceipt,
		arg.InboxID,
		arg.Topic,
		arg.PartitionID,
		arg.OffsetValue,
		arg.EventID,
		arg.ProducerIdentity,
		arg.BusinessIdentityType,
		arg.BusinessIdentityValue,
		arg.EventFingerprint,
		arg.SafeMetadata,
		arg.ReceivedAt,
	)
	var i BillingEventInbox
	err := row.Scan(
		&i.InboxID,
		&i.Topic,
		&i.PartitionID,
		&i.OffsetValue,
		&i.EventID,
		&i.ProducerIdentity,
		&i.BusinessIdentityType,
		&i.BusinessIdentityValue,
		&i.EventFingerprint,
		&i.State,
		&i.FailureClass,
		&i.SafeMetadata,
		&i.ReceivedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBillingOutbox = `-- name: CreateBillingOutbox :one
INSERT INTO billing_outbox (
    outbox_id,
    event_type,
    aggregate_type,
    aggregate_id,
    event_fingerprint,
    safe_payload,
    state,
    attempt_count,
    next_attempt_at,
    published_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', 0, $7, NULL, $8, $8)
RETURNING outbox_id, event_type, aggregate_type, aggregate_id, event_fingerprint, safe_payload, state, attempt_count, next_attempt_at, published_at, created_at, updated_at
`

type CreateBillingOutboxParams struct {
	OutboxID         pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      string
	EventFingerprint string
	SafePayload      []byte
	NextAttemptAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateBillingOutbox(ctx context.Context, arg CreateBillingOutboxParams) (BillingOutbox, error) {
	row := q.db.QueryRow(ctx, createBillingOutbox,
		arg.OutboxID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventFingerprint,
		arg.SafePayload,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	var i BillingOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventFingerprint,
		&i.SafePayload,
		&i.State,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMicroleaseCheckpoint = `-- name: CreateMicroleaseCheckpoint :one
INSERT INTO microlease_checkpoints (
    checkpoint_id,
    microlease_id,
    account_id,
    account_scope_key,
    proxy_allocator_owner_id,
    microlease_generation,
    checkpoint_sequence,
    checkpoint_kind,
    allocated_child_high_water,
    allocated_child_count,
    allocated_child_cap_sum_usd_atoms,
    terminal_submitted_count,
    terminal_published_count,
    terminal_accepted_count,
    unresolved_child_count,
    unresolved_child_cap_sum_usd_atoms,
    local_remaining_usd_atoms,
    checkpoint_fingerprint,
    inbox_id,
    created_at,
    applied_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING checkpoint_id, microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, checkpoint_sequence, checkpoint_kind, allocated_child_high_water, allocated_child_count, allocated_child_cap_sum_usd_atoms, terminal_submitted_count, terminal_published_count, terminal_accepted_count, unresolved_child_count, unresolved_child_cap_sum_usd_atoms, local_remaining_usd_atoms, checkpoint_fingerprint, inbox_id, created_at, applied_at
`

type CreateMicroleaseCheckpointParams struct {
	CheckpointID                  pgtype.UUID
	MicroleaseID                  pgtype.UUID
	AccountID                     pgtype.UUID
	AccountScopeKey               string
	ProxyAllocatorOwnerID         string
	MicroleaseGeneration          int64
	CheckpointSequence            int64
	CheckpointKind                string
	AllocatedChildHighWater       int64
	AllocatedChildCount           int64
	AllocatedChildCapSumUsdAtoms  int64
	TerminalSubmittedCount        int64
	TerminalPublishedCount        int64
	TerminalAcceptedCount         int64
	UnresolvedChildCount          int64
	UnresolvedChildCapSumUsdAtoms int64
	LocalRemainingUsdAtoms        int64
	CheckpointFingerprint         string
	InboxID                       pgtype.UUID
	CreatedAt                     pgtype.Timestamptz
	AppliedAt                     pgtype.Timestamptz
}

func (q *Queries) CreateMicroleaseCheckpoint(ctx context.Context, arg CreateMicroleaseCheckpointParams) (MicroleaseCheckpoint, error) {
	row := q.db.QueryRow(ctx, createMicroleaseCheckpoint,
		arg.CheckpointID,
		arg.MicroleaseID,
		arg.AccountID,
		arg.AccountScopeKey,
		arg.ProxyAllocatorOwnerID,
		arg.MicroleaseGeneration,
		arg.CheckpointSequence,
		arg.CheckpointKind,
		arg.AllocatedChildHighWater,
		arg.AllocatedChildCount,
		arg.AllocatedChildCapSumUsdAtoms,
		arg.TerminalSubmittedCount,
		arg.TerminalPublishedCount,
		arg.TerminalAcceptedCount,
		arg.UnresolvedChildCount,
		arg.UnresolvedChildCapSumUsdAtoms,
		arg.LocalRemainingUsdAtoms,
		arg.CheckpointFingerprint,
		arg.InboxID,
		arg.CreatedAt,
		arg.AppliedAt,
	)
	var i MicroleaseCheckpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.CheckpointSequence,
		&i.CheckpointKind,
		&i.AllocatedChildHighWater,
		&i.AllocatedChildCount,
		&i.AllocatedChildCapSumUsdAtoms,
		&i.TerminalSubmittedCount,
		&i.TerminalPublishedCount,
		&i.TerminalAcceptedCount,
		&i.UnresolvedChildCount,
		&i.UnresolvedChildCapSumUsdAtoms,
		&i.LocalRemainingUsdAtoms,
		&i.CheckpointFingerprint,
		&i.InboxID,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const createMicroleaseChildDebit = `-- name: CreateMicroleaseChildDebit :one
INSERT INTO microlease_child_debits (
    microlease_child_debit_id,
    microlease_id,
    debit_authorization_id,
    usage_operation_id,
    account_id,
    account_scope_key,
    proxy_allocator_owner_id,
    microlease_generation,
    child_sequence,
    child_cap_usd_atoms,
    charged_usd_atoms,
    released_usd_atoms,
    write_off_usd_atoms,
    request_basis_fingerprint,
    terminal_basis_fingerprint,
    pricing_snapshot_id,
    pricing_snapshot_fingerprint,
    terminal_kind,
    state,
    qualified_inference_evidence_id,
    terminal_event_id,
    terminal_inbox_id,
    ledger_entry_id,
    settlement_effect_id,
    safe_metadata,
    created_at,
    terminal_at,
    settled_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $26
)
RETURNING microlease_child_debit_id, microlease_id, debit_authorization_id, usage_operation_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, child_sequence, child_cap_usd_atoms, charged_usd_atoms, released_usd_atoms, write_off_usd_atoms, request_basis_fingerprint, terminal_basis_fingerprint, pricing_snapshot_id, pricing_snapshot_fingerprint, terminal_kind, state, qualified_inference_evidence_id, terminal_event_id, terminal_inbox_id, ledger_entry_id, settlement_effect_id, safe_metadata, created_at, terminal_at, settled_at, updated_at
`

type CreateMicroleaseChildDebitParams struct {
	MicroleaseChildDebitID       pgtype.UUID
	MicroleaseID                 pgtype.UUID
	DebitAuthorizationID         string
	UsageOperationID             pgtype.UUID
	AccountID                    pgtype.UUID
	AccountScopeKey              string
	ProxyAllocatorOwnerID        string
	MicroleaseGeneration         int64
	ChildSequence                int64
	ChildCapUsdAtoms             int64
	ChargedUsdAtoms              int64
	ReleasedUsdAtoms             int64
	WriteOffUsdAtoms             int64
	RequestBasisFingerprint      string
	TerminalBasisFingerprint     *string
	PricingSnapshotID            string
	PricingSnapshotFingerprint   string
	TerminalKind                 string
	State                        string
	QualifiedInferenceEvidenceID pgtype.UUID
	TerminalEventID              *string
	TerminalInboxID              pgtype.UUID
	LedgerEntryID                pgtype.UUID
	SettlementEffectID           pgtype.UUID
	SafeMetadata                 []byte
	CreatedAt                    pgtype.Timestamptz
	TerminalAt                   pgtype.Timestamptz
	SettledAt                    pgtype.Timestamptz
}

func (q *Queries) CreateMicroleaseChildDebit(ctx context.Context, arg CreateMicroleaseChildDebitParams) (MicroleaseChildDebit, error) {
	row := q.db.QueryRow(ctx, createMicroleaseChildDebit,
		arg.MicroleaseChildDebitID,
		arg.MicroleaseID,
		arg.DebitAuthorizationID,
		arg.UsageOperationID,
		arg.AccountID,
		arg.AccountScopeKey,
		arg.ProxyAllocatorOwnerID,
		arg.MicroleaseGeneration,
		arg.ChildSequence,
		arg.ChildCapUsdAtoms,
		arg.ChargedUsdAtoms,
		arg.ReleasedUsdAtoms,
		arg.WriteOffUsdAtoms,
		arg.RequestBasisFingerprint,
		arg.TerminalBasisFingerprint,
		arg.PricingSnapshotID,
		arg.PricingSnapshotFingerprint,
		arg.TerminalKind,
		arg.State,
		arg.QualifiedInferenceEvidenceID,
		arg.TerminalEventID,
		arg.TerminalInboxID,
		arg.LedgerEntryID,
		arg.SettlementEffectID,
		arg.SafeMetadata,
		arg.CreatedAt,
		arg.TerminalAt,
		arg.SettledAt,
	)
	var i MicroleaseChildDebit
	err := row.Scan(
		&i.MicroleaseChildDebitID,
		&i.MicroleaseID,
		&i.DebitAuthorizationID,
		&i.UsageOperationID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.ChildSequence,
		&i.ChildCapUsdAtoms,
		&i.ChargedUsdAtoms,
		&i.ReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.RequestBasisFingerprint,
		&i.TerminalBasisFingerprint,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.TerminalKind,
		&i.State,
		&i.QualifiedInferenceEvidenceID,
		&i.TerminalEventID,
		&i.TerminalInboxID,
		&i.LedgerEntryID,
		&i.SettlementEffectID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.TerminalAt,
		&i.SettledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMicroleaseReconciliationCase = `-- name: CreateMicroleaseReconciliationCase :one
INSERT INTO reconciliation_cases (
    reconciliation_case_id,
    account_id,
    reason,
    state,
    severity,
    usage_operation_id,
    topup_operation_id,
    payment_attempt_id,
    payment_evidence_id,
    settlement_effect_id,
    qualified_inference_evidence_id,
    ledger_entry_id,
    legacy_balance_import_id,
    resolution_ledger_entry_id,
    resolution_settlement_effect_id,
    lease_owner,
    lease_deadline_at,
    attempt_count,
    next_attempt_at,
    support_safe_notes,
    created_at,
    updated_at,
    resolved_at,
    microlease_id,
    microlease_child_debit_id,
    microlease_checkpoint_id,
    billing_event_inbox_id
)
VALUES (
    $1, $2, $3, $4, $5, NULL, NULL, NULL, NULL, $6, NULL, $7, NULL, NULL, NULL, $8, $9,
    $10, $11, $12, $13, $13, NULL, $14, $15, $16, $17
)
RETURNING reconciliation_case_id, account_id, reason, state, severity, usage_operation_id, topup_operation_id, payment_attempt_id, payment_evidence_id, settlement_effect_id, qualified_inference_evidence_id, ledger_entry_id, legacy_balance_import_id, resolution_ledger_entry_id, resolution_settlement_effect_id, lease_owner, lease_deadline_at, attempt_count, next_attempt_at, support_safe_notes, created_at, updated_at, resolved_at, microlease_id, microlease_child_debit_id, microlease_checkpoint_id, billing_event_inbox_id
`

type CreateMicroleaseReconciliationCaseParams struct {
	ReconciliationCaseID   pgtype.UUID
	AccountID              pgtype.UUID
	Reason                 string
	State                  string
	Severity               string
	SettlementEffectID     pgtype.UUID
	LedgerEntryID          pgtype.UUID
	LeaseOwner             *string
	LeaseDeadlineAt        pgtype.Timestamptz
	AttemptCount           int32
	NextAttemptAt          pgtype.Timestamptz
	SupportSafeNotes       *string
	CreatedAt              pgtype.Timestamptz
	MicroleaseID           pgtype.UUID
	MicroleaseChildDebitID pgtype.UUID
	MicroleaseCheckpointID pgtype.UUID
	BillingEventInboxID    pgtype.UUID
}

func (q *Queries) CreateMicroleaseReconciliationCase(ctx context.Context, arg CreateMicroleaseReconciliationCaseParams) (ReconciliationCase, error) {
	row := q.db.QueryRow(ctx, createMicroleaseReconciliationCase,
		arg.ReconciliationCaseID,
		arg.AccountID,
		arg.Reason,
		arg.State,
		arg.Severity,
		arg.SettlementEffectID,
		arg.LedgerEntryID,
		arg.LeaseOwner,
		arg.LeaseDeadlineAt,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.SupportSafeNotes,
		arg.CreatedAt,
		arg.MicroleaseID,
		arg.MicroleaseChildDebitID,
		arg.MicroleaseCheckpointID,
		arg.BillingEventInboxID,
	)
	var i ReconciliationCase
	err := row.Scan(
		&i.ReconciliationCaseID,
		&i.AccountID,
		&i.Reason,
		&i.State,
		&i.Severity,
		&i.UsageOperationID,
		&i.TopupOperationID,
		&i.PaymentAttemptID,
		&i.PaymentEvidenceID,
		&i.SettlementEffectID,
		&i.QualifiedInferenceEvidenceID,
		&i.LedgerEntryID,
		&i.LegacyBalanceImportID,
		&i.ResolutionLedgerEntryID,
		&i.ResolutionSettlementEffectID,
		&i.LeaseOwner,
		&i.LeaseDeadlineAt,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.SupportSafeNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.MicroleaseID,
		&i.MicroleaseChildDebitID,
		&i.MicroleaseCheckpointID,
		&i.BillingEventInboxID,
	)
	return i, err
}

const createSpendingMicrolease = `-- name: CreateSpendingMicrolease :one
INSERT INTO spending_microleases (
    microlease_id,
    account_id,
    account_scope_key,
    proxy_allocator_owner_id,
    microlease_generation,
    lease_fence,
    state,
    issued_cap_usd_atoms,
    available_child_cap_usd_atoms,
    allocated_child_cap_reported_usd_atoms,
    terminal_charged_usd_atoms,
    terminal_released_usd_atoms,
    write_off_usd_atoms,
    pricing_snapshot_id,
    pricing_snapshot_fingerprint,
    pricing_policy_version,
    pricing_decision_at,
    pricing_selector_key,
    pricing_contract_version,
    fee_policy_version,
    microlease_policy_version,
    issued_at,
    debit_cutoff_at,
    expires_at,
    closed_at,
    last_checkpoint_sequence,
    last_checkpoint_fingerprint,
    idempotency_record_id,
    stored_outcome_id,
    safe_metadata,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 0, 0, 0, 0, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, NULL, 0, NULL, $21, $22, $23, $24, $24
)
RETURNING microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, lease_fence, state, issued_cap_usd_atoms, available_child_cap_usd_atoms, allocated_child_cap_reported_usd_atoms, terminal_charged_usd_atoms, terminal_released_usd_atoms, write_off_usd_atoms, pricing_snapshot_id, pricing_snapshot_fingerprint, pricing_policy_version, pricing_decision_at, pricing_selector_key, pricing_contract_version, fee_policy_version, microlease_policy_version, issued_at, debit_cutoff_at, expires_at, closed_at, last_checkpoint_sequence, last_checkpoint_fingerprint, idempotency_record_id, stored_outcome_id, safe_metadata, created_at, updated_at
`

type CreateSpendingMicroleaseParams struct {
	MicroleaseID               pgtype.UUID
	AccountID                  pgtype.UUID
	AccountScopeKey            string
	ProxyAllocatorOwnerID      string
	MicroleaseGeneration       int64
	LeaseFence                 string
	State                      string
	IssuedCapUsdAtoms          int64
	AvailableChildCapUsdAtoms  int64
	PricingSnapshotID          string
	PricingSnapshotFingerprint string
	PricingPolicyVersion       string
	PricingDecisionAt          pgtype.Timestamptz
	PricingSelectorKey         string
	PricingContractVersion     string
	FeePolicyVersion           string
	MicroleasePolicyVersion    string
	IssuedAt                   pgtype.Timestamptz
	DebitCutoffAt              pgtype.Timestamptz
	ExpiresAt                  pgtype.Timestamptz
	IdempotencyRecordID        pgtype.UUID
	StoredOutcomeID            pgtype.UUID
	SafeMetadata               []byte
	CreatedAt                  pgtype.Timestamptz
}

func (q *Queries) CreateSpendingMicrolease(ctx context.Context, arg CreateSpendingMicroleaseParams) (SpendingMicrolease, error) {
	row := q.db.QueryRow(ctx, createSpendingMicrolease,
		arg.MicroleaseID,
		arg.AccountID,
		arg.AccountScopeKey,
		arg.ProxyAllocatorOwnerID,
		arg.MicroleaseGeneration,
		arg.LeaseFence,
		arg.State,
		arg.IssuedCapUsdAtoms,
		arg.AvailableChildCapUsdAtoms,
		arg.PricingSnapshotID,
		arg.PricingSnapshotFingerprint,
		arg.PricingPolicyVersion,
		arg.PricingDecisionAt,
		arg.PricingSelectorKey,
		arg.PricingContractVersion,
		arg.FeePolicyVersion,
		arg.MicroleasePolicyVersion,
		arg.IssuedAt,
		arg.DebitCutoffAt,
		arg.ExpiresAt,
		arg.IdempotencyRecordID,
		arg.StoredOutcomeID,
		arg.SafeMetadata,
		arg.CreatedAt,
	)
	var i SpendingMicrolease
	err := row.Scan(
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.LeaseFence,
		&i.State,
		&i.IssuedCapUsdAtoms,
		&i.AvailableChildCapUsdAtoms,
		&i.AllocatedChildCapReportedUsdAtoms,
		&i.TerminalChargedUsdAtoms,
		&i.TerminalReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.PricingPolicyVersion,
		&i.PricingDecisionAt,
		&i.PricingSelectorKey,
		&i.PricingContractVersion,
		&i.FeePolicyVersion,
		&i.MicroleasePolicyVersion,
		&i.IssuedAt,
		&i.DebitCutoffAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.LastCheckpointSequence,
		&i.LastCheckpointFingerprint,
		&i.IdempotencyRecordID,
		&i.StoredOutcomeID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingAdmissionControl = `-- name: GetBillingAdmissionControl :one
SELECT admission_control_id, scope_kind, scope_key, use_class, state, reason_code, terminal_lag_bucket, stale_age_bucket, reconciliation_backlog_bucket, audited_actor_kind, audited_actor_id, safe_metadata, expires_at, renewed_at, created_at, updated_at
FROM billing_admission_controls
WHERE scope_kind = $1
  AND scope_key = $2
  AND use_class = $3
`

type GetBillingAdmissionControlParams struct {
	ScopeKind string
	ScopeKey  string
	UseClass  string
}

func (q *Queries) GetBillingAdmissionControl(ctx context.Context, arg GetBillingAdmissionControlParams) (BillingAdmissionControl, error) {
	row := q.db.QueryRow(ctx, getBillingAdmissionControl, arg.ScopeKind, arg.ScopeKey, arg.UseClass)
	var i BillingAdmissionControl
	err := row.Scan(
		&i.AdmissionControlID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.UseClass,
		&i.State,
		&i.ReasonCode,
		&i.TerminalLagBucket,
		&i.StaleAgeBucket,
		&i.ReconciliationBacklogBucket,
		&i.AuditedActorKind,
		&i.AuditedActorID,
		&i.SafeMetadata,
		&i.ExpiresAt,
		&i.RenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingEventInboxByEvent = `-- name: GetBillingEventInboxByEvent :one
SELECT inbox_id, topic, partition_id, offset_value, event_id, producer_identity, business_identity_type, business_identity_value, event_fingerprint, state, failure_class, safe_metadata, received_at, applied_at, updated_at
FROM billing_event_inbox
WHERE topic = $1
  AND event_id = $2
`

type GetBillingEventInboxByEventParams struct {
	Topic   string
	EventID string
}

func (q *Queries) GetBillingEventInboxByEvent(ctx context.Context, arg GetBillingEventInboxByEventParams) (BillingEventInbox, error) {
	row := q.db.QueryRow(ctx, getBillingEventInboxByEvent, arg.Topic, arg.EventID)
	var i BillingEventInbox
	err := row.Scan(
		&i.InboxID,
		&i.Topic,
		&i.PartitionID,
		&i.OffsetValue,
		&i.EventID,
		&i.ProducerIdentity,
		&i.BusinessIdentityType,
		&i.BusinessIdentityValue,
		&i.EventFingerprint,
		&i.State,
		&i.FailureClass,
		&i.SafeMetadata,
		&i.ReceivedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMicroleaseCheckpoint = `-- name: GetLatestMicroleaseCheckpoint :one
SELECT checkpoint_id, microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, checkpoint_sequence, checkpoint_kind, allocated_child_high_water, allocated_child_count, allocated_child_cap_sum_usd_atoms, terminal_submitted_count, terminal_published_count, terminal_accepted_count, unresolved_child_count, unresolved_child_cap_sum_usd_atoms, local_remaining_usd_atoms, checkpoint_fingerprint, inbox_id, created_at, applied_at
FROM microlease_checkpoints
WHERE microlease_id = $1
ORDER BY checkpoint_sequence DESC, checkpoint_id DESC
LIMIT 1
`

func (q *Queries) GetLatestMicroleaseCheckpoint(ctx context.Context, microleaseID pgtype.UUID) (MicroleaseCheckpoint, error) {
	row := q.db.QueryRow(ctx, getLatestMicroleaseCheckpoint, microleaseID)
	var i MicroleaseCheckpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.CheckpointSequence,
		&i.CheckpointKind,
		&i.AllocatedChildHighWater,
		&i.AllocatedChildCount,
		&i.AllocatedChildCapSumUsdAtoms,
		&i.TerminalSubmittedCount,
		&i.TerminalPublishedCount,
		&i.TerminalAcceptedCount,
		&i.UnresolvedChildCount,
		&i.UnresolvedChildCapSumUsdAtoms,
		&i.LocalRemainingUsdAtoms,
		&i.CheckpointFingerprint,
		&i.InboxID,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getMicroleaseChildDebit = `-- name: GetMicroleaseChildDebit :one
SELECT microlease_child_debit_id, microlease_id, debit_authorization_id, usage_operation_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, child_sequence, child_cap_usd_atoms, charged_usd_atoms, released_usd_atoms, write_off_usd_atoms, request_basis_fingerprint, terminal_basis_fingerprint, pricing_snapshot_id, pricing_snapshot_fingerprint, terminal_kind, state, qualified_inference_evidence_id, terminal_event_id, terminal_inbox_id, ledger_entry_id, settlement_effect_id, safe_metadata, created_at, terminal_at, settled_at, updated_at
FROM microlease_child_debits
WHERE microlease_child_debit_id = $1
`

func (q *Queries) GetMicroleaseChildDebit(ctx context.Context, microleaseChildDebitID pgtype.UUID) (MicroleaseChildDebit, error) {
	row := q.db.QueryRow(ctx, getMicroleaseChildDebit, microleaseChildDebitID)
	var i MicroleaseChildDebit
	err := row.Scan(
		&i.MicroleaseChildDebitID,
		&i.MicroleaseID,
		&i.DebitAuthorizationID,
		&i.UsageOperationID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.ChildSequence,
		&i.ChildCapUsdAtoms,
		&i.ChargedUsdAtoms,
		&i.ReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.RequestBasisFingerprint,
		&i.TerminalBasisFingerprint,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.TerminalKind,
		&i.State,
		&i.QualifiedInferenceEvidenceID,
		&i.TerminalEventID,
		&i.TerminalInboxID,
		&i.LedgerEntryID,
		&i.SettlementEffectID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.TerminalAt,
		&i.SettledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicroleaseChildDebitByAuthorization = `-- name: GetMicroleaseChildDebitByAuthorization :one
SELECT microlease_child_debit_id, microlease_id, debit_authorization_id, usage_operation_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, child_sequence, child_cap_usd_atoms, charged_usd_atoms, released_usd_atoms, write_off_usd_atoms, request_basis_fingerprint, terminal_basis_fingerprint, pricing_snapshot_id, pricing_snapshot_fingerprint, terminal_kind, state, qualified_inference_evidence_id, terminal_event_id, terminal_inbox_id, ledger_entry_id, settlement_effect_id, safe_metadata, created_at, terminal_at, settled_at, updated_at
FROM microlease_child_debits
WHERE microlease_id = $1
  AND debit_authorization_id = $2
`

type GetMicroleaseChildDebitByAuthorizationParams struct {
	MicroleaseID         pgtype.UUID
	DebitAuthorizationID string
}

func (q *Queries) GetMicroleaseChildDebitByAuthorization(ctx context.Context, arg GetMicroleaseChildDebitByAuthorizationParams) (MicroleaseChildDebit, error) {
	row := q.db.QueryRow(ctx, getMicroleaseChildDebitByAuthorization, arg.MicroleaseID, arg.DebitAuthorizationID)
	var i MicroleaseChildDebit
	err := row.Scan(
		&i.MicroleaseChildDebitID,
		&i.MicroleaseID,
		&i.DebitAuthorizationID,
		&i.UsageOperationID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.ChildSequence,
		&i.ChildCapUsdAtoms,
		&i.ChargedUsdAtoms,
		&i.ReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.RequestBasisFingerprint,
		&i.TerminalBasisFingerprint,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.TerminalKind,
		&i.State,
		&i.QualifiedInferenceEvidenceID,
		&i.TerminalEventID,
		&i.TerminalInboxID,
		&i.LedgerEntryID,
		&i.SettlementEffectID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.TerminalAt,
		&i.SettledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpendingMicrolease = `-- name: GetSpendingMicrolease :one
SELECT microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, lease_fence, state, issued_cap_usd_atoms, available_child_cap_usd_atoms, allocated_child_cap_reported_usd_atoms, terminal_charged_usd_atoms, terminal_released_usd_atoms, write_off_usd_atoms, pricing_snapshot_id, pricing_snapshot_fingerprint, pricing_policy_version, pricing_decision_at, pricing_selector_key, pricing_contract_version, fee_policy_version, microlease_policy_version, issued_at, debit_cutoff_at, expires_at, closed_at, last_checkpoint_sequence, last_checkpoint_fingerprint, idempotency_record_id, stored_outcome_id, safe_metadata, created_at, updated_at
FROM spending_microleases
WHERE microlease_id = $1
`

func (q *Queries) GetSpendingMicrolease(ctx context.Context, microleaseID pgtype.UUID) (SpendingMicrolease, error) {
	row := q.db.QueryRow(ctx, getSpendingMicrolease, microleaseID)
	var i SpendingMicrolease
	err := row.Scan(
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.LeaseFence,
		&i.State,
		&i.IssuedCapUsdAtoms,
		&i.AvailableChildCapUsdAtoms,
		&i.AllocatedChildCapReportedUsdAtoms,
		&i.TerminalChargedUsdAtoms,
		&i.TerminalReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.PricingPolicyVersion,
		&i.PricingDecisionAt,
		&i.PricingSelectorKey,
		&i.PricingContractVersion,
		&i.FeePolicyVersion,
		&i.MicroleasePolicyVersion,
		&i.IssuedAt,
		&i.DebitCutoffAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.LastCheckpointSequence,
		&i.LastCheckpointFingerprint,
		&i.IdempotencyRecordID,
		&i.StoredOutcomeID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpendingMicroleaseByIdempotency = `-- name: GetSpendingMicroleaseByIdempotency :one
SELECT microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, lease_fence, state, issued_cap_usd_atoms, available_child_cap_usd_atoms, allocated_child_cap_reported_usd_atoms, terminal_charged_usd_atoms, terminal_released_usd_atoms, write_off_usd_atoms, pricing_snapshot_id, pricing_snapshot_fingerprint, pricing_policy_version, pricing_decision_at, pricing_selector_key, pricing_contract_version, fee_policy_version, microlease_policy_version, issued_at, debit_cutoff_at, expires_at, closed_at, last_checkpoint_sequence, last_checkpoint_fingerprint, idempotency_record_id, stored_outcome_id, safe_metadata, created_at, updated_at
FROM spending_microleases
WHERE idempotency_record_id = $1
`

func (q *Queries) GetSpendingMicroleaseByIdempotency(ctx context.Context, idempotencyRecordID pgtype.UUID) (SpendingMicrolease, error) {
	row := q.db.QueryRow(ctx, getSpendingMicroleaseByIdempotency, idempotencyRecordID)
	var i SpendingMicrolease
	err := row.Scan(
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.LeaseFence,
		&i.State,
		&i.IssuedCapUsdAtoms,
		&i.AvailableChildCapUsdAtoms,
		&i.AllocatedChildCapReportedUsdAtoms,
		&i.TerminalChargedUsdAtoms,
		&i.TerminalReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.PricingPolicyVersion,
		&i.PricingDecisionAt,
		&i.PricingSelectorKey,
		&i.PricingContractVersion,
		&i.FeePolicyVersion,
		&i.MicroleasePolicyVersion,
		&i.IssuedAt,
		&i.DebitCutoffAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.LastCheckpointSequence,
		&i.LastCheckpointFingerprint,
		&i.IdempotencyRecordID,
		&i.StoredOutcomeID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaleSpendingMicroleases = `-- name: ListStaleSpendingMicroleases :many
SELECT microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, lease_fence, state, issued_cap_usd_atoms, available_child_cap_usd_atoms, allocated_child_cap_reported_usd_atoms, terminal_charged_usd_atoms, terminal_released_usd_atoms, write_off_usd_atoms, pricing_snapshot_id, pricing_snapshot_fingerprint, pricing_policy_version, pricing_decision_at, pricing_selector_key, pricing_contract_version, fee_policy_version, microlease_policy_version, issued_at, debit_cutoff_at, expires_at, closed_at, last_checkpoint_sequence, last_checkpoint_fingerprint, idempotency_record_id, stored_outcome_id, safe_metadata, created_at, updated_at
FROM spending_microleases
WHERE state IN ('active', 'cutoff', 'closing', 'expired')
  AND expires_at <= $1
ORDER BY expires_at, microlease_id
LIMIT $2
`

type ListStaleSpendingMicroleasesParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListStaleSpendingMicroleases(ctx context.Context, arg ListStaleSpendingMicroleasesParams) ([]SpendingMicrolease, error) {
	rows, err := q.db.Query(ctx, listStaleSpendingMicroleases, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpendingMicrolease
	for rows.Next() {
		var i SpendingMicrolease
		if err := rows.Scan(
			&i.MicroleaseID,
			&i.AccountID,
			&i.AccountScopeKey,
			&i.ProxyAllocatorOwnerID,
			&i.MicroleaseGeneration,
			&i.LeaseFence,
			&i.State,
			&i.IssuedCapUsdAtoms,
			&i.AvailableChildCapUsdAtoms,
			&i.AllocatedChildCapReportedUsdAtoms,
			&i.TerminalChargedUsdAtoms,
			&i.TerminalReleasedUsdAtoms,
			&i.WriteOffUsdAtoms,
			&i.PricingSnapshotID,
			&i.PricingSnapshotFingerprint,
			&i.PricingPolicyVersion,
			&i.PricingDecisionAt,
			&i.PricingSelectorKey,
			&i.PricingContractVersion,
			&i.FeePolicyVersion,
			&i.MicroleasePolicyVersion,
			&i.IssuedAt,
			&i.DebitCutoffAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.LastCheckpointSequence,
			&i.LastCheckpointFingerprint,
			&i.IdempotencyRecordID,
			&i.StoredOutcomeID,
			&i.SafeMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBillingEventInboxByBusinessIdentity = `-- name: LockBillingEventInboxByBusinessIdentity :one
SELECT inbox_id, topic, partition_id, offset_value, event_id, producer_identity, business_identity_type, business_identity_value, event_fingerprint, state, failure_class, safe_metadata, received_at, applied_at, updated_at
FROM billing_event_inbox
WHERE topic = $1
  AND business_identity_type = $2
  AND business_identity_value = $3
FOR UPDATE
`

type LockBillingEventInboxByBusinessIdentityParams struct {
	Topic                 string
	BusinessIdentityType  string
	BusinessIdentityValue string
}

func (q *Queries) LockBillingEventInboxByBusinessIdentity(ctx context.Context, arg LockBillingEventInboxByBusinessIdentityParams) (BillingEventInbox, error) {
	row := q.db.QueryRow(ctx, lockBillingEventInboxByBusinessIdentity, arg.Topic, arg.BusinessIdentityType, arg.BusinessIdentityValue)
	var i BillingEventInbox
	err := row.Scan(
		&i.InboxID,
		&i.Topic,
		&i.PartitionID,
		&i.OffsetValue,
		&i.EventID,
		&i.ProducerIdentity,
		&i.BusinessIdentityType,
		&i.BusinessIdentityValue,
		&i.EventFingerprint,
		&i.State,
		&i.FailureClass,
		&i.SafeMetadata,
		&i.ReceivedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMicroleaseChildDebit = `-- name: LockMicroleaseChildDebit :one
SELECT microlease_child_debit_id, microlease_id, debit_authorization_id, usage_operation_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, child_sequence, child_cap_usd_atoms, charged_usd_atoms, released_usd_atoms, write_off_usd_atoms, request_basis_fingerprint, terminal_basis_fingerprint, pricing_snapshot_id, pricing_snapshot_fingerprint, terminal_kind, state, qualified_inference_evidence_id, terminal_event_id, terminal_inbox_id, ledger_entry_id, settlement_effect_id, safe_metadata, created_at, terminal_at, settled_at, updated_at
FROM microlease_child_debits
WHERE microlease_child_debit_id = $1
FOR UPDATE
`

func (q *Queries) LockMicroleaseChildDebit(ctx context.Context, microleaseChildDebitID pgtype.UUID) (MicroleaseChildDebit, error) {
	row := q.db.QueryRow(ctx, lockMicroleaseChildDebit, microleaseChildDebitID)
	var i MicroleaseChildDebit
	err := row.Scan(
		&i.MicroleaseChildDebitID,
		&i.MicroleaseID,
		&i.DebitAuthorizationID,
		&i.UsageOperationID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.ChildSequence,
		&i.ChildCapUsdAtoms,
		&i.ChargedUsdAtoms,
		&i.ReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.RequestBasisFingerprint,
		&i.TerminalBasisFingerprint,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.TerminalKind,
		&i.State,
		&i.QualifiedInferenceEvidenceID,
		&i.TerminalEventID,
		&i.TerminalInboxID,
		&i.LedgerEntryID,
		&i.SettlementEffectID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.TerminalAt,
		&i.SettledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSpendingMicrolease = `-- name: LockSpendingMicrolease :one
SELECT microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, lease_fence, state, issued_cap_usd_atoms, available_child_cap_usd_atoms, allocated_child_cap_reported_usd_atoms, terminal_charged_usd_atoms, terminal_released_usd_atoms, write_off_usd_atoms, pricing_snapshot_id, pricing_snapshot_fingerprint, pricing_policy_version, pricing_decision_at, pricing_selector_key, pricing_contract_version, fee_policy_version, microlease_policy_version, issued_at, debit_cutoff_at, expires_at, closed_at, last_checkpoint_sequence, last_checkpoint_fingerprint, idempotency_record_id, stored_outcome_id, safe_metadata, created_at, updated_at
FROM spending_microleases
WHERE microlease_id = $1
FOR UPDATE
`

func (q *Queries) LockSpendingMicrolease(ctx context.Context, microleaseID pgtype.UUID) (SpendingMicrolease, error) {
	row := q.db.QueryRow(ctx, lockSpendingMicrolease, microleaseID)
	var i SpendingMicrolease
	err := row.Scan(
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.LeaseFence,
		&i.State,
		&i.IssuedCapUsdAtoms,
		&i.AvailableChildCapUsdAtoms,
		&i.AllocatedChildCapReportedUsdAtoms,
		&i.TerminalChargedUsdAtoms,
		&i.TerminalReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.PricingPolicyVersion,
		&i.PricingDecisionAt,
		&i.PricingSelectorKey,
		&i.PricingContractVersion,
		&i.FeePolicyVersion,
		&i.MicroleasePolicyVersion,
		&i.IssuedAt,
		&i.DebitCutoffAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.LastCheckpointSequence,
		&i.LastCheckpointFingerprint,
		&i.IdempotencyRecordID,
		&i.StoredOutcomeID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBillingEventInboxApplied = `-- name: MarkBillingEventInboxApplied :one
UPDATE billing_event_inbox
SET
    state = 'applied',
    failure_class = NULL,
    applied_at = $2,
    updated_at = $2
WHERE inbox_id = $1
  AND state IN ('received', 'duplicate', 'applied')
RETURNING inbox_id, topic, partition_id, offset_value, event_id, producer_identity, business_identity_type, business_identity_value, event_fingerprint, state, failure_class, safe_metadata, received_at, applied_at, updated_at
`

type MarkBillingEventInboxAppliedParams struct {
	InboxID   pgtype.UUID
	AppliedAt pgtype.Timestamptz
}

func (q *Queries) MarkBillingEventInboxApplied(ctx context.Context, arg MarkBillingEventInboxAppliedParams) (BillingEventInbox, error) {
	row := q.db.QueryRow(ctx, markBillingEventInboxApplied, arg.InboxID, arg.AppliedAt)
	var i BillingEventInbox
	err := row.Scan(
		&i.InboxID,
		&i.Topic,
		&i.PartitionID,
		&i.OffsetValue,
		&i.EventID,
		&i.ProducerIdentity,
		&i.BusinessIdentityType,
		&i.BusinessIdentityValue,
		&i.EventFingerprint,
		&i.State,
		&i.FailureClass,
		&i.SafeMetadata,
		&i.ReceivedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBillingEventInboxConflict = `-- name: MarkBillingEventInboxConflict :one
UPDATE billing_event_inbox
SET
    state = 'conflict',
    failure_class = $2,
    safe_metadata = $3,
    updated_at = $4
WHERE inbox_id = $1
RETURNING inbox_id, topic, partition_id, offset_value, event_id, producer_identity, business_identity_type, business_identity_value, event_fingerprint, state, failure_class, safe_metadata, received_at, applied_at, updated_at
`

type MarkBillingEventInboxConflictParams struct {
	InboxID      pgtype.UUID
	FailureClass *string
	SafeMetadata []byte
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) MarkBillingEventInboxConflict(ctx context.Context, arg MarkBillingEventInboxConflictParams) (BillingEventInbox, error) {
	row := q.db.QueryRow(ctx, markBillingEventInboxConflict,
		arg.InboxID,
		arg.FailureClass,
		arg.SafeMetadata,
		arg.UpdatedAt,
	)
	var i BillingEventInbox
	err := row.Scan(
		&i.InboxID,
		&i.Topic,
		&i.PartitionID,
		&i.OffsetValue,
		&i.EventID,
		&i.ProducerIdentity,
		&i.BusinessIdentityType,
		&i.BusinessIdentityValue,
		&i.EventFingerprint,
		&i.State,
		&i.FailureClass,
		&i.SafeMetadata,
		&i.ReceivedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBillingOutboxFailed = `-- name: MarkBillingOutboxFailed :one
UPDATE billing_outbox
SET
    state = 'failed',
    next_attempt_at = $2,
    updated_at = $3
WHERE outbox_id = $1
RETURNING outbox_id, event_type, aggregate_type, aggregate_id, event_fingerprint, safe_payload, state, attempt_count, next_attempt_at, published_at, created_at, updated_at
`

type MarkBillingOutboxFailedParams struct {
	OutboxID      pgtype.UUID
	NextAttemptAt pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) MarkBillingOutboxFailed(ctx context.Context, arg MarkBillingOutboxFailedParams) (BillingOutbox, error) {
	row := q.db.QueryRow(ctx, markBillingOutboxFailed, arg.OutboxID, arg.NextAttemptAt, arg.UpdatedAt)
	var i BillingOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventFingerprint,
		&i.SafePayload,
		&i.State,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBillingOutboxPublished = `-- name: MarkBillingOutboxPublished :one
UPDATE billing_outbox
SET
    state = 'published',
    published_at = $2,
    updated_at = $2
WHERE outbox_id = $1
RETURNING outbox_id, event_type, aggregate_type, aggregate_id, event_fingerprint, safe_payload, state, attempt_count, next_attempt_at, published_at, created_at, updated_at
`

type MarkBillingOutboxPublishedParams struct {
	OutboxID    pgtype.UUID
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) MarkBillingOutboxPublished(ctx context.Context, arg MarkBillingOutboxPublishedParams) (BillingOutbox, error) {
	row := q.db.QueryRow(ctx, markBillingOutboxPublished, arg.OutboxID, arg.PublishedAt)
	var i BillingOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventFingerprint,
		&i.SafePayload,
		&i.State,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMicroleaseChildDebitTerminal = `-- name: UpdateMicroleaseChildDebitTerminal :one
UPDATE microlease_child_debits
SET
    terminal_basis_fingerprint = $2,
    terminal_kind = $3,
    state = $4,
    charged_usd_atoms = $5,
    released_usd_atoms = $6,
    write_off_usd_atoms = $7,
    qualified_inference_evidence_id = $8,
    terminal_event_id = $9,
    terminal_inbox_id = $10,
    ledger_entry_id = $11,
    settlement_effect_id = $12,
    terminal_at = $13,
    settled_at = $14,
    updated_at = $15
WHERE microlease_child_debit_id = $1
RETURNING microlease_child_debit_id, microlease_id, debit_authorization_id, usage_operation_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, child_sequence, child_cap_usd_atoms, charged_usd_atoms, released_usd_atoms, write_off_usd_atoms, request_basis_fingerprint, terminal_basis_fingerprint, pricing_snapshot_id, pricing_snapshot_fingerprint, terminal_kind, state, qualified_inference_evidence_id, terminal_event_id, terminal_inbox_id, ledger_entry_id, settlement_effect_id, safe_metadata, created_at, terminal_at, settled_at, updated_at
`

type UpdateMicroleaseChildDebitTerminalParams struct {
	MicroleaseChildDebitID       pgtype.UUID
	TerminalBasisFingerprint     *string
	TerminalKind                 string
	State                        string
	ChargedUsdAtoms              int64
	ReleasedUsdAtoms             int64
	WriteOffUsdAtoms             int64
	QualifiedInferenceEvidenceID pgtype.UUID
	TerminalEventID              *string
	TerminalInboxID              pgtype.UUID
	LedgerEntryID                pgtype.UUID
	SettlementEffectID           pgtype.UUID
	TerminalAt                   pgtype.Timestamptz
	SettledAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

func (q *Queries) UpdateMicroleaseChildDebitTerminal(ctx context.Context, arg UpdateMicroleaseChildDebitTerminalParams) (MicroleaseChildDebit, error) {
	row := q.db.QueryRow(ctx, updateMicroleaseChildDebitTerminal,
		arg.MicroleaseChildDebitID,
		arg.TerminalBasisFingerprint,
		arg.TerminalKind,
		arg.State,
		arg.ChargedUsdAtoms,
		arg.ReleasedUsdAtoms,
		arg.WriteOffUsdAtoms,
		arg.QualifiedInferenceEvidenceID,
		arg.TerminalEventID,
		arg.TerminalInboxID,
		arg.LedgerEntryID,
		arg.SettlementEffectID,
		arg.TerminalAt,
		arg.SettledAt,
		arg.UpdatedAt,
	)
	var i MicroleaseChildDebit
	err := row.Scan(
		&i.MicroleaseChildDebitID,
		&i.MicroleaseID,
		&i.DebitAuthorizationID,
		&i.UsageOperationID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.ChildSequence,
		&i.ChildCapUsdAtoms,
		&i.ChargedUsdAtoms,
		&i.ReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.RequestBasisFingerprint,
		&i.TerminalBasisFingerprint,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.TerminalKind,
		&i.State,
		&i.QualifiedInferenceEvidenceID,
		&i.TerminalEventID,
		&i.TerminalInboxID,
		&i.LedgerEntryID,
		&i.SettlementEffectID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.TerminalAt,
		&i.SettledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSpendingMicroleaseSettlementTotals = `-- name: UpdateSpendingMicroleaseSettlementTotals :one
UPDATE spending_microleases
SET
    state = $2,
    available_child_cap_usd_atoms = $3,
    allocated_child_cap_reported_usd_atoms = $4,
    terminal_charged_usd_atoms = $5,
    terminal_released_usd_atoms = $6,
    write_off_usd_atoms = $7,
    last_checkpoint_sequence = $8,
    last_checkpoint_fingerprint = $9,
    closed_at = $10,
    updated_at = $11
WHERE microlease_id = $1
RETURNING microlease_id, account_id, account_scope_key, proxy_allocator_owner_id, microlease_generation, lease_fence, state, issued_cap_usd_atoms, available_child_cap_usd_atoms, allocated_child_cap_reported_usd_atoms, terminal_charged_usd_atoms, terminal_released_usd_atoms, write_off_usd_atoms, pricing_snapshot_id, pricing_snapshot_fingerprint, pricing_policy_version, pricing_decision_at, pricing_selector_key, pricing_contract_version, fee_policy_version, microlease_policy_version, issued_at, debit_cutoff_at, expires_at, closed_at, last_checkpoint_sequence, last_checkpoint_fingerprint, idempotency_record_id, stored_outcome_id, safe_metadata, created_at, updated_at
`

type UpdateSpendingMicroleaseSettlementTotalsParams struct {
	MicroleaseID                      pgtype.UUID
	State                             string
	AvailableChildCapUsdAtoms         int64
	AllocatedChildCapReportedUsdAtoms int64
	TerminalChargedUsdAtoms           int64
	TerminalReleasedUsdAtoms          int64
	WriteOffUsdAtoms                  int64
	LastCheckpointSequence            int64
	LastCheckpointFingerprint         *string
	ClosedAt                          pgtype.Timestamptz
	UpdatedAt                         pgtype.Timestamptz
}

func (q *Queries) UpdateSpendingMicroleaseSettlementTotals(ctx context.Context, arg UpdateSpendingMicroleaseSettlementTotalsParams) (SpendingMicrolease, error) {
	row := q.db.QueryRow(ctx, updateSpendingMicroleaseSettlementTotals,
		arg.MicroleaseID,
		arg.State,
		arg.AvailableChildCapUsdAtoms,
		arg.AllocatedChildCapReportedUsdAtoms,
		arg.TerminalChargedUsdAtoms,
		arg.TerminalReleasedUsdAtoms,
		arg.WriteOffUsdAtoms,
		arg.LastCheckpointSequence,
		arg.LastCheckpointFingerprint,
		arg.ClosedAt,
		arg.UpdatedAt,
	)
	var i SpendingMicrolease
	err := row.Scan(
		&i.MicroleaseID,
		&i.AccountID,
		&i.AccountScopeKey,
		&i.ProxyAllocatorOwnerID,
		&i.MicroleaseGeneration,
		&i.LeaseFence,
		&i.State,
		&i.IssuedCapUsdAtoms,
		&i.AvailableChildCapUsdAtoms,
		&i.AllocatedChildCapReportedUsdAtoms,
		&i.TerminalChargedUsdAtoms,
		&i.TerminalReleasedUsdAtoms,
		&i.WriteOffUsdAtoms,
		&i.PricingSnapshotID,
		&i.PricingSnapshotFingerprint,
		&i.PricingPolicyVersion,
		&i.PricingDecisionAt,
		&i.PricingSelectorKey,
		&i.PricingContractVersion,
		&i.FeePolicyVersion,
		&i.MicroleasePolicyVersion,
		&i.IssuedAt,
		&i.DebitCutoffAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.LastCheckpointSequence,
		&i.LastCheckpointFingerprint,
		&i.IdempotencyRecordID,
		&i.StoredOutcomeID,
		&i.SafeMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBillingAdmissionControl = `-- name: UpsertBillingAdmissionControl :one
INSERT INTO billing_admission_controls (
    admission_control_id,
    scope_kind,
    scope_key,
    use_class,
    state,
    reason_code,
    terminal_lag_bucket,
    stale_age_bucket,
    reconciliation_backlog_bucket,
    audited_actor_kind,
    audited_actor_id,
    safe_metadata,
    expires_at,
    renewed_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $15)
ON CONFLICT (scope_kind, scope_key, use_class)
DO UPDATE SET
    state = EXCLUDED.state,
    reason_code = EXCLUDED.reason_code,
    terminal_lag_bucket = EXCLUDED.terminal_lag_bucket,
    stale_age_bucket = EXCLUDED.stale_age_bucket,
    reconciliation_backlog_bucket = EXCLUDED.reconciliation_backlog_bucket,
    audited_actor_kind = EXCLUDED.audited_actor_kind,
    audited_actor_id = EXCLUDED.audited_actor_id,
    safe_metadata = EXCLUDED.safe_metadata,
    expires_at = EXCLUDED.expires_at,
    renewed_at = EXCLUDED.renewed_at,
    updated_at = EXCLUDED.updated_at
RETURNING admission_control_id, scope_kind, scope_key, use_class, state, reason_code, terminal_lag_bucket, stale_age_bucket, reconciliation_backlog_bucket, audited_actor_kind, audited_actor_id, safe_metadata, expires_at, renewed_at, created_at, updated_at
`

type UpsertBillingAdmissionControlParams struct {
	AdmissionControlID          pgtype.UUID
	ScopeKind                   string
	ScopeKey                    string
	UseClass                    string
	State                       string
	ReasonCode                  string
	TerminalLagBucket           string
	StaleAgeBucket              string
	ReconciliationBacklogBucket string
	AuditedActorKind            string
	AuditedActorID              string
	SafeMetadata                []byte
	ExpiresAt                   pgtype.Timestamptz
	RenewedAt                   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) UpsertBillingAdmissionControl(ctx context.Context, arg UpsertBillingAdmissionControlParams) (BillingAdmissionControl, error) {
	row := q.db.QueryRow(ctx, upsertBillingAdmissionControl,
		arg.AdmissionControlID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.UseClass,
		arg.State,
		arg.ReasonCode,
		arg.TerminalLagBucket,
		arg.StaleAgeBucket,
		arg.ReconciliationBacklogBucket,
		arg.AuditedActorKind,
		arg.AuditedActorID,
		arg.SafeMetadata,
		arg.ExpiresAt,
		arg.RenewedAt,
		arg.CreatedAt,
	)
	var i BillingAdmissionControl
	err := row.Scan(
		&i.AdmissionControlID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.UseClass,
		&i.State,
		&i.ReasonCode,
		&i.TerminalLagBucket,
		&i.StaleAgeBucket,
		&i.ReconciliationBacklogBucket,
		&i.AuditedActorKind,
		&i.AuditedActorID,
		&i.SafeMetadata,
		&i.ExpiresAt,
		&i.RenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
