// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxCommitReceipt struct {
	EventID             string
	FingerprintVersion  int16
	EnvelopeFingerprint []byte
}

type OutboxEvent struct {
	ID                   string
	EventType            string
	Source               string
	Destination          string
	SchemaName           string
	OccurredAt           pgtype.Timestamptz
	Payload              []byte
	Metadata             []byte
	TraceContext         []byte
	OrderingKey          *string
	OrderingSequence     *int64
	OrderingReady        bool
	CreatedAt            pgtype.Timestamptz
	AvailableAt          pgtype.Timestamptz
	CycleAttemptCount    int32
	TotalAttemptCount    int64
	LastAttemptAt        pgtype.Timestamptz
	LeaseToken           *string
	LeaseExpiresAt       pgtype.Timestamptz
	PublishedAt          pgtype.Timestamptz
	PoisonedAt           pgtype.Timestamptz
	PublicationUncertain *bool
	LastErrorClass       *string
	RedriveCount         int32
	LastRedriveID        *string
	LastRedrivenAt       pgtype.Timestamptz
}

type OutboxOrderingHead struct {
	OrderingKey     string
	LastSequence    int64
	CurrentSequence *int64
	UpdatedAt       pgtype.Timestamptz
}

type OutboxRedrife struct {
	AuditID     string
	EventID     string
	ActionKind  string
	RedrivenAt  pgtype.Timestamptz
	CycleNumber *int32
}

type PostgresHttpIdempotency struct {
	IdentityToken                 []byte
	Generation                    int64
	Phase                         string
	ProvisionalFingerprintVersion *string
	ProvisionalFingerprint        []byte
	FingerprintVersion            *string
	Fingerprint                   []byte
	Result                        []byte
	ResultMaxBytes                *int64
	ReplayNanos                   *int64
	DuplicateRiskNanos            *int64
	DuplicateRiskPermanent        *bool
	RecoverAfter                  pgtype.Timestamptz
	CommittedAt                   pgtype.Timestamptz
}

type PostgresInboxClaim struct {
	ConsumerIdentity string
	MessageID        string
}
