// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboundWebhookReceipt struct {
	ReceiptID      string
	EndpointID     string
	DeliveryID     string
	BodySha256     []byte
	SignedAt       pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	Payload        []byte
	Outcome        string
	TerminalReason *string
	TerminalAt     pgtype.Timestamptz
}
