// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postgres_http_idempotency.sql

package sqlcgen

import (
	"context"
)

const claimHTTPIdempotency = `-- name: ClaimHTTPIdempotency :one
INSERT INTO postgres_http_idempotency (
    identity_token,
    fingerprint_version,
    fingerprint
)
SELECT
    $1::bytea,
    $2::smallint,
    $3::bytea
WHERE NOT pg_is_in_recovery()
  AND current_setting('transaction_read_only') = 'off'
ON CONFLICT (identity_token) DO UPDATE
SET
    fingerprint_version = EXCLUDED.fingerprint_version,
    fingerprint = EXCLUDED.fingerprint,
    result = NULL,
    expires_at = NULL
WHERE postgres_http_idempotency.expires_at <= clock_timestamp()
RETURNING identity_token
`

type ClaimHTTPIdempotencyParams struct {
	IdentityToken      []byte
	FingerprintVersion int16
	Fingerprint        []byte
}

func (q *Queries) ClaimHTTPIdempotency(ctx context.Context, arg ClaimHTTPIdempotencyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, claimHTTPIdempotency, arg.IdentityToken, arg.FingerprintVersion, arg.Fingerprint)
	var identity_token []byte
	err := row.Scan(&identity_token)
	return identity_token, err
}

const cleanupHTTPIdempotency = `-- name: CleanupHTTPIdempotency :execrows
WITH expired AS (
    SELECT identity_token
    FROM postgres_http_idempotency
    WHERE expires_at <= clock_timestamp()
    ORDER BY expires_at, identity_token
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
DELETE FROM postgres_http_idempotency AS target
USING expired
WHERE target.identity_token = expired.identity_token
`

func (q *Queries) CleanupHTTPIdempotency(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupHTTPIdempotency, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeHTTPIdempotency = `-- name: CompleteHTTPIdempotency :one
UPDATE postgres_http_idempotency
SET
    result = $1::bytea,
    expires_at = clock_timestamp()
        + $2::bigint * interval '1 microsecond'
WHERE identity_token = $3::bytea
  AND result IS NULL
RETURNING result
`

type CompleteHTTPIdempotencyParams struct {
	Result          []byte
	RetentionMicros int64
	IdentityToken   []byte
}

func (q *Queries) CompleteHTTPIdempotency(ctx context.Context, arg CompleteHTTPIdempotencyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, completeHTTPIdempotency, arg.Result, arg.RetentionMicros, arg.IdentityToken)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const readHTTPIdempotency = `-- name: ReadHTTPIdempotency :one
WITH input AS (
    SELECT $1::bytea AS identity_token
)
SELECT
    (entry.identity_token IS NOT NULL)::boolean AS row_exists,
    (NOT pg_is_in_recovery()
        AND current_setting('transaction_read_only') = 'off')::boolean AS writer_primary,
    coalesce(entry.expires_at > clock_timestamp(), FALSE)::boolean AS live,
    entry.fingerprint_version,
    entry.fingerprint,
    entry.result
FROM input
LEFT JOIN postgres_http_idempotency AS entry USING (identity_token)
`

type ReadHTTPIdempotencyRow struct {
	RowExists          bool
	WriterPrimary      bool
	Live               bool
	FingerprintVersion *int16
	Fingerprint        []byte
	Result             []byte
}

func (q *Queries) ReadHTTPIdempotency(ctx context.Context, identityToken []byte) (ReadHTTPIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, readHTTPIdempotency, identityToken)
	var i ReadHTTPIdempotencyRow
	err := row.Scan(
		&i.RowExists,
		&i.WriterPrimary,
		&i.Live,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.Result,
	)
	return i, err
}
