// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postgres_jobs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPostgresJobsProducerAuthority = `-- name: CheckPostgresJobsProducerAuthority :one
SELECT
    (NOT pg_is_in_recovery()
        AND current_setting('transaction_read_only') = 'off')::boolean AS writer_primary,
    (has_table_privilege(current_user, 'postgres_jobs', 'SELECT')
        AND has_table_privilege(current_user, 'postgres_jobs', 'INSERT'))::boolean AS producer_privileges
`

type CheckPostgresJobsProducerAuthorityRow struct {
	WriterPrimary      bool
	ProducerPrivileges bool
}

func (q *Queries) CheckPostgresJobsProducerAuthority(ctx context.Context) (CheckPostgresJobsProducerAuthorityRow, error) {
	row := q.db.QueryRow(ctx, checkPostgresJobsProducerAuthority)
	var i CheckPostgresJobsProducerAuthorityRow
	err := row.Scan(&i.WriterPrimary, &i.ProducerPrivileges)
	return i, err
}

const claimPostgresJobs = `-- name: ClaimPostgresJobs :many
WITH input_keys AS MATERIALIZED (
    SELECT kind.kind, args.args_version, policy.policy_version
    FROM unnest($1::text[]) WITH ORDINALITY AS kind(kind, position)
    JOIN unnest($2::text[]) WITH ORDINALITY AS args(args_version, position) USING (position)
    JOIN unnest($3::text[]) WITH ORDINALITY AS policy(policy_version, position) USING (position)
),
observed AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
),
uncovered AS MATERIALIZED (
    SELECT DISTINCT job.kind, job.args_version, job.policy_version
    FROM postgres_jobs AS job
    WHERE NOT EXISTS (
        SELECT 1
        FROM input_keys AS key
        WHERE key.kind = job.kind
          AND key.args_version = job.args_version
          AND key.policy_version = job.policy_version
    )
),
missing AS MATERIALIZED (
    SELECT kind, args_version, policy_version
    FROM uncovered
    ORDER BY kind, args_version, policy_version
    LIMIT 16
),
scope AS MATERIALIZED (
    SELECT paused, scope_generation
    FROM postgres_job_claim_scopes
    WHERE work_class = 'neutral'
    FOR SHARE
),
eligible AS MATERIALIZED (
    SELECT job.logical_job_id
    FROM postgres_jobs AS job
    CROSS JOIN observed
    CROSS JOIN scope
    WHERE NOT EXISTS (SELECT 1 FROM uncovered)
      AND NOT scope.paused
      AND job.work_class = 'neutral'
      AND job.state IN ('ready', 'scheduled', 'retry_wait')
      AND job.available_at <= observed.observed_at
    ORDER BY job.available_at, job.logical_job_id
    LIMIT $4::integer
    FOR UPDATE OF job SKIP LOCKED
),
claimed AS (
    UPDATE postgres_jobs AS job
    SET state = 'running',
        attempt_generation = job.attempt_generation + 1,
        attempts_used = job.attempts_used + 1,
        current_worker_id = $5::text,
        lease_expires_at = observed.observed_at
            + $6::bigint * interval '1 microsecond',
        updated_at = observed.observed_at,
        terminal_at = NULL
    FROM eligible, observed
    WHERE job.logical_job_id = eligible.logical_job_id
    RETURNING
        job.logical_job_id,
        job.producer_scope,
        job.producer_key,
        job.occurrence_scope,
        job.occurrence_id,
        job.effect_scope,
        job.effect_key,
        job.kind,
        job.args_version,
        job.policy_version,
        job.payload,
        job.recovery_generation,
        job.attempt_generation,
        job.attempts_used,
        job.budget_started_at,
        job.current_worker_id,
        job.lease_expires_at,
        observed.observed_at AS started_at
),
inserted_attempts AS (
    INSERT INTO postgres_job_attempts (
        logical_job_id,
        attempt_generation,
        recovery_generation,
        attempt_number,
        worker_id,
        started_at,
        lease_expires_at
    )
    SELECT
        claimed.logical_job_id,
        claimed.attempt_generation,
        claimed.recovery_generation,
        claimed.attempts_used,
        claimed.current_worker_id,
        claimed.started_at,
        claimed.lease_expires_at
    FROM claimed
    RETURNING logical_job_id, attempt_generation
)
SELECT
    NOT EXISTS (SELECT 1 FROM uncovered)::boolean AS compatible,
    scope.paused,
    scope.scope_generation,
    observed.observed_at::timestamptz AS observed_at,
    ARRAY(SELECT kind FROM missing ORDER BY kind, args_version, policy_version)::text[] AS missing_kinds,
    ARRAY(SELECT args_version FROM missing ORDER BY kind, args_version, policy_version)::text[] AS missing_args_versions,
    ARRAY(SELECT policy_version FROM missing ORDER BY kind, args_version, policy_version)::text[] AS missing_policy_versions,
    claimed.logical_job_id,
    claimed.producer_scope,
    claimed.producer_key,
    claimed.occurrence_scope,
    claimed.occurrence_id,
    claimed.effect_scope,
    claimed.effect_key,
    claimed.kind,
    claimed.args_version,
    claimed.policy_version,
    claimed.payload,
    claimed.recovery_generation,
    claimed.attempt_generation,
    claimed.attempts_used,
    claimed.budget_started_at,
    claimed.current_worker_id,
    claimed.started_at::timestamptz AS started_at,
    claimed.lease_expires_at
FROM observed
CROSS JOIN scope
LEFT JOIN claimed ON EXISTS (
    SELECT 1
    FROM inserted_attempts
    WHERE inserted_attempts.logical_job_id = claimed.logical_job_id
      AND inserted_attempts.attempt_generation = claimed.attempt_generation
)
ORDER BY claimed.logical_job_id
`

type ClaimPostgresJobsParams struct {
	Kinds             []string
	ArgsVersions      []string
	PolicyVersions    []string
	ClaimLimit        int32
	WorkerID          string
	LeaseMicroseconds int64
}

type ClaimPostgresJobsRow struct {
	Compatible            *bool
	Paused                bool
	ScopeGeneration       int64
	ObservedAt            pgtype.Timestamptz
	MissingKinds          []string
	MissingArgsVersions   []string
	MissingPolicyVersions []string
	LogicalJobID          *string
	ProducerScope         *string
	ProducerKey           *string
	OccurrenceScope       *string
	OccurrenceID          *string
	EffectScope           *string
	EffectKey             *string
	Kind                  *string
	ArgsVersion           *string
	PolicyVersion         *string
	Payload               []byte
	RecoveryGeneration    *int64
	AttemptGeneration     *int64
	AttemptsUsed          *int32
	BudgetStartedAt       pgtype.Timestamptz
	CurrentWorkerID       *string
	StartedAt             pgtype.Timestamptz
	LeaseExpiresAt        pgtype.Timestamptz
}

func (q *Queries) ClaimPostgresJobs(ctx context.Context, arg ClaimPostgresJobsParams) ([]ClaimPostgresJobsRow, error) {
	rows, err := q.db.Query(ctx, claimPostgresJobs,
		arg.Kinds,
		arg.ArgsVersions,
		arg.PolicyVersions,
		arg.ClaimLimit,
		arg.WorkerID,
		arg.LeaseMicroseconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPostgresJobsRow
	for rows.Next() {
		var i ClaimPostgresJobsRow
		if err := rows.Scan(
			&i.Compatible,
			&i.Paused,
			&i.ScopeGeneration,
			&i.ObservedAt,
			&i.MissingKinds,
			&i.MissingArgsVersions,
			&i.MissingPolicyVersions,
			&i.LogicalJobID,
			&i.ProducerScope,
			&i.ProducerKey,
			&i.OccurrenceScope,
			&i.OccurrenceID,
			&i.EffectScope,
			&i.EffectKey,
			&i.Kind,
			&i.ArgsVersion,
			&i.PolicyVersion,
			&i.Payload,
			&i.RecoveryGeneration,
			&i.AttemptGeneration,
			&i.AttemptsUsed,
			&i.BudgetStartedAt,
			&i.CurrentWorkerID,
			&i.StartedAt,
			&i.LeaseExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finalizePostgresJobAttempt = `-- name: FinalizePostgresJobAttempt :one
WITH observed AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
),
locked_job AS MATERIALIZED (
    SELECT logical_job_id, producer_scope, producer_key, occurrence_scope, occurrence_id, effect_scope, effect_key, intent_fingerprint, kind, args_version, policy_version, payload, work_class, state, available_at, recovery_generation, attempt_generation, attempts_used, budget_started_at, current_worker_id, lease_expires_at, created_at, updated_at, terminal_at
    FROM postgres_jobs
    WHERE logical_job_id = $1::text
    FOR UPDATE
),
locked_attempt AS MATERIALIZED (
    SELECT attempt.logical_job_id, attempt.attempt_generation, attempt.recovery_generation, attempt.attempt_number, attempt.worker_id, attempt.started_at, attempt.lease_expires_at, attempt.finalized_at, attempt.final_state, attempt.outcome, attempt.effect_status, attempt.failure_code, attempt.retry_at, attempt.attempts_used, attempt.elapsed_used_milliseconds
    FROM postgres_job_attempts AS attempt
    JOIN locked_job ON locked_job.logical_job_id = attempt.logical_job_id
    WHERE attempt.attempt_generation = $2::bigint
      AND attempt.recovery_generation = $3::bigint
      AND attempt.worker_id = $4::text
    FOR UPDATE OF attempt
),
current_attempt AS MATERIALIZED (
    SELECT locked_job.logical_job_id
    FROM locked_job
    JOIN locked_attempt USING (logical_job_id)
    WHERE locked_attempt.finalized_at IS NULL
      AND locked_job.attempt_generation = $2::bigint
      AND locked_job.recovery_generation = $3::bigint
      AND locked_job.current_worker_id = $4::text
      AND locked_job.state IN ('running', 'cancel_requested')
),
updated_job AS (
    UPDATE postgres_jobs AS job
    SET state = $5::text,
        available_at = CASE
            WHEN $5::text = 'retry_wait'
            THEN observed.observed_at
                + $6::bigint * interval '1 microsecond'
            ELSE job.available_at
        END,
        attempts_used = $7::integer,
        current_worker_id = NULL,
        lease_expires_at = NULL,
        updated_at = observed.observed_at,
        terminal_at = CASE
            WHEN $5::text = 'retry_wait' THEN NULL
            ELSE observed.observed_at
        END
    FROM current_attempt, observed
    WHERE job.logical_job_id = current_attempt.logical_job_id
    RETURNING job.logical_job_id
),
updated_attempt AS (
    UPDATE postgres_job_attempts AS attempt
    SET finalized_at = observed.observed_at,
        final_state = $5::text,
        outcome = $8::text,
        effect_status = $9::text,
        failure_code = NULLIF($10::text, ''),
        retry_at = CASE
            WHEN $5::text = 'retry_wait'
            THEN observed.observed_at
                + $6::bigint * interval '1 microsecond'
            ELSE NULL
        END,
        attempts_used = $7::integer,
        elapsed_used_milliseconds = $11::bigint
    FROM updated_job, observed
    WHERE attempt.logical_job_id = updated_job.logical_job_id
      AND attempt.attempt_generation = $2::bigint
    RETURNING attempt.logical_job_id, attempt.attempt_generation, attempt.recovery_generation, attempt.attempt_number, attempt.worker_id, attempt.started_at, attempt.lease_expires_at, attempt.finalized_at, attempt.final_state, attempt.outcome, attempt.effect_status, attempt.failure_code, attempt.retry_at, attempt.attempts_used, attempt.elapsed_used_milliseconds
),
result_attempt AS MATERIALIZED (
    SELECT logical_job_id, attempt_generation, recovery_generation, attempt_number, worker_id, started_at, lease_expires_at, finalized_at, final_state, outcome, effect_status, failure_code, retry_at, attempts_used, elapsed_used_milliseconds FROM updated_attempt
    UNION ALL
    SELECT logical_job_id, attempt_generation, recovery_generation, attempt_number, worker_id, started_at, lease_expires_at, finalized_at, final_state, outcome, effect_status, failure_code, retry_at, attempts_used, elapsed_used_milliseconds FROM locked_attempt
    WHERE locked_attempt.finalized_at IS NOT NULL
    LIMIT 1
)
SELECT
    CASE
        WHEN EXISTS (SELECT 1 FROM updated_attempt) THEN 'applied'
        WHEN EXISTS (SELECT 1 FROM locked_attempt WHERE finalized_at IS NOT NULL) THEN 'repeated'
        WHEN NOT EXISTS (SELECT 1 FROM locked_job) THEN 'not_found'
        ELSE 'stale'
    END::text AS status,
    EXISTS (SELECT 1 FROM result_attempt)::boolean AS has_result,
    coalesce((SELECT final_state FROM result_attempt), '')::text AS final_state,
    coalesce((SELECT outcome FROM result_attempt), '')::text AS outcome,
    coalesce((SELECT effect_status FROM result_attempt), '')::text AS effect_status,
    coalesce((SELECT failure_code FROM result_attempt), '')::text AS failure_code,
    (SELECT retry_at FROM result_attempt)::timestamptz AS retry_at,
    coalesce((SELECT attempts_used FROM result_attempt), 0)::integer AS attempts_used,
    coalesce((SELECT elapsed_used_milliseconds FROM result_attempt), 0)::bigint AS elapsed_used_milliseconds,
    (SELECT finalized_at FROM result_attempt)::timestamptz AS finalized_at
`

type FinalizePostgresJobAttemptParams struct {
	LogicalJobID            string
	AttemptGeneration       int64
	RecoveryGeneration      int64
	WorkerID                string
	FinalState              string
	DelayMicroseconds       int64
	AttemptsUsed            int32
	Outcome                 string
	EffectStatus            string
	FailureCode             string
	ElapsedUsedMilliseconds int64
}

type FinalizePostgresJobAttemptRow struct {
	Status                  string
	HasResult               bool
	FinalState              string
	Outcome                 string
	EffectStatus            string
	FailureCode             string
	RetryAt                 pgtype.Timestamptz
	AttemptsUsed            int32
	ElapsedUsedMilliseconds int64
	FinalizedAt             pgtype.Timestamptz
}

func (q *Queries) FinalizePostgresJobAttempt(ctx context.Context, arg FinalizePostgresJobAttemptParams) (FinalizePostgresJobAttemptRow, error) {
	row := q.db.QueryRow(ctx, finalizePostgresJobAttempt,
		arg.LogicalJobID,
		arg.AttemptGeneration,
		arg.RecoveryGeneration,
		arg.WorkerID,
		arg.FinalState,
		arg.DelayMicroseconds,
		arg.AttemptsUsed,
		arg.Outcome,
		arg.EffectStatus,
		arg.FailureCode,
		arg.ElapsedUsedMilliseconds,
	)
	var i FinalizePostgresJobAttemptRow
	err := row.Scan(
		&i.Status,
		&i.HasResult,
		&i.FinalState,
		&i.Outcome,
		&i.EffectStatus,
		&i.FailureCode,
		&i.RetryAt,
		&i.AttemptsUsed,
		&i.ElapsedUsedMilliseconds,
		&i.FinalizedAt,
	)
	return i, err
}

const getPostgresJobsNeutralScope = `-- name: GetPostgresJobsNeutralScope :one
SELECT work_class
FROM postgres_job_claim_scopes
WHERE work_class = 'neutral'
`

func (q *Queries) GetPostgresJobsNeutralScope(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getPostgresJobsNeutralScope)
	var work_class string
	err := row.Scan(&work_class)
	return work_class, err
}

const insertPostgresJobAcceptance = `-- name: InsertPostgresJobAcceptance :one
INSERT INTO postgres_jobs (
    logical_job_id,
    producer_scope,
    producer_key,
    occurrence_scope,
    occurrence_id,
    effect_scope,
    effect_key,
    intent_fingerprint,
    kind,
    args_version,
    policy_version,
    payload,
    work_class,
    state,
    available_at
)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::bytea,
    $9::text,
    $10::text,
    $11::text,
    $12::bytea,
    'neutral',
    CASE
        WHEN $13::timestamptz <= clock_timestamp() THEN 'ready'
        ELSE 'scheduled'
    END,
    $13::timestamptz
)
ON CONFLICT DO NOTHING
RETURNING logical_job_id
`

type InsertPostgresJobAcceptanceParams struct {
	LogicalJobID      string
	ProducerScope     string
	ProducerKey       string
	OccurrenceScope   string
	OccurrenceID      string
	EffectScope       string
	EffectKey         string
	IntentFingerprint []byte
	Kind              string
	ArgsVersion       string
	PolicyVersion     string
	Payload           []byte
	AvailableAt       pgtype.Timestamptz
}

func (q *Queries) InsertPostgresJobAcceptance(ctx context.Context, arg InsertPostgresJobAcceptanceParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPostgresJobAcceptance,
		arg.LogicalJobID,
		arg.ProducerScope,
		arg.ProducerKey,
		arg.OccurrenceScope,
		arg.OccurrenceID,
		arg.EffectScope,
		arg.EffectKey,
		arg.IntentFingerprint,
		arg.Kind,
		arg.ArgsVersion,
		arg.PolicyVersion,
		arg.Payload,
		arg.AvailableAt,
	)
	var logical_job_id string
	err := row.Scan(&logical_job_id)
	return logical_job_id, err
}

const listExpiredPostgresJobAttempts = `-- name: ListExpiredPostgresJobAttempts :many
WITH observed AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
)
SELECT
    job.logical_job_id,
    job.kind,
    job.args_version,
    job.policy_version,
    job.state,
    job.recovery_generation,
    job.attempt_generation,
    job.attempts_used,
    job.current_worker_id,
    job.budget_started_at,
    attempt.started_at,
    attempt.lease_expires_at,
    observed.observed_at::timestamptz AS observed_at,
    greatest(
        0,
        floor(extract(epoch FROM observed.observed_at - job.budget_started_at) * 1000)
    )::bigint AS elapsed_milliseconds
FROM postgres_jobs AS job
JOIN postgres_job_attempts AS attempt
  ON attempt.logical_job_id = job.logical_job_id
 AND attempt.attempt_generation = job.attempt_generation
CROSS JOIN observed
WHERE job.state IN ('running', 'cancel_requested')
  AND job.current_worker_id IS NOT NULL
  AND job.lease_expires_at < observed.observed_at
  AND attempt.finalized_at IS NULL
ORDER BY job.lease_expires_at, job.logical_job_id
LIMIT $1::integer
`

type ListExpiredPostgresJobAttemptsRow struct {
	LogicalJobID        string
	Kind                string
	ArgsVersion         string
	PolicyVersion       string
	State               string
	RecoveryGeneration  int64
	AttemptGeneration   int64
	AttemptsUsed        int32
	CurrentWorkerID     *string
	BudgetStartedAt     pgtype.Timestamptz
	StartedAt           pgtype.Timestamptz
	LeaseExpiresAt      pgtype.Timestamptz
	ObservedAt          pgtype.Timestamptz
	ElapsedMilliseconds int64
}

func (q *Queries) ListExpiredPostgresJobAttempts(ctx context.Context, candidateLimit int32) ([]ListExpiredPostgresJobAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPostgresJobAttempts, candidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredPostgresJobAttemptsRow
	for rows.Next() {
		var i ListExpiredPostgresJobAttemptsRow
		if err := rows.Scan(
			&i.LogicalJobID,
			&i.Kind,
			&i.ArgsVersion,
			&i.PolicyVersion,
			&i.State,
			&i.RecoveryGeneration,
			&i.AttemptGeneration,
			&i.AttemptsUsed,
			&i.CurrentWorkerID,
			&i.BudgetStartedAt,
			&i.StartedAt,
			&i.LeaseExpiresAt,
			&i.ObservedAt,
			&i.ElapsedMilliseconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostgresJobsAcceptanceConflicts = `-- name: ListPostgresJobsAcceptanceConflicts :many
SELECT
    logical_job_id,
    intent_fingerprint
FROM postgres_jobs
WHERE logical_job_id = $1::text
   OR (producer_scope = $2::text
       AND producer_key = $3::text)
   OR (occurrence_scope = $4::text
       AND occurrence_id = $5::text)
   OR (effect_scope = $6::text
       AND effect_key = $7::text)
ORDER BY logical_job_id
`

type ListPostgresJobsAcceptanceConflictsParams struct {
	LogicalJobID    string
	ProducerScope   string
	ProducerKey     string
	OccurrenceScope string
	OccurrenceID    string
	EffectScope     string
	EffectKey       string
}

type ListPostgresJobsAcceptanceConflictsRow struct {
	LogicalJobID      string
	IntentFingerprint []byte
}

func (q *Queries) ListPostgresJobsAcceptanceConflicts(ctx context.Context, arg ListPostgresJobsAcceptanceConflictsParams) ([]ListPostgresJobsAcceptanceConflictsRow, error) {
	rows, err := q.db.Query(ctx, listPostgresJobsAcceptanceConflicts,
		arg.LogicalJobID,
		arg.ProducerScope,
		arg.ProducerKey,
		arg.OccurrenceScope,
		arg.OccurrenceID,
		arg.EffectScope,
		arg.EffectKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostgresJobsAcceptanceConflictsRow
	for rows.Next() {
		var i ListPostgresJobsAcceptanceConflictsRow
		if err := rows.Scan(&i.LogicalJobID, &i.IntentFingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostgresJobsSchemaColumns = `-- name: ListPostgresJobsSchemaColumns :many
SELECT
    table_name::text AS table_name,
    column_name::text AS column_name,
    data_type::text AS data_type,
    udt_name::text AS udt_name,
    is_nullable::text AS is_nullable,
    coalesce(column_default, '')::text AS column_default,
    coalesce(collation_name, '')::text AS collation_name
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name = ANY($1::text[])
ORDER BY table_name, ordinal_position
`

type ListPostgresJobsSchemaColumnsRow struct {
	TableName     string
	ColumnName    string
	DataType      string
	UdtName       string
	IsNullable    string
	ColumnDefault string
	CollationName string
}

func (q *Queries) ListPostgresJobsSchemaColumns(ctx context.Context, tableNames []string) ([]ListPostgresJobsSchemaColumnsRow, error) {
	rows, err := q.db.Query(ctx, listPostgresJobsSchemaColumns, tableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostgresJobsSchemaColumnsRow
	for rows.Next() {
		var i ListPostgresJobsSchemaColumnsRow
		if err := rows.Scan(
			&i.TableName,
			&i.ColumnName,
			&i.DataType,
			&i.UdtName,
			&i.IsNullable,
			&i.ColumnDefault,
			&i.CollationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostgresJobsSchemaConstraints = `-- name: ListPostgresJobsSchemaConstraints :many
SELECT
    relation.relname::text AS table_name,
    constraint_record.conname::text AS constraint_name,
    constraint_record.contype::text AS constraint_type,
    md5(pg_get_constraintdef(constraint_record.oid, true))::text AS definition_hash
FROM pg_catalog.pg_constraint AS constraint_record
JOIN pg_catalog.pg_class AS relation ON relation.oid = constraint_record.conrelid
JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
WHERE namespace.nspname = current_schema()
  AND relation.relname = ANY($1::text[])
ORDER BY relation.relname, constraint_record.conname
`

type ListPostgresJobsSchemaConstraintsRow struct {
	TableName      string
	ConstraintName string
	ConstraintType string
	DefinitionHash string
}

func (q *Queries) ListPostgresJobsSchemaConstraints(ctx context.Context, tableNames []string) ([]ListPostgresJobsSchemaConstraintsRow, error) {
	rows, err := q.db.Query(ctx, listPostgresJobsSchemaConstraints, tableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostgresJobsSchemaConstraintsRow
	for rows.Next() {
		var i ListPostgresJobsSchemaConstraintsRow
		if err := rows.Scan(
			&i.TableName,
			&i.ConstraintName,
			&i.ConstraintType,
			&i.DefinitionHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostgresJobsSchemaIndexes = `-- name: ListPostgresJobsSchemaIndexes :many
SELECT
    relation.relname::text AS table_name,
    index_relation.relname::text AS index_name,
    md5(pg_get_indexdef(index_record.indexrelid))::text AS definition_hash
FROM pg_catalog.pg_index AS index_record
JOIN pg_catalog.pg_class AS relation ON relation.oid = index_record.indrelid
JOIN pg_catalog.pg_class AS index_relation ON index_relation.oid = index_record.indexrelid
JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
WHERE namespace.nspname = current_schema()
  AND relation.relname = ANY($1::text[])
ORDER BY relation.relname, index_relation.relname
`

type ListPostgresJobsSchemaIndexesRow struct {
	TableName      string
	IndexName      string
	DefinitionHash string
}

func (q *Queries) ListPostgresJobsSchemaIndexes(ctx context.Context, tableNames []string) ([]ListPostgresJobsSchemaIndexesRow, error) {
	rows, err := q.db.Query(ctx, listPostgresJobsSchemaIndexes, tableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostgresJobsSchemaIndexesRow
	for rows.Next() {
		var i ListPostgresJobsSchemaIndexesRow
		if err := rows.Scan(&i.TableName, &i.IndexName, &i.DefinitionHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observePostgresJobs = `-- name: ObservePostgresJobs :one
WITH input_keys AS MATERIALIZED (
    SELECT kind.kind, args.args_version, policy.policy_version
    FROM unnest($1::text[]) WITH ORDINALITY AS kind(kind, position)
    JOIN unnest($2::text[]) WITH ORDINALITY AS args(args_version, position) USING (position)
    JOIN unnest($3::text[]) WITH ORDINALITY AS policy(policy_version, position) USING (position)
),
observed AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
),
inventory AS MATERIALIZED (
    SELECT DISTINCT kind, args_version, policy_version
    FROM postgres_jobs
),
state_counts AS MATERIALIZED (
    SELECT state, count(*)::bigint AS job_count, min(available_at) AS oldest_available_at
    FROM postgres_jobs
    GROUP BY state
)
SELECT
    observed.observed_at::timestamptz AS observed_at,
    NOT EXISTS (
        SELECT 1
        FROM inventory
        WHERE NOT EXISTS (
            SELECT 1
            FROM input_keys
            WHERE input_keys.kind = inventory.kind
              AND input_keys.args_version = inventory.args_version
              AND input_keys.policy_version = inventory.policy_version
        )
    )::boolean AS compatible,
    ARRAY(SELECT kind FROM inventory ORDER BY kind, args_version, policy_version)::text[] AS retained_kinds,
    ARRAY(SELECT args_version FROM inventory ORDER BY kind, args_version, policy_version)::text[] AS retained_args_versions,
    ARRAY(SELECT policy_version FROM inventory ORDER BY kind, args_version, policy_version)::text[] AS retained_policy_versions,
    ARRAY(SELECT state FROM state_counts ORDER BY state)::text[] AS states,
    ARRAY(SELECT job_count FROM state_counts ORDER BY state)::bigint[] AS state_counts,
    ARRAY(SELECT oldest_available_at FROM state_counts ORDER BY state)::timestamptz[] AS oldest_available_at
FROM observed
`

type ObservePostgresJobsParams struct {
	Kinds          []string
	ArgsVersions   []string
	PolicyVersions []string
}

type ObservePostgresJobsRow struct {
	ObservedAt             pgtype.Timestamptz
	Compatible             *bool
	RetainedKinds          []string
	RetainedArgsVersions   []string
	RetainedPolicyVersions []string
	States                 []string
	StateCounts            []int64
	OldestAvailableAt      []pgtype.Timestamptz
}

func (q *Queries) ObservePostgresJobs(ctx context.Context, arg ObservePostgresJobsParams) (ObservePostgresJobsRow, error) {
	row := q.db.QueryRow(ctx, observePostgresJobs, arg.Kinds, arg.ArgsVersions, arg.PolicyVersions)
	var i ObservePostgresJobsRow
	err := row.Scan(
		&i.ObservedAt,
		&i.Compatible,
		&i.RetainedKinds,
		&i.RetainedArgsVersions,
		&i.RetainedPolicyVersions,
		&i.States,
		&i.StateCounts,
		&i.OldestAvailableAt,
	)
	return i, err
}

const readPostgresJobsAcceptance = `-- name: ReadPostgresJobsAcceptance :one
WITH input AS (
    SELECT
        $1::text AS producer_scope,
        $2::text AS producer_key
)
SELECT
    (job.logical_job_id IS NOT NULL)::boolean AS row_exists,
    job.logical_job_id,
    job.producer_scope,
    job.producer_key,
    job.occurrence_scope,
    job.occurrence_id,
    job.effect_scope,
    job.effect_key,
    job.intent_fingerprint,
    (NOT pg_is_in_recovery()
        AND current_setting('transaction_read_only') = 'off')::boolean AS writer_primary
FROM input
LEFT JOIN postgres_jobs AS job USING (producer_scope, producer_key)
`

type ReadPostgresJobsAcceptanceParams struct {
	ProducerScope string
	ProducerKey   string
}

type ReadPostgresJobsAcceptanceRow struct {
	RowExists         bool
	LogicalJobID      *string
	ProducerScope     *string
	ProducerKey       *string
	OccurrenceScope   *string
	OccurrenceID      *string
	EffectScope       *string
	EffectKey         *string
	IntentFingerprint []byte
	WriterPrimary     bool
}

func (q *Queries) ReadPostgresJobsAcceptance(ctx context.Context, arg ReadPostgresJobsAcceptanceParams) (ReadPostgresJobsAcceptanceRow, error) {
	row := q.db.QueryRow(ctx, readPostgresJobsAcceptance, arg.ProducerScope, arg.ProducerKey)
	var i ReadPostgresJobsAcceptanceRow
	err := row.Scan(
		&i.RowExists,
		&i.LogicalJobID,
		&i.ProducerScope,
		&i.ProducerKey,
		&i.OccurrenceScope,
		&i.OccurrenceID,
		&i.EffectScope,
		&i.EffectKey,
		&i.IntentFingerprint,
		&i.WriterPrimary,
	)
	return i, err
}

const renewPostgresJobAttempts = `-- name: RenewPostgresJobAttempts :many
WITH input_attempts AS MATERIALIZED (
    SELECT job.logical_job_id, attempt.attempt_generation, recovery.recovery_generation, worker.worker_id
    FROM unnest($1::text[]) WITH ORDINALITY AS job(logical_job_id, position)
    JOIN unnest($2::bigint[]) WITH ORDINALITY AS attempt(attempt_generation, position) USING (position)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS recovery(recovery_generation, position) USING (position)
    JOIN unnest($4::text[]) WITH ORDINALITY AS worker(worker_id, position) USING (position)
),
observed AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
),
renewed_jobs AS (
    UPDATE postgres_jobs AS job
    SET lease_expires_at = observed.observed_at
            + $5::bigint * interval '1 microsecond',
        updated_at = observed.observed_at
    FROM input_attempts, observed
    WHERE job.logical_job_id = input_attempts.logical_job_id
      AND job.attempt_generation = input_attempts.attempt_generation
      AND job.recovery_generation = input_attempts.recovery_generation
      AND job.current_worker_id = input_attempts.worker_id
      AND job.state IN ('running', 'cancel_requested')
    RETURNING
        job.logical_job_id,
        job.attempt_generation,
        job.recovery_generation,
        job.current_worker_id,
        job.state,
        job.lease_expires_at,
        observed.observed_at
),
renewed_attempts AS (
    UPDATE postgres_job_attempts AS attempt
    SET lease_expires_at = renewed_jobs.lease_expires_at
    FROM renewed_jobs
    WHERE attempt.logical_job_id = renewed_jobs.logical_job_id
      AND attempt.attempt_generation = renewed_jobs.attempt_generation
      AND attempt.recovery_generation = renewed_jobs.recovery_generation
      AND attempt.worker_id = renewed_jobs.current_worker_id
      AND attempt.finalized_at IS NULL
    RETURNING attempt.logical_job_id, attempt.attempt_generation
)
SELECT
    renewed_jobs.logical_job_id,
    renewed_jobs.attempt_generation,
    renewed_jobs.recovery_generation,
    renewed_jobs.current_worker_id AS worker_id,
    renewed_jobs.observed_at::timestamptz AS observed_at,
    renewed_jobs.lease_expires_at,
    (renewed_jobs.state = 'cancel_requested')::boolean AS cancel_requested
FROM renewed_jobs
JOIN renewed_attempts USING (logical_job_id, attempt_generation)
ORDER BY renewed_jobs.logical_job_id, renewed_jobs.attempt_generation
`

type RenewPostgresJobAttemptsParams struct {
	LogicalJobIds       []string
	AttemptGenerations  []int64
	RecoveryGenerations []int64
	WorkerIds           []string
	LeaseMicroseconds   int64
}

type RenewPostgresJobAttemptsRow struct {
	LogicalJobID       string
	AttemptGeneration  int64
	RecoveryGeneration int64
	WorkerID           *string
	ObservedAt         pgtype.Timestamptz
	LeaseExpiresAt     pgtype.Timestamptz
	CancelRequested    bool
}

func (q *Queries) RenewPostgresJobAttempts(ctx context.Context, arg RenewPostgresJobAttemptsParams) ([]RenewPostgresJobAttemptsRow, error) {
	rows, err := q.db.Query(ctx, renewPostgresJobAttempts,
		arg.LogicalJobIds,
		arg.AttemptGenerations,
		arg.RecoveryGenerations,
		arg.WorkerIds,
		arg.LeaseMicroseconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenewPostgresJobAttemptsRow
	for rows.Next() {
		var i RenewPostgresJobAttemptsRow
		if err := rows.Scan(
			&i.LogicalJobID,
			&i.AttemptGeneration,
			&i.RecoveryGeneration,
			&i.WorkerID,
			&i.ObservedAt,
			&i.LeaseExpiresAt,
			&i.CancelRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescuePostgresJobAttempt = `-- name: RescuePostgresJobAttempt :one
WITH observed AS MATERIALIZED (
    SELECT clock_timestamp() AS observed_at
),
locked_job AS MATERIALIZED (
    SELECT logical_job_id, producer_scope, producer_key, occurrence_scope, occurrence_id, effect_scope, effect_key, intent_fingerprint, kind, args_version, policy_version, payload, work_class, state, available_at, recovery_generation, attempt_generation, attempts_used, budget_started_at, current_worker_id, lease_expires_at, created_at, updated_at, terminal_at
    FROM postgres_jobs
    WHERE logical_job_id = $1::text
    FOR UPDATE
),
locked_attempt AS MATERIALIZED (
    SELECT attempt.logical_job_id, attempt.attempt_generation, attempt.recovery_generation, attempt.attempt_number, attempt.worker_id, attempt.started_at, attempt.lease_expires_at, attempt.finalized_at, attempt.final_state, attempt.outcome, attempt.effect_status, attempt.failure_code, attempt.retry_at, attempt.attempts_used, attempt.elapsed_used_milliseconds
    FROM postgres_job_attempts AS attempt
    JOIN locked_job ON locked_job.logical_job_id = attempt.logical_job_id
    WHERE attempt.attempt_generation = $2::bigint
      AND attempt.recovery_generation = $3::bigint
      AND attempt.worker_id = $4::text
    FOR UPDATE OF attempt
),
current_expired AS MATERIALIZED (
    SELECT locked_job.logical_job_id
    FROM locked_job
    JOIN locked_attempt USING (logical_job_id)
    CROSS JOIN observed
    WHERE locked_attempt.finalized_at IS NULL
      AND locked_job.attempt_generation = $2::bigint
      AND locked_job.recovery_generation = $3::bigint
      AND locked_job.current_worker_id = $4::text
      AND locked_job.state IN ('running', 'cancel_requested')
      AND locked_job.lease_expires_at < observed.observed_at
),
updated_job AS (
    UPDATE postgres_jobs AS job
    SET state = $5::text,
        available_at = CASE
            WHEN $5::text = 'retry_wait'
            THEN observed.observed_at
                + $6::bigint * interval '1 microsecond'
            ELSE job.available_at
        END,
        attempts_used = $7::integer,
        current_worker_id = NULL,
        lease_expires_at = NULL,
        updated_at = observed.observed_at,
        terminal_at = CASE
            WHEN $5::text = 'retry_wait' THEN NULL
            ELSE observed.observed_at
        END
    FROM current_expired, observed
    WHERE job.logical_job_id = current_expired.logical_job_id
    RETURNING job.logical_job_id
),
updated_attempt AS (
    UPDATE postgres_job_attempts AS attempt
    SET finalized_at = observed.observed_at,
        final_state = $5::text,
        outcome = $8::text,
        effect_status = $9::text,
        failure_code = NULLIF($10::text, ''),
        retry_at = CASE
            WHEN $5::text = 'retry_wait'
            THEN observed.observed_at
                + $6::bigint * interval '1 microsecond'
            ELSE NULL
        END,
        attempts_used = $7::integer,
        elapsed_used_milliseconds = $11::bigint
    FROM updated_job, observed
    WHERE attempt.logical_job_id = updated_job.logical_job_id
      AND attempt.attempt_generation = $2::bigint
    RETURNING attempt.logical_job_id, attempt.attempt_generation, attempt.recovery_generation, attempt.attempt_number, attempt.worker_id, attempt.started_at, attempt.lease_expires_at, attempt.finalized_at, attempt.final_state, attempt.outcome, attempt.effect_status, attempt.failure_code, attempt.retry_at, attempt.attempts_used, attempt.elapsed_used_milliseconds
),
result_attempt AS MATERIALIZED (
    SELECT logical_job_id, attempt_generation, recovery_generation, attempt_number, worker_id, started_at, lease_expires_at, finalized_at, final_state, outcome, effect_status, failure_code, retry_at, attempts_used, elapsed_used_milliseconds FROM updated_attempt
    UNION ALL
    SELECT logical_job_id, attempt_generation, recovery_generation, attempt_number, worker_id, started_at, lease_expires_at, finalized_at, final_state, outcome, effect_status, failure_code, retry_at, attempts_used, elapsed_used_milliseconds FROM locked_attempt
    WHERE locked_attempt.finalized_at IS NOT NULL
    LIMIT 1
)
SELECT
    CASE
        WHEN EXISTS (SELECT 1 FROM updated_attempt) THEN 'applied'
        WHEN EXISTS (SELECT 1 FROM locked_attempt WHERE finalized_at IS NOT NULL) THEN 'repeated'
        WHEN NOT EXISTS (SELECT 1 FROM locked_job) THEN 'not_found'
        ELSE 'stale'
    END::text AS status,
    EXISTS (SELECT 1 FROM result_attempt)::boolean AS has_result,
    coalesce((SELECT final_state FROM result_attempt), '')::text AS final_state,
    coalesce((SELECT outcome FROM result_attempt), '')::text AS outcome,
    coalesce((SELECT effect_status FROM result_attempt), '')::text AS effect_status,
    coalesce((SELECT failure_code FROM result_attempt), '')::text AS failure_code,
    (SELECT retry_at FROM result_attempt)::timestamptz AS retry_at,
    coalesce((SELECT attempts_used FROM result_attempt), 0)::integer AS attempts_used,
    coalesce((SELECT elapsed_used_milliseconds FROM result_attempt), 0)::bigint AS elapsed_used_milliseconds,
    (SELECT finalized_at FROM result_attempt)::timestamptz AS finalized_at
`

type RescuePostgresJobAttemptParams struct {
	LogicalJobID            string
	AttemptGeneration       int64
	RecoveryGeneration      int64
	WorkerID                string
	FinalState              string
	DelayMicroseconds       int64
	AttemptsUsed            int32
	Outcome                 string
	EffectStatus            string
	FailureCode             string
	ElapsedUsedMilliseconds int64
}

type RescuePostgresJobAttemptRow struct {
	Status                  string
	HasResult               bool
	FinalState              string
	Outcome                 string
	EffectStatus            string
	FailureCode             string
	RetryAt                 pgtype.Timestamptz
	AttemptsUsed            int32
	ElapsedUsedMilliseconds int64
	FinalizedAt             pgtype.Timestamptz
}

func (q *Queries) RescuePostgresJobAttempt(ctx context.Context, arg RescuePostgresJobAttemptParams) (RescuePostgresJobAttemptRow, error) {
	row := q.db.QueryRow(ctx, rescuePostgresJobAttempt,
		arg.LogicalJobID,
		arg.AttemptGeneration,
		arg.RecoveryGeneration,
		arg.WorkerID,
		arg.FinalState,
		arg.DelayMicroseconds,
		arg.AttemptsUsed,
		arg.Outcome,
		arg.EffectStatus,
		arg.FailureCode,
		arg.ElapsedUsedMilliseconds,
	)
	var i RescuePostgresJobAttemptRow
	err := row.Scan(
		&i.Status,
		&i.HasResult,
		&i.FinalState,
		&i.Outcome,
		&i.EffectStatus,
		&i.FailureCode,
		&i.RetryAt,
		&i.AttemptsUsed,
		&i.ElapsedUsedMilliseconds,
		&i.FinalizedAt,
	)
	return i, err
}

const resolvePostgresJobsClaims = `-- name: ResolvePostgresJobsClaims :many
WITH input_attempts AS (
    SELECT job.logical_job_id, attempt.attempt_generation, recovery.recovery_generation, worker.worker_id
    FROM unnest($1::text[]) WITH ORDINALITY AS job(logical_job_id, position)
    JOIN unnest($2::bigint[]) WITH ORDINALITY AS attempt(attempt_generation, position) USING (position)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS recovery(recovery_generation, position) USING (position)
    JOIN unnest($4::text[]) WITH ORDINALITY AS worker(worker_id, position) USING (position)
)
SELECT
    input_attempts.logical_job_id::text AS logical_job_id,
    input_attempts.attempt_generation::bigint AS attempt_generation,
    input_attempts.recovery_generation::bigint AS recovery_generation,
    input_attempts.worker_id::text AS worker_id,
    (
        job.logical_job_id IS NOT NULL
        AND attempt.logical_job_id IS NOT NULL
    )::boolean AS committed
FROM input_attempts
LEFT JOIN postgres_jobs AS job
    ON job.logical_job_id = input_attempts.logical_job_id
   AND job.attempt_generation = input_attempts.attempt_generation
   AND job.recovery_generation = input_attempts.recovery_generation
   AND job.current_worker_id = input_attempts.worker_id
   AND job.state IN ('running', 'cancel_requested')
LEFT JOIN postgres_job_attempts AS attempt
    ON attempt.logical_job_id = input_attempts.logical_job_id
   AND attempt.attempt_generation = input_attempts.attempt_generation
   AND attempt.recovery_generation = input_attempts.recovery_generation
   AND attempt.worker_id = input_attempts.worker_id
ORDER BY input_attempts.logical_job_id, input_attempts.attempt_generation
`

type ResolvePostgresJobsClaimsParams struct {
	LogicalJobIds       []string
	AttemptGenerations  []int64
	RecoveryGenerations []int64
	WorkerIds           []string
}

type ResolvePostgresJobsClaimsRow struct {
	LogicalJobID       string
	AttemptGeneration  int64
	RecoveryGeneration int64
	WorkerID           string
	Committed          bool
}

func (q *Queries) ResolvePostgresJobsClaims(ctx context.Context, arg ResolvePostgresJobsClaimsParams) ([]ResolvePostgresJobsClaimsRow, error) {
	rows, err := q.db.Query(ctx, resolvePostgresJobsClaims,
		arg.LogicalJobIds,
		arg.AttemptGenerations,
		arg.RecoveryGenerations,
		arg.WorkerIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolvePostgresJobsClaimsRow
	for rows.Next() {
		var i ResolvePostgresJobsClaimsRow
		if err := rows.Scan(
			&i.LogicalJobID,
			&i.AttemptGeneration,
			&i.RecoveryGeneration,
			&i.WorkerID,
			&i.Committed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
