// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postgres_webhooks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWebhookRedriveCycle = `-- name: ActivateWebhookRedriveCycle :execrows
UPDATE webhook_deliveries
SET current_cycle = $1, state = 'ready', next_due_at = $2,
    sendable = true, terminal_at = NULL, updated_at = $2
WHERE owner_scope = $3 AND delivery_id = $4
  AND current_cycle = $5 AND state IN ('terminal', 'suspended')
`

type ActivateWebhookRedriveCycleParams struct {
	CycleNumber   int64
	AcceptedAt    pgtype.Timestamptz
	OwnerScope    string
	DeliveryID    string
	PreviousCycle int64
}

func (q *Queries) ActivateWebhookRedriveCycle(ctx context.Context, arg ActivateWebhookRedriveCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateWebhookRedriveCycle,
		arg.CycleNumber,
		arg.AcceptedAt,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.PreviousCycle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advanceWebhookClock = `-- name: AdvanceWebhookClock :one
WITH locked AS (
    SELECT high_water, regression FROM webhook_clock WHERE singleton FOR UPDATE
), sampled AS (
    SELECT clock_timestamp() AS sampled_at, high_water, regression FROM locked
), advanced AS (
    UPDATE webhook_clock c
    SET high_water = s.sampled_at, observed_at = s.sampled_at
    FROM sampled s
    WHERE c.singleton AND NOT s.regression AND s.sampled_at >= s.high_water
    RETURNING c.high_water
)
SELECT high_water AS sampled_at FROM advanced
`

func (q *Queries) AdvanceWebhookClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, advanceWebhookClock)
	var sampled_at pgtype.Timestamptz
	err := row.Scan(&sampled_at)
	return sampled_at, err
}

const advanceWebhookDestinationCursor = `-- name: AdvanceWebhookDestinationCursor :execrows
UPDATE webhook_destinations
SET last_considered_sequence = nextval('webhook_fairness_sequence'), updated_at = $1
WHERE owner_scope = $2
  AND destination_id = $3
  AND generation = $4
`

type AdvanceWebhookDestinationCursorParams struct {
	SampledAt     pgtype.Timestamptz
	OwnerScope    string
	DestinationID string
	Generation    int64
}

func (q *Queries) AdvanceWebhookDestinationCursor(ctx context.Context, arg AdvanceWebhookDestinationCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceWebhookDestinationCursor,
		arg.SampledAt,
		arg.OwnerScope,
		arg.DestinationID,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyWebhookDestinationState = `-- name: ApplyWebhookDestinationState :execrows
UPDATE webhook_destinations
SET disposition = $1, control_revision = control_revision + 1,
    updated_at = $2
WHERE owner_scope = $3 AND destination_id = $4
  AND generation = $5 AND control_revision = $6
  AND disposition <> 'retired'
`

type ApplyWebhookDestinationStateParams struct {
	Disposition      string
	UpdatedAt        pgtype.Timestamptz
	OwnerScope       string
	DestinationID    string
	Generation       int64
	ExpectedRevision int64
}

func (q *Queries) ApplyWebhookDestinationState(ctx context.Context, arg ApplyWebhookDestinationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyWebhookDestinationState,
		arg.Disposition,
		arg.UpdatedAt,
		arg.OwnerScope,
		arg.DestinationID,
		arg.Generation,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyWebhookKeyRotation = `-- name: ApplyWebhookKeyRotation :execrows
UPDATE webhook_destinations
SET required_secret_revision = $1,
    key_state_revision = $2, active_key_reference = $3,
    predecessor_key_reference = $4,
    predecessor_valid_until = $5,
    control_revision = control_revision + 1, updated_at = $6
WHERE owner_scope = $7 AND destination_id = $8
  AND generation = $9 AND control_revision = $10
  AND required_secret_revision < $1
  AND key_state_revision < $2 AND disposition <> 'retired'
`

type ApplyWebhookKeyRotationParams struct {
	RequiredSecretRevision  int64
	KeyStateRevision        int64
	ActiveKeyReference      string
	PredecessorKeyReference *string
	PredecessorValidUntil   pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	OwnerScope              string
	DestinationID           string
	Generation              int64
	ExpectedRevision        int64
}

func (q *Queries) ApplyWebhookKeyRotation(ctx context.Context, arg ApplyWebhookKeyRotationParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyWebhookKeyRotation,
		arg.RequiredSecretRevision,
		arg.KeyStateRevision,
		arg.ActiveKeyReference,
		arg.PredecessorKeyReference,
		arg.PredecessorValidUntil,
		arg.UpdatedAt,
		arg.OwnerScope,
		arg.DestinationID,
		arg.Generation,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const authorizeWebhookAttempt = `-- name: AuthorizeWebhookAttempt :execrows
UPDATE webhook_attempts a
SET key_reference = $1, signature_header_digest = $2,
    dns_set_digest = $3, selected_address = $4,
    send_authorized = true, may_have_sent = true
FROM webhook_deliveries d, webhook_destinations g, webhook_capacity_slots s
WHERE a.owner_scope = $5 AND a.delivery_id = $6
  AND a.cycle_number = $7 AND a.attempt_id = $8
  AND a.fence = $9 AND a.finalized_at IS NULL
  AND d.owner_scope = a.owner_scope AND d.delivery_id = a.delivery_id
  AND d.state = 'in_flight' AND d.fence = a.fence AND d.sendable
  AND g.owner_scope = d.owner_scope AND g.destination_id = d.destination_id
  AND g.generation = d.destination_generation AND g.disposition = 'active'
  AND g.control_revision = $10
  AND g.key_state_revision = $11
  AND g.required_secret_revision <= $12
  AND s.slot_number = a.capacity_slot AND s.owner_scope = a.owner_scope
  AND s.delivery_id = a.delivery_id AND s.attempt_id = a.attempt_id AND s.fence = a.fence
`

type AuthorizeWebhookAttemptParams struct {
	KeyReference          *string
	SignatureHeaderDigest []byte
	DnsSetDigest          []byte
	SelectedAddress       []byte
	OwnerScope            string
	DeliveryID            string
	CycleNumber           int64
	AttemptID             string
	Fence                 int64
	ControlRevision       int64
	KeyStateRevision      int64
	ManifestRevision      int64
}

func (q *Queries) AuthorizeWebhookAttempt(ctx context.Context, arg AuthorizeWebhookAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, authorizeWebhookAttempt,
		arg.KeyReference,
		arg.SignatureHeaderDigest,
		arg.DnsSetDigest,
		arg.SelectedAddress,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.AttemptID,
		arg.Fence,
		arg.ControlRevision,
		arg.KeyStateRevision,
		arg.ManifestRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkPostgresWebhookWriter = `-- name: CheckPostgresWebhookWriter :one
SELECT COALESCE(bool_and(has_table_privilege(current_user, relation_name, 'SELECT,INSERT,UPDATE,DELETE')), false)
       AND has_sequence_privilege(current_user, 'webhook_fairness_sequence', 'USAGE') AS writable
FROM unnest(ARRAY[
    'webhook_clock', 'webhook_destinations', 'webhook_events', 'webhook_fanouts',
    'webhook_deliveries', 'webhook_cycles', 'webhook_attempts', 'webhook_capacity_slots',
    'webhook_operator_actions', 'webhook_tombstones'
]::text[]) AS relation_name
`

func (q *Queries) CheckPostgresWebhookWriter(ctx context.Context) (*bool, error) {
	row := q.db.QueryRow(ctx, checkPostgresWebhookWriter)
	var writable *bool
	err := row.Scan(&writable)
	return writable, err
}

const claimWebhookDelivery = `-- name: ClaimWebhookDelivery :execrows
UPDATE webhook_deliveries
SET state = 'in_flight', lease_owner = $1, lease_expires_at = $2,
    fence = fence + 1, updated_at = $3
WHERE owner_scope = $4 AND delivery_id = $5
  AND state IN ('ready', 'scheduled') AND fence = $6
`

type ClaimWebhookDeliveryParams struct {
	WorkerID       *string
	LeaseExpiresAt pgtype.Timestamptz
	SampledAt      pgtype.Timestamptz
	OwnerScope     string
	DeliveryID     string
	PreviousFence  int64
}

func (q *Queries) ClaimWebhookDelivery(ctx context.Context, arg ClaimWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimWebhookDelivery,
		arg.WorkerID,
		arg.LeaseExpiresAt,
		arg.SampledAt,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.PreviousFence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupRetainedWebhookEvents = `-- name: CleanupRetainedWebhookEvents :one
WITH candidates AS (
    SELECT e.owner_scope, e.business_event_id
    FROM webhook_events e
    WHERE NOT EXISTS (
        SELECT 1 FROM webhook_deliveries d
        WHERE d.owner_scope = e.owner_scope AND d.business_event_id = e.business_event_id
          AND (d.state <> 'terminal' OR d.redrive_eligible_until > $1)
    )
    ORDER BY e.owner_scope, e.business_event_id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
), deleted AS (
    DELETE FROM webhook_events e USING candidates c
    WHERE e.owner_scope = c.owner_scope AND e.business_event_id = c.business_event_id
    RETURNING 1
)
SELECT count(*) FROM deleted
`

type CleanupRetainedWebhookEventsParams struct {
	SampledAt pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) CleanupRetainedWebhookEvents(ctx context.Context, arg CleanupRetainedWebhookEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, cleanupRetainedWebhookEvents, arg.SampledAt, arg.BatchSize)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearWebhookCapacity = `-- name: ClearWebhookCapacity :exec
DELETE FROM webhook_capacity_slots
`

func (q *Queries) ClearWebhookCapacity(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearWebhookCapacity)
	return err
}

const closeWebhookUnknownCycle = `-- name: CloseWebhookUnknownCycle :execrows
UPDATE webhook_cycles
SET disposition = 'closed_unknown', finalized_at = $1
WHERE owner_scope = $2 AND delivery_id = $3
  AND cycle_number = $4 AND disposition = 'outcome_unknown'
`

type CloseWebhookUnknownCycleParams struct {
	FinalizedAt pgtype.Timestamptz
	OwnerScope  string
	DeliveryID  string
	CycleNumber int64
}

func (q *Queries) CloseWebhookUnknownCycle(ctx context.Context, arg CloseWebhookUnknownCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeWebhookUnknownCycle,
		arg.FinalizedAt,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeWebhookUnknownDelivery = `-- name: CloseWebhookUnknownDelivery :execrows
UPDATE webhook_deliveries d
SET state = 'terminal', cumulative_summary = 'closed_unknown', sendable = false,
    terminal_at = $1, updated_at = $1
WHERE d.owner_scope = $2 AND d.delivery_id = $3
  AND d.current_cycle = $4 AND d.cumulative_summary = 'outcome_unknown'
`

type CloseWebhookUnknownDeliveryParams struct {
	FinalizedAt pgtype.Timestamptz
	OwnerScope  string
	DeliveryID  string
	CycleNumber int64
}

func (q *Queries) CloseWebhookUnknownDelivery(ctx context.Context, arg CloseWebhookUnknownDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeWebhookUnknownDelivery,
		arg.FinalizedAt,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeWebhookNamespaceTombstone = `-- name: CompleteWebhookNamespaceTombstone :execrows
UPDATE webhook_tombstones
SET first_disposition = 'completed'
WHERE owner_scope = $1 AND target_kind = 'namespace'
  AND target_id = $1 AND action_id = $2
  AND first_disposition = 'pending'
`

type CompleteWebhookNamespaceTombstoneParams struct {
	OwnerScope string
	ActionID   string
}

func (q *Queries) CompleteWebhookNamespaceTombstone(ctx context.Context, arg CompleteWebhookNamespaceTombstoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWebhookNamespaceTombstone, arg.OwnerScope, arg.ActionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countWebhookDestinationAttempts = `-- name: CountWebhookDestinationAttempts :one
SELECT count(*)::integer
FROM webhook_attempts a
JOIN webhook_deliveries d
  ON d.owner_scope = a.owner_scope AND d.delivery_id = a.delivery_id
WHERE d.owner_scope = $1
  AND d.destination_id = $2
  AND d.destination_generation = $3
  AND a.finalized_at IS NULL
  AND a.lease_expires_at > $4
`

type CountWebhookDestinationAttemptsParams struct {
	OwnerScope    string
	DestinationID string
	Generation    int64
	SampledAt     pgtype.Timestamptz
}

func (q *Queries) CountWebhookDestinationAttempts(ctx context.Context, arg CountWebhookDestinationAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countWebhookDestinationAttempts,
		arg.OwnerScope,
		arg.DestinationID,
		arg.Generation,
		arg.SampledAt,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countWebhookNamespaceRows = `-- name: CountWebhookNamespaceRows :one
SELECT (
  (SELECT count(*) FROM webhook_events events WHERE events.owner_scope = $1) +
  (SELECT count(*) FROM webhook_destinations destinations WHERE destinations.owner_scope = $1) +
  (SELECT count(*) FROM webhook_operator_actions actions WHERE actions.owner_scope = $1)
)::bigint
`

func (q *Queries) CountWebhookNamespaceRows(ctx context.Context, ownerScope string) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookNamespaceRows, ownerScope)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWebhookEvent = `-- name: DeleteWebhookEvent :execrows
DELETE FROM webhook_events
WHERE owner_scope = $1 AND business_event_id = $2
`

type DeleteWebhookEventParams struct {
	OwnerScope      string
	BusinessEventID string
}

func (q *Queries) DeleteWebhookEvent(ctx context.Context, arg DeleteWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEvent, arg.OwnerScope, arg.BusinessEventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhookNamespaceActions = `-- name: DeleteWebhookNamespaceActions :exec
DELETE FROM webhook_operator_actions WHERE owner_scope = $1
`

func (q *Queries) DeleteWebhookNamespaceActions(ctx context.Context, ownerScope string) error {
	_, err := q.db.Exec(ctx, deleteWebhookNamespaceActions, ownerScope)
	return err
}

const deleteWebhookNamespaceBatch = `-- name: DeleteWebhookNamespaceBatch :one
WITH deleted AS (
    DELETE FROM webhook_events e
    WHERE e.ctid IN (
        SELECT candidate.ctid FROM webhook_events candidate WHERE candidate.owner_scope = $1
        ORDER BY candidate.business_event_id LIMIT $2
    )
    RETURNING 1
)
SELECT count(*) FROM deleted
`

type DeleteWebhookNamespaceBatchParams struct {
	OwnerScope string
	BatchSize  int32
}

func (q *Queries) DeleteWebhookNamespaceBatch(ctx context.Context, arg DeleteWebhookNamespaceBatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteWebhookNamespaceBatch, arg.OwnerScope, arg.BatchSize)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWebhookNamespaceDestinations = `-- name: DeleteWebhookNamespaceDestinations :exec
DELETE FROM webhook_destinations d WHERE d.owner_scope = $1
  AND NOT EXISTS (SELECT 1 FROM webhook_deliveries w WHERE w.owner_scope = d.owner_scope AND w.destination_id = d.destination_id AND w.destination_generation = d.generation)
`

func (q *Queries) DeleteWebhookNamespaceDestinations(ctx context.Context, ownerScope string) error {
	_, err := q.db.Exec(ctx, deleteWebhookNamespaceDestinations, ownerScope)
	return err
}

const finalizeWebhookAttempt = `-- name: FinalizeWebhookAttempt :one
WITH finalized AS (
    UPDATE webhook_attempts a
    SET response_header_bytes = $1,
        response_body_bytes = $2,
        response_status = $3, retry_after = $4,
        outcome_class = $5, finalized_at = $6
    WHERE a.owner_scope = $7 AND a.delivery_id = $8
      AND a.cycle_number = $9 AND a.attempt_id = $10
      AND a.fence = $11 AND a.finalized_at IS NULL
    RETURNING a.capacity_slot
), released AS (
    UPDATE webhook_capacity_slots s
    SET owner_scope = NULL, delivery_id = NULL, cycle_number = NULL, attempt_id = NULL,
        lease_expires_at = NULL, fence = NULL
    FROM finalized f WHERE s.slot_number = f.capacity_slot
), delivery AS (
    UPDATE webhook_deliveries d
    SET state = $12, next_due_at = $13,
        lease_owner = NULL, lease_expires_at = NULL, cumulative_summary = $14,
        terminal_at = $15, updated_at = $6
    FROM finalized
    WHERE d.owner_scope = $7 AND d.delivery_id = $8
      AND d.fence = $11
    RETURNING d.delivery_id
), cycle AS (
    UPDATE webhook_cycles c
    SET disposition = $16, finalized_at = $15
    FROM finalized
    WHERE c.owner_scope = $7 AND c.delivery_id = $8
      AND c.cycle_number = $9 AND c.disposition = 'active'
      AND $16 <> 'active'
)
SELECT count(*) FROM delivery
`

type FinalizeWebhookAttemptParams struct {
	ResponseHeaderBytes *int32
	ResponseBodyBytes   *int32
	ResponseStatus      *int32
	RetryAfter          *string
	OutcomeClass        *string
	FinalizedAt         pgtype.Timestamptz
	OwnerScope          string
	DeliveryID          string
	CycleNumber         int64
	AttemptID           string
	Fence               int64
	DeliveryState       string
	NextDueAt           pgtype.Timestamptz
	CumulativeSummary   string
	TerminalAt          pgtype.Timestamptz
	CycleDisposition    string
}

func (q *Queries) FinalizeWebhookAttempt(ctx context.Context, arg FinalizeWebhookAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, finalizeWebhookAttempt,
		arg.ResponseHeaderBytes,
		arg.ResponseBodyBytes,
		arg.ResponseStatus,
		arg.RetryAfter,
		arg.OutcomeClass,
		arg.FinalizedAt,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.AttemptID,
		arg.Fence,
		arg.DeliveryState,
		arg.NextDueAt,
		arg.CumulativeSummary,
		arg.TerminalAt,
		arg.CycleDisposition,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementWebhookCycleAttempts = `-- name: IncrementWebhookCycleAttempts :execrows
UPDATE webhook_cycles
SET attempts_used = attempts_used + 1
WHERE owner_scope = $1 AND delivery_id = $2
  AND cycle_number = $3 AND disposition = 'active'
  AND attempts_used < maximum_attempts
`

type IncrementWebhookCycleAttemptsParams struct {
	OwnerScope  string
	DeliveryID  string
	CycleNumber int64
}

func (q *Queries) IncrementWebhookCycleAttempts(ctx context.Context, arg IncrementWebhookCycleAttemptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementWebhookCycleAttempts, arg.OwnerScope, arg.DeliveryID, arg.CycleNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookAttempt = `-- name: InsertWebhookAttempt :exec
INSERT INTO webhook_attempts (
    owner_scope, delivery_id, cycle_number, attempt_id, fence, capacity_slot,
    attempted_at, lease_expires_at, payload_digest, payload_bytes
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10
)
`

type InsertWebhookAttemptParams struct {
	OwnerScope     string
	DeliveryID     string
	CycleNumber    int64
	AttemptID      string
	Fence          int64
	CapacitySlot   int32
	AttemptedAt    pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	PayloadDigest  []byte
	PayloadBytes   int32
}

func (q *Queries) InsertWebhookAttempt(ctx context.Context, arg InsertWebhookAttemptParams) error {
	_, err := q.db.Exec(ctx, insertWebhookAttempt,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.AttemptID,
		arg.Fence,
		arg.CapacitySlot,
		arg.AttemptedAt,
		arg.LeaseExpiresAt,
		arg.PayloadDigest,
		arg.PayloadBytes,
	)
	return err
}

const insertWebhookCapacity = `-- name: InsertWebhookCapacity :exec
INSERT INTO webhook_capacity_slots (slot_number, capacity_revision)
SELECT generate_series(1, $1::integer), $2::bigint
`

type InsertWebhookCapacityParams struct {
	SlotCount        int32
	CapacityRevision int64
}

func (q *Queries) InsertWebhookCapacity(ctx context.Context, arg InsertWebhookCapacityParams) error {
	_, err := q.db.Exec(ctx, insertWebhookCapacity, arg.SlotCount, arg.CapacityRevision)
	return err
}

const insertWebhookCycle = `-- name: InsertWebhookCycle :execrows
INSERT INTO webhook_cycles (
    owner_scope, delivery_id, cycle_number, cycle_kind, accepted_at, deadline_at, maximum_attempts
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
ON CONFLICT DO NOTHING
`

type InsertWebhookCycleParams struct {
	OwnerScope      string
	DeliveryID      string
	CycleNumber     int64
	CycleKind       string
	AcceptedAt      pgtype.Timestamptz
	DeadlineAt      pgtype.Timestamptz
	MaximumAttempts int32
}

func (q *Queries) InsertWebhookCycle(ctx context.Context, arg InsertWebhookCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookCycle,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.CycleKind,
		arg.AcceptedAt,
		arg.DeadlineAt,
		arg.MaximumAttempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :execrows
INSERT INTO webhook_deliveries (
    owner_scope, delivery_id, business_event_id, fanout_snapshot_id, destination_id,
    destination_generation, url_snapshot, policy_snapshot, next_due_at,
    redrive_eligible_until, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $11
)
ON CONFLICT DO NOTHING
`

type InsertWebhookDeliveryParams struct {
	OwnerScope            string
	DeliveryID            string
	BusinessEventID       string
	FanoutSnapshotID      string
	DestinationID         string
	DestinationGeneration int64
	UrlSnapshot           string
	PolicySnapshot        []byte
	NextDueAt             pgtype.Timestamptz
	RedriveEligibleUntil  pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.BusinessEventID,
		arg.FanoutSnapshotID,
		arg.DestinationID,
		arg.DestinationGeneration,
		arg.UrlSnapshot,
		arg.PolicySnapshot,
		arg.NextDueAt,
		arg.RedriveEligibleUntil,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookDestination = `-- name: InsertWebhookDestination :execrows
INSERT INTO webhook_destinations (
    owner_scope, destination_id, generation, ownership_verification_receipt, url,
    selection_revision, payload_version_preference, signature_profile,
    signing_authority_binding, policy, policy_fingerprint, destination_concurrency,
    global_concurrency, required_secret_revision, active_key_reference, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, $11,
    $12, $13,
    $14, $15,
    $16, $16
)
ON CONFLICT (owner_scope, destination_id, generation) DO NOTHING
`

type InsertWebhookDestinationParams struct {
	OwnerScope                   string
	DestinationID                string
	Generation                   int64
	OwnershipVerificationReceipt string
	Url                          string
	SelectionRevision            string
	PayloadVersionPreference     string
	SignatureProfile             string
	SigningAuthorityBinding      string
	Policy                       []byte
	PolicyFingerprint            []byte
	DestinationConcurrency       int32
	GlobalConcurrency            int32
	RequiredSecretRevision       int64
	ActiveKeyReference           string
	CreatedAt                    pgtype.Timestamptz
}

func (q *Queries) InsertWebhookDestination(ctx context.Context, arg InsertWebhookDestinationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookDestination,
		arg.OwnerScope,
		arg.DestinationID,
		arg.Generation,
		arg.OwnershipVerificationReceipt,
		arg.Url,
		arg.SelectionRevision,
		arg.PayloadVersionPreference,
		arg.SignatureProfile,
		arg.SigningAuthorityBinding,
		arg.Policy,
		arg.PolicyFingerprint,
		arg.DestinationConcurrency,
		arg.GlobalConcurrency,
		arg.RequiredSecretRevision,
		arg.ActiveKeyReference,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :execrows
INSERT INTO webhook_events (
    owner_scope, business_event_id, acceptance_id, fanout_snapshot_id, event_type,
    business_schema_version, content_type, body, delivery_envelope_version,
    subscriber_policy_revision, intent_fingerprint, retention_policy_identity, accepted_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13
)
ON CONFLICT DO NOTHING
`

type InsertWebhookEventParams struct {
	OwnerScope               string
	BusinessEventID          string
	AcceptanceID             string
	FanoutSnapshotID         string
	EventType                string
	BusinessSchemaVersion    string
	ContentType              string
	Body                     []byte
	DeliveryEnvelopeVersion  string
	SubscriberPolicyRevision string
	IntentFingerprint        []byte
	RetentionPolicyIdentity  string
	AcceptedAt               pgtype.Timestamptz
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookEvent,
		arg.OwnerScope,
		arg.BusinessEventID,
		arg.AcceptanceID,
		arg.FanoutSnapshotID,
		arg.EventType,
		arg.BusinessSchemaVersion,
		arg.ContentType,
		arg.Body,
		arg.DeliveryEnvelopeVersion,
		arg.SubscriberPolicyRevision,
		arg.IntentFingerprint,
		arg.RetentionPolicyIdentity,
		arg.AcceptedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookFanout = `-- name: InsertWebhookFanout :execrows
INSERT INTO webhook_fanouts (
    owner_scope, fanout_snapshot_id, business_event_id, member_count, member_fingerprint, accepted_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT DO NOTHING
`

type InsertWebhookFanoutParams struct {
	OwnerScope        string
	FanoutSnapshotID  string
	BusinessEventID   string
	MemberCount       int32
	MemberFingerprint []byte
	AcceptedAt        pgtype.Timestamptz
}

func (q *Queries) InsertWebhookFanout(ctx context.Context, arg InsertWebhookFanoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookFanout,
		arg.OwnerScope,
		arg.FanoutSnapshotID,
		arg.BusinessEventID,
		arg.MemberCount,
		arg.MemberFingerprint,
		arg.AcceptedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookOperatorAction = `-- name: InsertWebhookOperatorAction :execrows
INSERT INTO webhook_operator_actions (
    owner_scope, action_id, encoding_version, request_fingerprint, actor_reference,
    action_kind, target_kind, target_id, target_generation, expected_state, reason,
    duplicate_risk_acknowledged, result, created_at, completed_at
) VALUES (
    $1, $2, 'webhook-operator-action-v1',
    $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13, $13
)
ON CONFLICT DO NOTHING
`

type InsertWebhookOperatorActionParams struct {
	OwnerScope                string
	ActionID                  string
	RequestFingerprint        []byte
	ActorReference            string
	ActionKind                string
	TargetKind                string
	TargetID                  string
	TargetGeneration          int64
	ExpectedState             string
	Reason                    string
	DuplicateRiskAcknowledged bool
	Result                    string
	CreatedAt                 pgtype.Timestamptz
}

func (q *Queries) InsertWebhookOperatorAction(ctx context.Context, arg InsertWebhookOperatorActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookOperatorAction,
		arg.OwnerScope,
		arg.ActionID,
		arg.RequestFingerprint,
		arg.ActorReference,
		arg.ActionKind,
		arg.TargetKind,
		arg.TargetID,
		arg.TargetGeneration,
		arg.ExpectedState,
		arg.Reason,
		arg.DuplicateRiskAcknowledged,
		arg.Result,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookRedriveCycle = `-- name: InsertWebhookRedriveCycle :execrows
INSERT INTO webhook_cycles (
    owner_scope, delivery_id, cycle_number, cycle_kind, authorizing_action_id,
    accepted_at, deadline_at, maximum_attempts
) VALUES (
    $1, $2, $3, 'redrive',
    $4, $5, $6, $7
)
ON CONFLICT DO NOTHING
`

type InsertWebhookRedriveCycleParams struct {
	OwnerScope      string
	DeliveryID      string
	CycleNumber     int64
	ActionID        *string
	AcceptedAt      pgtype.Timestamptz
	DeadlineAt      pgtype.Timestamptz
	MaximumAttempts int32
}

func (q *Queries) InsertWebhookRedriveCycle(ctx context.Context, arg InsertWebhookRedriveCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookRedriveCycle,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.ActionID,
		arg.AcceptedAt,
		arg.DeadlineAt,
		arg.MaximumAttempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookTombstone = `-- name: InsertWebhookTombstone :execrows
INSERT INTO webhook_tombstones (
    owner_scope, target_kind, target_id, acceptance_id, fanout_snapshot_id,
    delivery_identities, destination_identities, last_semantic_class, action_id,
    action_encoding_version, request_fingerprint, first_disposition,
    deletion_authority, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, 'webhook-operator-action-v1',
    $10, $11, $12,
    $13
)
ON CONFLICT DO NOTHING
`

type InsertWebhookTombstoneParams struct {
	OwnerScope            string
	TargetKind            string
	TargetID              string
	AcceptanceID          *string
	FanoutSnapshotID      *string
	DeliveryIdentities    []byte
	DestinationIdentities []byte
	LastSemanticClass     string
	ActionID              string
	RequestFingerprint    []byte
	FirstDisposition      string
	DeletionAuthority     string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertWebhookTombstone(ctx context.Context, arg InsertWebhookTombstoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookTombstone,
		arg.OwnerScope,
		arg.TargetKind,
		arg.TargetID,
		arg.AcceptanceID,
		arg.FanoutSnapshotID,
		arg.DeliveryIdentities,
		arg.DestinationIdentities,
		arg.LastSemanticClass,
		arg.ActionID,
		arg.RequestFingerprint,
		arg.FirstDisposition,
		arg.DeletionAuthority,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leaseWebhookCapacitySlot = `-- name: LeaseWebhookCapacitySlot :execrows
UPDATE webhook_capacity_slots
SET owner_scope = $1, delivery_id = $2,
    cycle_number = $3, attempt_id = $4,
    lease_expires_at = $5, fence = $6
WHERE slot_number = $7 AND capacity_revision = $8
`

type LeaseWebhookCapacitySlotParams struct {
	OwnerScope       *string
	DeliveryID       *string
	CycleNumber      *int64
	AttemptID        *string
	LeaseExpiresAt   pgtype.Timestamptz
	Fence            *int64
	SlotNumber       int32
	CapacityRevision int64
}

func (q *Queries) LeaseWebhookCapacitySlot(ctx context.Context, arg LeaseWebhookCapacitySlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaseWebhookCapacitySlot,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.AttemptID,
		arg.LeaseExpiresAt,
		arg.Fence,
		arg.SlotNumber,
		arg.CapacityRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpiredWebhookAttempts = `-- name: ListExpiredWebhookAttempts :many
SELECT owner_scope, delivery_id, cycle_number, attempt_id, fence, capacity_slot,
       send_authorized, may_have_sent, attempted_at, lease_expires_at
FROM webhook_attempts
WHERE finalized_at IS NULL AND lease_expires_at <= $1
ORDER BY lease_expires_at, owner_scope, delivery_id, cycle_number, attempt_id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredWebhookAttemptsParams struct {
	SampledAt pgtype.Timestamptz
	BatchSize int32
}

type ListExpiredWebhookAttemptsRow struct {
	OwnerScope     string
	DeliveryID     string
	CycleNumber    int64
	AttemptID      string
	Fence          int64
	CapacitySlot   int32
	SendAuthorized bool
	MayHaveSent    bool
	AttemptedAt    pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListExpiredWebhookAttempts(ctx context.Context, arg ListExpiredWebhookAttemptsParams) ([]ListExpiredWebhookAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredWebhookAttempts, arg.SampledAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredWebhookAttemptsRow
	for rows.Next() {
		var i ListExpiredWebhookAttemptsRow
		if err := rows.Scan(
			&i.OwnerScope,
			&i.DeliveryID,
			&i.CycleNumber,
			&i.AttemptID,
			&i.Fence,
			&i.CapacitySlot,
			&i.SendAuthorized,
			&i.MayHaveSent,
			&i.AttemptedAt,
			&i.LeaseExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostgresWebhookRelations = `-- name: ListPostgresWebhookRelations :many
SELECT c.relname::text AS relation_name
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = current_schema()
  AND c.relkind = 'r'
  AND c.relname = ANY(ARRAY[
    'webhook_clock', 'webhook_destinations', 'webhook_events', 'webhook_fanouts',
    'webhook_deliveries', 'webhook_cycles', 'webhook_attempts', 'webhook_capacity_slots',
    'webhook_operator_actions', 'webhook_tombstones'
  ]::text[])
ORDER BY c.relname
`

func (q *Queries) ListPostgresWebhookRelations(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPostgresWebhookRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var relation_name string
		if err := rows.Scan(&relation_name); err != nil {
			return nil, err
		}
		items = append(items, relation_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookAcceptanceDeliveries = `-- name: ListWebhookAcceptanceDeliveries :many
SELECT d.delivery_id, d.destination_id, d.destination_generation, d.current_cycle,
       c.accepted_at, c.deadline_at, c.maximum_attempts
FROM webhook_deliveries d
JOIN webhook_cycles c
  ON c.owner_scope = d.owner_scope AND c.delivery_id = d.delivery_id AND c.cycle_number = 0
WHERE d.owner_scope = $1
  AND d.fanout_snapshot_id = $2
ORDER BY d.destination_id, d.destination_generation
`

type ListWebhookAcceptanceDeliveriesParams struct {
	OwnerScope       string
	FanoutSnapshotID string
}

type ListWebhookAcceptanceDeliveriesRow struct {
	DeliveryID            string
	DestinationID         string
	DestinationGeneration int64
	CurrentCycle          int64
	AcceptedAt            pgtype.Timestamptz
	DeadlineAt            pgtype.Timestamptz
	MaximumAttempts       int32
}

func (q *Queries) ListWebhookAcceptanceDeliveries(ctx context.Context, arg ListWebhookAcceptanceDeliveriesParams) ([]ListWebhookAcceptanceDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookAcceptanceDeliveries, arg.OwnerScope, arg.FanoutSnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookAcceptanceDeliveriesRow
	for rows.Next() {
		var i ListWebhookAcceptanceDeliveriesRow
		if err := rows.Scan(
			&i.DeliveryID,
			&i.DestinationID,
			&i.DestinationGeneration,
			&i.CurrentCycle,
			&i.AcceptedAt,
			&i.DeadlineAt,
			&i.MaximumAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookClaimDestinations = `-- name: ListWebhookClaimDestinations :many
SELECT d.owner_scope, d.destination_id, d.generation, d.ownership_verification_receipt, d.url, d.selection_revision, d.payload_version_preference, d.signature_profile, d.signing_authority_binding, d.policy, d.policy_fingerprint, d.destination_concurrency, d.global_concurrency, d.control_revision, d.required_secret_revision, d.key_state_revision, d.active_key_reference, d.predecessor_key_reference, d.predecessor_valid_until, d.disposition, d.last_considered_sequence, d.created_at, d.updated_at
FROM webhook_destinations d
WHERE d.disposition = 'active'
  AND d.required_secret_revision <= $1
  AND EXISTS (
      SELECT 1 FROM webhook_deliveries w
      WHERE w.owner_scope = d.owner_scope
        AND w.destination_id = d.destination_id
        AND w.destination_generation = d.generation
        AND w.state IN ('ready', 'scheduled')
        AND w.sendable
        AND w.next_due_at <= $2
  )
ORDER BY d.last_considered_sequence, d.owner_scope, d.destination_id, d.generation
LIMIT $3
FOR UPDATE SKIP LOCKED
`

type ListWebhookClaimDestinationsParams struct {
	ManifestRevision int64
	SampledAt        pgtype.Timestamptz
	PageSize         int32
}

func (q *Queries) ListWebhookClaimDestinations(ctx context.Context, arg ListWebhookClaimDestinationsParams) ([]WebhookDestination, error) {
	rows, err := q.db.Query(ctx, listWebhookClaimDestinations, arg.ManifestRevision, arg.SampledAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDestination
	for rows.Next() {
		var i WebhookDestination
		if err := rows.Scan(
			&i.OwnerScope,
			&i.DestinationID,
			&i.Generation,
			&i.OwnershipVerificationReceipt,
			&i.Url,
			&i.SelectionRevision,
			&i.PayloadVersionPreference,
			&i.SignatureProfile,
			&i.SigningAuthorityBinding,
			&i.Policy,
			&i.PolicyFingerprint,
			&i.DestinationConcurrency,
			&i.GlobalConcurrency,
			&i.ControlRevision,
			&i.RequiredSecretRevision,
			&i.KeyStateRevision,
			&i.ActiveKeyReference,
			&i.PredecessorKeyReference,
			&i.PredecessorValidUntil,
			&i.Disposition,
			&i.LastConsideredSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSecretBindings = `-- name: ListWebhookSecretBindings :many
SELECT owner_scope, destination_id, required_secret_revision, active_key_reference,
       predecessor_key_reference, predecessor_valid_until
FROM webhook_destinations
WHERE disposition IN ('active', 'automatically_paused')
ORDER BY owner_scope, destination_id, generation
`

type ListWebhookSecretBindingsRow struct {
	OwnerScope              string
	DestinationID           string
	RequiredSecretRevision  int64
	ActiveKeyReference      string
	PredecessorKeyReference *string
	PredecessorValidUntil   pgtype.Timestamptz
}

func (q *Queries) ListWebhookSecretBindings(ctx context.Context) ([]ListWebhookSecretBindingsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookSecretBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookSecretBindingsRow
	for rows.Next() {
		var i ListWebhookSecretBindingsRow
		if err := rows.Scan(
			&i.OwnerScope,
			&i.DestinationID,
			&i.RequiredSecretRevision,
			&i.ActiveKeyReference,
			&i.PredecessorKeyReference,
			&i.PredecessorValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWebhookAdvisoryKey = `-- name: LockWebhookAdvisoryKey :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) LockWebhookAdvisoryKey(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, lockWebhookAdvisoryKey, lockKey)
	return err
}

const lockWebhookCapacitySlot = `-- name: LockWebhookCapacitySlot :one
SELECT slot_number
FROM webhook_capacity_slots
WHERE capacity_revision = $1
  AND (attempt_id IS NULL OR lease_expires_at <= $2)
ORDER BY slot_number
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type LockWebhookCapacitySlotParams struct {
	CapacityRevision int64
	SampledAt        pgtype.Timestamptz
}

func (q *Queries) LockWebhookCapacitySlot(ctx context.Context, arg LockWebhookCapacitySlotParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockWebhookCapacitySlot, arg.CapacityRevision, arg.SampledAt)
	var slot_number int32
	err := row.Scan(&slot_number)
	return slot_number, err
}

const lockWebhookCapacityTable = `-- name: LockWebhookCapacityTable :exec
LOCK TABLE webhook_capacity_slots IN ACCESS EXCLUSIVE MODE
`

func (q *Queries) LockWebhookCapacityTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockWebhookCapacityTable)
	return err
}

const lockWebhookDeliveryForAction = `-- name: LockWebhookDeliveryForAction :one
SELECT d.current_cycle, d.state, d.cumulative_summary, d.redrive_eligible_until,
       d.destination_id, d.destination_generation, d.sendable, c.disposition, c.deadline_at
FROM webhook_deliveries d
JOIN webhook_cycles c
  ON c.owner_scope = d.owner_scope AND c.delivery_id = d.delivery_id AND c.cycle_number = d.current_cycle
WHERE d.owner_scope = $1 AND d.delivery_id = $2
FOR UPDATE OF d, c
`

type LockWebhookDeliveryForActionParams struct {
	OwnerScope string
	DeliveryID string
}

type LockWebhookDeliveryForActionRow struct {
	CurrentCycle          int64
	State                 string
	CumulativeSummary     string
	RedriveEligibleUntil  pgtype.Timestamptz
	DestinationID         string
	DestinationGeneration int64
	Sendable              bool
	Disposition           string
	DeadlineAt            pgtype.Timestamptz
}

func (q *Queries) LockWebhookDeliveryForAction(ctx context.Context, arg LockWebhookDeliveryForActionParams) (LockWebhookDeliveryForActionRow, error) {
	row := q.db.QueryRow(ctx, lockWebhookDeliveryForAction, arg.OwnerScope, arg.DeliveryID)
	var i LockWebhookDeliveryForActionRow
	err := row.Scan(
		&i.CurrentCycle,
		&i.State,
		&i.CumulativeSummary,
		&i.RedriveEligibleUntil,
		&i.DestinationID,
		&i.DestinationGeneration,
		&i.Sendable,
		&i.Disposition,
		&i.DeadlineAt,
	)
	return i, err
}

const lockWebhookDueDelivery = `-- name: LockWebhookDueDelivery :one
SELECT d.owner_scope, d.delivery_id, d.business_event_id, d.fanout_snapshot_id, d.destination_id, d.destination_generation, d.url_snapshot, d.policy_snapshot, d.state, d.current_cycle, d.next_due_at, d.lease_owner, d.lease_expires_at, d.fence, d.cumulative_summary, d.sendable, d.redrive_eligible_until, d.terminal_at, d.created_at, d.updated_at, e.body, e.content_type
FROM webhook_deliveries d
JOIN webhook_events e
  ON e.owner_scope = d.owner_scope AND e.business_event_id = d.business_event_id
JOIN webhook_cycles c
  ON c.owner_scope = d.owner_scope AND c.delivery_id = d.delivery_id AND c.cycle_number = d.current_cycle
WHERE d.owner_scope = $1
  AND d.destination_id = $2
  AND d.destination_generation = $3
  AND d.state IN ('ready', 'scheduled') AND d.sendable
  AND d.next_due_at <= $4
  AND c.disposition = 'active' AND c.deadline_at > $4
ORDER BY d.next_due_at, d.delivery_id
LIMIT 1
FOR UPDATE OF d SKIP LOCKED
`

type LockWebhookDueDeliveryParams struct {
	OwnerScope    string
	DestinationID string
	Generation    int64
	SampledAt     pgtype.Timestamptz
}

type LockWebhookDueDeliveryRow struct {
	OwnerScope            string
	DeliveryID            string
	BusinessEventID       string
	FanoutSnapshotID      string
	DestinationID         string
	DestinationGeneration int64
	UrlSnapshot           string
	PolicySnapshot        []byte
	State                 string
	CurrentCycle          int64
	NextDueAt             pgtype.Timestamptz
	LeaseOwner            *string
	LeaseExpiresAt        pgtype.Timestamptz
	Fence                 int64
	CumulativeSummary     string
	Sendable              bool
	RedriveEligibleUntil  pgtype.Timestamptz
	TerminalAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Body                  []byte
	ContentType           string
}

func (q *Queries) LockWebhookDueDelivery(ctx context.Context, arg LockWebhookDueDeliveryParams) (LockWebhookDueDeliveryRow, error) {
	row := q.db.QueryRow(ctx, lockWebhookDueDelivery,
		arg.OwnerScope,
		arg.DestinationID,
		arg.Generation,
		arg.SampledAt,
	)
	var i LockWebhookDueDeliveryRow
	err := row.Scan(
		&i.OwnerScope,
		&i.DeliveryID,
		&i.BusinessEventID,
		&i.FanoutSnapshotID,
		&i.DestinationID,
		&i.DestinationGeneration,
		&i.UrlSnapshot,
		&i.PolicySnapshot,
		&i.State,
		&i.CurrentCycle,
		&i.NextDueAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.Fence,
		&i.CumulativeSummary,
		&i.Sendable,
		&i.RedriveEligibleUntil,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.ContentType,
	)
	return i, err
}

const lockWebhookFinalization = `-- name: LockWebhookFinalization :one
SELECT a.send_authorized, a.may_have_sent, a.capacity_slot,
       d.cumulative_summary, d.state, d.fence,
       c.attempts_used, c.maximum_attempts, c.deadline_at
FROM webhook_attempts a
JOIN webhook_deliveries d
  ON d.owner_scope = a.owner_scope AND d.delivery_id = a.delivery_id
JOIN webhook_cycles c
  ON c.owner_scope = a.owner_scope AND c.delivery_id = a.delivery_id AND c.cycle_number = a.cycle_number
JOIN webhook_capacity_slots s ON s.slot_number = a.capacity_slot
WHERE a.owner_scope = $1 AND a.delivery_id = $2
  AND a.cycle_number = $3 AND a.attempt_id = $4
  AND a.fence = $5 AND a.finalized_at IS NULL
FOR UPDATE OF d, s, c, a
`

type LockWebhookFinalizationParams struct {
	OwnerScope  string
	DeliveryID  string
	CycleNumber int64
	AttemptID   string
	Fence       int64
}

type LockWebhookFinalizationRow struct {
	SendAuthorized    bool
	MayHaveSent       bool
	CapacitySlot      int32
	CumulativeSummary string
	State             string
	Fence             int64
	AttemptsUsed      int32
	MaximumAttempts   int32
	DeadlineAt        pgtype.Timestamptz
}

func (q *Queries) LockWebhookFinalization(ctx context.Context, arg LockWebhookFinalizationParams) (LockWebhookFinalizationRow, error) {
	row := q.db.QueryRow(ctx, lockWebhookFinalization,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.AttemptID,
		arg.Fence,
	)
	var i LockWebhookFinalizationRow
	err := row.Scan(
		&i.SendAuthorized,
		&i.MayHaveSent,
		&i.CapacitySlot,
		&i.CumulativeSummary,
		&i.State,
		&i.Fence,
		&i.AttemptsUsed,
		&i.MaximumAttempts,
		&i.DeadlineAt,
	)
	return i, err
}

const lockWebhookSendBarrier = `-- name: LockWebhookSendBarrier :one
SELECT g.control_revision, g.key_state_revision, g.required_secret_revision,
       g.active_key_reference, g.predecessor_key_reference, g.predecessor_valid_until,
       d.destination_id, d.destination_generation, a.capacity_slot
FROM webhook_attempts a
JOIN webhook_deliveries d
  ON d.owner_scope = a.owner_scope AND d.delivery_id = a.delivery_id
JOIN webhook_destinations g
  ON g.owner_scope = d.owner_scope AND g.destination_id = d.destination_id
 AND g.generation = d.destination_generation
JOIN webhook_capacity_slots s
  ON s.slot_number = a.capacity_slot
WHERE a.owner_scope = $1 AND a.delivery_id = $2
  AND a.cycle_number = $3 AND a.attempt_id = $4
  AND a.fence = $5 AND a.finalized_at IS NULL
FOR UPDATE OF g, d, s, a
`

type LockWebhookSendBarrierParams struct {
	OwnerScope  string
	DeliveryID  string
	CycleNumber int64
	AttemptID   string
	Fence       int64
}

type LockWebhookSendBarrierRow struct {
	ControlRevision         int64
	KeyStateRevision        int64
	RequiredSecretRevision  int64
	ActiveKeyReference      string
	PredecessorKeyReference *string
	PredecessorValidUntil   pgtype.Timestamptz
	DestinationID           string
	DestinationGeneration   int64
	CapacitySlot            int32
}

func (q *Queries) LockWebhookSendBarrier(ctx context.Context, arg LockWebhookSendBarrierParams) (LockWebhookSendBarrierRow, error) {
	row := q.db.QueryRow(ctx, lockWebhookSendBarrier,
		arg.OwnerScope,
		arg.DeliveryID,
		arg.CycleNumber,
		arg.AttemptID,
		arg.Fence,
	)
	var i LockWebhookSendBarrierRow
	err := row.Scan(
		&i.ControlRevision,
		&i.KeyStateRevision,
		&i.RequiredSecretRevision,
		&i.ActiveKeyReference,
		&i.PredecessorKeyReference,
		&i.PredecessorValidUntil,
		&i.DestinationID,
		&i.DestinationGeneration,
		&i.CapacitySlot,
	)
	return i, err
}

const observePostgresWebhooks = `-- name: ObservePostgresWebhooks :one
SELECT
    (SELECT count(*) FROM webhook_deliveries WHERE state IN ('ready', 'scheduled'))::bigint AS scheduled,
    (SELECT count(*) FROM webhook_deliveries WHERE state = 'in_flight')::bigint AS in_flight,
    (SELECT count(*) FROM webhook_deliveries WHERE state = 'terminal')::bigint AS terminal,
    (SELECT count(*) FROM webhook_destinations WHERE disposition = 'administratively_disabled')::bigint AS disabled,
    (SELECT count(*) FROM webhook_capacity_slots WHERE attempt_id IS NOT NULL)::bigint AS leased_slots,
    (SELECT count(*) FROM webhook_capacity_slots)::bigint AS total_slots,
    (SELECT regression FROM webhook_clock WHERE singleton) AS clock_regression
`

type ObservePostgresWebhooksRow struct {
	Scheduled       int64
	InFlight        int64
	Terminal        int64
	Disabled        int64
	LeasedSlots     int64
	TotalSlots      int64
	ClockRegression bool
}

func (q *Queries) ObservePostgresWebhooks(ctx context.Context) (ObservePostgresWebhooksRow, error) {
	row := q.db.QueryRow(ctx, observePostgresWebhooks)
	var i ObservePostgresWebhooksRow
	err := row.Scan(
		&i.Scheduled,
		&i.InFlight,
		&i.Terminal,
		&i.Disabled,
		&i.LeasedSlots,
		&i.TotalSlots,
		&i.ClockRegression,
	)
	return i, err
}

const observeWebhookClock = `-- name: ObserveWebhookClock :one
WITH locked AS (
    SELECT high_water FROM webhook_clock WHERE singleton FOR UPDATE
), sampled AS (
    SELECT clock_timestamp() AS sampled_at, high_water FROM locked
)
UPDATE webhook_clock c
SET high_water = GREATEST(c.high_water, s.sampled_at),
    regression = s.sampled_at < c.high_water,
    observed_at = s.sampled_at
FROM sampled s
WHERE c.singleton
RETURNING c.high_water, c.regression, c.observed_at
`

type ObserveWebhookClockRow struct {
	HighWater  pgtype.Timestamptz
	Regression bool
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) ObserveWebhookClock(ctx context.Context) (ObserveWebhookClockRow, error) {
	row := q.db.QueryRow(ctx, observeWebhookClock)
	var i ObserveWebhookClockRow
	err := row.Scan(&i.HighWater, &i.Regression, &i.ObservedAt)
	return i, err
}

const readWebhookAcceptance = `-- name: ReadWebhookAcceptance :one
SELECT e.business_event_id, e.acceptance_id, e.fanout_snapshot_id, e.intent_fingerprint,
       f.member_count, f.member_fingerprint, e.accepted_at
FROM webhook_events e
JOIN webhook_fanouts f USING (owner_scope, fanout_snapshot_id)
WHERE e.owner_scope = $1
  AND e.acceptance_id = $2
`

type ReadWebhookAcceptanceParams struct {
	OwnerScope   string
	AcceptanceID string
}

type ReadWebhookAcceptanceRow struct {
	BusinessEventID   string
	AcceptanceID      string
	FanoutSnapshotID  string
	IntentFingerprint []byte
	MemberCount       int32
	MemberFingerprint []byte
	AcceptedAt        pgtype.Timestamptz
}

func (q *Queries) ReadWebhookAcceptance(ctx context.Context, arg ReadWebhookAcceptanceParams) (ReadWebhookAcceptanceRow, error) {
	row := q.db.QueryRow(ctx, readWebhookAcceptance, arg.OwnerScope, arg.AcceptanceID)
	var i ReadWebhookAcceptanceRow
	err := row.Scan(
		&i.BusinessEventID,
		&i.AcceptanceID,
		&i.FanoutSnapshotID,
		&i.IntentFingerprint,
		&i.MemberCount,
		&i.MemberFingerprint,
		&i.AcceptedAt,
	)
	return i, err
}

const readWebhookCapacity = `-- name: ReadWebhookCapacity :one
SELECT COALESCE(max(capacity_revision), 0)::bigint AS capacity_revision,
       count(*)::integer AS slot_count,
       count(*) FILTER (WHERE attempt_id IS NOT NULL)::integer AS leased_count,
       count(DISTINCT capacity_revision)::integer AS revision_count
FROM webhook_capacity_slots
`

type ReadWebhookCapacityRow struct {
	CapacityRevision int64
	SlotCount        int32
	LeasedCount      int32
	RevisionCount    int32
}

func (q *Queries) ReadWebhookCapacity(ctx context.Context) (ReadWebhookCapacityRow, error) {
	row := q.db.QueryRow(ctx, readWebhookCapacity)
	var i ReadWebhookCapacityRow
	err := row.Scan(
		&i.CapacityRevision,
		&i.SlotCount,
		&i.LeasedCount,
		&i.RevisionCount,
	)
	return i, err
}

const readWebhookClock = `-- name: ReadWebhookClock :one
SELECT high_water, regression, observed_at FROM webhook_clock WHERE singleton
`

type ReadWebhookClockRow struct {
	HighWater  pgtype.Timestamptz
	Regression bool
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) ReadWebhookClock(ctx context.Context) (ReadWebhookClockRow, error) {
	row := q.db.QueryRow(ctx, readWebhookClock)
	var i ReadWebhookClockRow
	err := row.Scan(&i.HighWater, &i.Regression, &i.ObservedAt)
	return i, err
}

const readWebhookDestination = `-- name: ReadWebhookDestination :one
SELECT owner_scope, destination_id, generation, ownership_verification_receipt, url, selection_revision, payload_version_preference, signature_profile, signing_authority_binding, policy, policy_fingerprint, destination_concurrency, global_concurrency, control_revision, required_secret_revision, key_state_revision, active_key_reference, predecessor_key_reference, predecessor_valid_until, disposition, last_considered_sequence, created_at, updated_at FROM webhook_destinations
WHERE owner_scope = $1
  AND destination_id = $2
  AND generation = $3
`

type ReadWebhookDestinationParams struct {
	OwnerScope    string
	DestinationID string
	Generation    int64
}

func (q *Queries) ReadWebhookDestination(ctx context.Context, arg ReadWebhookDestinationParams) (WebhookDestination, error) {
	row := q.db.QueryRow(ctx, readWebhookDestination, arg.OwnerScope, arg.DestinationID, arg.Generation)
	var i WebhookDestination
	err := row.Scan(
		&i.OwnerScope,
		&i.DestinationID,
		&i.Generation,
		&i.OwnershipVerificationReceipt,
		&i.Url,
		&i.SelectionRevision,
		&i.PayloadVersionPreference,
		&i.SignatureProfile,
		&i.SigningAuthorityBinding,
		&i.Policy,
		&i.PolicyFingerprint,
		&i.DestinationConcurrency,
		&i.GlobalConcurrency,
		&i.ControlRevision,
		&i.RequiredSecretRevision,
		&i.KeyStateRevision,
		&i.ActiveKeyReference,
		&i.PredecessorKeyReference,
		&i.PredecessorValidUntil,
		&i.Disposition,
		&i.LastConsideredSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readWebhookEventForPrivacy = `-- name: ReadWebhookEventForPrivacy :one
WITH e AS (
    SELECT acceptance_id, fanout_snapshot_id
    FROM webhook_events
    WHERE owner_scope = $1 AND business_event_id = $2
    FOR UPDATE
)
SELECT e.acceptance_id, e.fanout_snapshot_id,
       COALESCE(jsonb_agg(DISTINCT jsonb_build_array(d.delivery_id)) FILTER (WHERE d.delivery_id IS NOT NULL), '[]') AS delivery_identities,
       COALESCE(jsonb_agg(DISTINCT jsonb_build_array(d.destination_id, d.destination_generation)) FILTER (WHERE d.destination_id IS NOT NULL), '[]') AS destination_identities,
       COALESCE(max(d.cumulative_summary), 'none')::text AS last_semantic_class
FROM e
LEFT JOIN webhook_deliveries d
  ON d.owner_scope = $1 AND d.business_event_id = $2
GROUP BY e.acceptance_id, e.fanout_snapshot_id
`

type ReadWebhookEventForPrivacyParams struct {
	OwnerScope      string
	BusinessEventID string
}

type ReadWebhookEventForPrivacyRow struct {
	AcceptanceID          string
	FanoutSnapshotID      string
	DeliveryIdentities    interface{}
	DestinationIdentities interface{}
	LastSemanticClass     string
}

func (q *Queries) ReadWebhookEventForPrivacy(ctx context.Context, arg ReadWebhookEventForPrivacyParams) (ReadWebhookEventForPrivacyRow, error) {
	row := q.db.QueryRow(ctx, readWebhookEventForPrivacy, arg.OwnerScope, arg.BusinessEventID)
	var i ReadWebhookEventForPrivacyRow
	err := row.Scan(
		&i.AcceptanceID,
		&i.FanoutSnapshotID,
		&i.DeliveryIdentities,
		&i.DestinationIdentities,
		&i.LastSemanticClass,
	)
	return i, err
}

const readWebhookMaxRequiredSecretRevision = `-- name: ReadWebhookMaxRequiredSecretRevision :one
SELECT COALESCE(max(required_secret_revision), 0)::bigint
FROM webhook_destinations
WHERE disposition IN ('active', 'automatically_paused')
`

func (q *Queries) ReadWebhookMaxRequiredSecretRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, readWebhookMaxRequiredSecretRevision)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const readWebhookMinimumDeclaredConcurrency = `-- name: ReadWebhookMinimumDeclaredConcurrency :one
SELECT COALESCE(min(global_concurrency), 0)::integer
FROM webhook_destinations
WHERE disposition IN ('active', 'automatically_paused')
`

func (q *Queries) ReadWebhookMinimumDeclaredConcurrency(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, readWebhookMinimumDeclaredConcurrency)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const readWebhookOperatorAction = `-- name: ReadWebhookOperatorAction :one
SELECT owner_scope, action_id, encoding_version, request_fingerprint, actor_reference, action_kind, target_kind, target_id, target_generation, expected_state, reason, duplicate_risk_acknowledged, state, result, created_at, completed_at FROM webhook_operator_actions
WHERE owner_scope = $1 AND action_id = $2
`

type ReadWebhookOperatorActionParams struct {
	OwnerScope string
	ActionID   string
}

func (q *Queries) ReadWebhookOperatorAction(ctx context.Context, arg ReadWebhookOperatorActionParams) (WebhookOperatorAction, error) {
	row := q.db.QueryRow(ctx, readWebhookOperatorAction, arg.OwnerScope, arg.ActionID)
	var i WebhookOperatorAction
	err := row.Scan(
		&i.OwnerScope,
		&i.ActionID,
		&i.EncodingVersion,
		&i.RequestFingerprint,
		&i.ActorReference,
		&i.ActionKind,
		&i.TargetKind,
		&i.TargetID,
		&i.TargetGeneration,
		&i.ExpectedState,
		&i.Reason,
		&i.DuplicateRiskAcknowledged,
		&i.State,
		&i.Result,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const readWebhookTombstone = `-- name: ReadWebhookTombstone :one
SELECT target_kind, target_id, acceptance_id, fanout_snapshot_id, last_semantic_class,
       action_id, action_encoding_version, request_fingerprint, first_disposition,
       deletion_authority, created_at
FROM webhook_tombstones
WHERE owner_scope = $1
  AND ((target_kind = 'namespace' AND target_id = $1)
    OR (target_kind = 'event' AND target_id = $2))
ORDER BY target_kind DESC
LIMIT 1
`

type ReadWebhookTombstoneParams struct {
	OwnerScope string
	TargetID   string
}

type ReadWebhookTombstoneRow struct {
	TargetKind            string
	TargetID              string
	AcceptanceID          *string
	FanoutSnapshotID      *string
	LastSemanticClass     string
	ActionID              string
	ActionEncodingVersion string
	RequestFingerprint    []byte
	FirstDisposition      string
	DeletionAuthority     string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ReadWebhookTombstone(ctx context.Context, arg ReadWebhookTombstoneParams) (ReadWebhookTombstoneRow, error) {
	row := q.db.QueryRow(ctx, readWebhookTombstone, arg.OwnerScope, arg.TargetID)
	var i ReadWebhookTombstoneRow
	err := row.Scan(
		&i.TargetKind,
		&i.TargetID,
		&i.AcceptanceID,
		&i.FanoutSnapshotID,
		&i.LastSemanticClass,
		&i.ActionID,
		&i.ActionEncodingVersion,
		&i.RequestFingerprint,
		&i.FirstDisposition,
		&i.DeletionAuthority,
		&i.CreatedAt,
	)
	return i, err
}

const readWebhookTombstoneAction = `-- name: ReadWebhookTombstoneAction :one
SELECT target_kind, target_id, acceptance_id, fanout_snapshot_id, last_semantic_class,
       action_id, action_encoding_version, request_fingerprint, first_disposition,
       deletion_authority, created_at
FROM webhook_tombstones
WHERE owner_scope = $1 AND action_id = $2
`

type ReadWebhookTombstoneActionParams struct {
	OwnerScope string
	ActionID   string
}

type ReadWebhookTombstoneActionRow struct {
	TargetKind            string
	TargetID              string
	AcceptanceID          *string
	FanoutSnapshotID      *string
	LastSemanticClass     string
	ActionID              string
	ActionEncodingVersion string
	RequestFingerprint    []byte
	FirstDisposition      string
	DeletionAuthority     string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ReadWebhookTombstoneAction(ctx context.Context, arg ReadWebhookTombstoneActionParams) (ReadWebhookTombstoneActionRow, error) {
	row := q.db.QueryRow(ctx, readWebhookTombstoneAction, arg.OwnerScope, arg.ActionID)
	var i ReadWebhookTombstoneActionRow
	err := row.Scan(
		&i.TargetKind,
		&i.TargetID,
		&i.AcceptanceID,
		&i.FanoutSnapshotID,
		&i.LastSemanticClass,
		&i.ActionID,
		&i.ActionEncodingVersion,
		&i.RequestFingerprint,
		&i.FirstDisposition,
		&i.DeletionAuthority,
		&i.CreatedAt,
	)
	return i, err
}

const releaseWebhookEventCapacity = `-- name: ReleaseWebhookEventCapacity :exec
UPDATE webhook_capacity_slots s
SET owner_scope = NULL, delivery_id = NULL, cycle_number = NULL, attempt_id = NULL,
    lease_expires_at = NULL, fence = NULL
WHERE s.owner_scope = $1
  AND EXISTS (
      SELECT 1 FROM webhook_deliveries d
      WHERE d.owner_scope = $1 AND d.business_event_id = $2
        AND d.delivery_id = s.delivery_id
  )
`

type ReleaseWebhookEventCapacityParams struct {
	OwnerScope      *string
	BusinessEventID string
}

func (q *Queries) ReleaseWebhookEventCapacity(ctx context.Context, arg ReleaseWebhookEventCapacityParams) error {
	_, err := q.db.Exec(ctx, releaseWebhookEventCapacity, arg.OwnerScope, arg.BusinessEventID)
	return err
}

const releaseWebhookNamespaceCapacity = `-- name: ReleaseWebhookNamespaceCapacity :exec
UPDATE webhook_capacity_slots
SET owner_scope = NULL, delivery_id = NULL, cycle_number = NULL, attempt_id = NULL,
    lease_expires_at = NULL, fence = NULL
WHERE owner_scope = $1
`

func (q *Queries) ReleaseWebhookNamespaceCapacity(ctx context.Context, ownerScope *string) error {
	_, err := q.db.Exec(ctx, releaseWebhookNamespaceCapacity, ownerScope)
	return err
}
