// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postgres_outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceOutboxOrderingHead = `-- name: AdvanceOutboxOrderingHead :one
INSERT INTO outbox_ordering_heads (ordering_key, last_sequence, current_sequence)
VALUES ($1, $2, $2)
ON CONFLICT (ordering_key) DO UPDATE
SET last_sequence = EXCLUDED.last_sequence,
    current_sequence = coalesce(
        outbox_ordering_heads.current_sequence,
        EXCLUDED.current_sequence
    ),
    updated_at = clock_timestamp()
WHERE outbox_ordering_heads.last_sequence < EXCLUDED.last_sequence
RETURNING current_sequence
`

type AdvanceOutboxOrderingHeadParams struct {
	OrderingKey      string
	OrderingSequence int64
}

func (q *Queries) AdvanceOutboxOrderingHead(ctx context.Context, arg AdvanceOutboxOrderingHeadParams) (*int64, error) {
	row := q.db.QueryRow(ctx, advanceOutboxOrderingHead, arg.OrderingKey, arg.OrderingSequence)
	var current_sequence *int64
	err := row.Scan(&current_sequence)
	return current_sequence, err
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidate AS (
    SELECT event.id,
           event.lease_expires_at IS NOT NULL AS recovery_due
    FROM outbox_events AS event
    WHERE event.published_at IS NULL
      AND event.poisoned_at IS NULL
      AND (event.ordering_key IS NULL OR event.ordering_ready)
      AND event.available_at <= statement_timestamp()
      AND (event.lease_expires_at IS NULL OR event.lease_expires_at <= statement_timestamp())
    ORDER BY event.available_at, event.created_at, event.id
    FOR UPDATE OF event SKIP LOCKED
    LIMIT $3
)
UPDATE outbox_events AS event
SET lease_token = $1,
    lease_expires_at = statement_timestamp()
        + $2::double precision * interval '1 millisecond',
    cycle_attempt_count = event.cycle_attempt_count + 1,
    total_attempt_count = event.total_attempt_count + 1,
    last_attempt_at = statement_timestamp()
FROM candidate
WHERE event.id = candidate.id
RETURNING event.id, event.event_type, event.source, event.destination, event.schema_name, event.occurred_at, event.payload, event.metadata, event.ordering_key, event.ordering_sequence, event.created_at, event.available_at, event.cycle_attempt_count, event.total_attempt_count, event.last_attempt_at, event.lease_token, event.lease_expires_at, event.published_at, event.poisoned_at, event.last_error_class, event.redrive_count, event.last_redrive_id, event.last_redriven_at, event.ordering_ready, candidate.recovery_due::boolean AS recovery_due
`

type ClaimOutboxEventsParams struct {
	LeaseToken        *string
	LeaseMilliseconds float64
	BatchSize         int32
}

type ClaimOutboxEventsRow struct {
	ID                string
	EventType         string
	Source            string
	Destination       string
	SchemaName        string
	OccurredAt        pgtype.Timestamptz
	Payload           []byte
	Metadata          []byte
	OrderingKey       *string
	OrderingSequence  *int64
	CreatedAt         pgtype.Timestamptz
	AvailableAt       pgtype.Timestamptz
	CycleAttemptCount int32
	TotalAttemptCount int64
	LastAttemptAt     pgtype.Timestamptz
	LeaseToken        *string
	LeaseExpiresAt    pgtype.Timestamptz
	PublishedAt       pgtype.Timestamptz
	PoisonedAt        pgtype.Timestamptz
	LastErrorClass    *string
	RedriveCount      int32
	LastRedriveID     *string
	LastRedrivenAt    pgtype.Timestamptz
	OrderingReady     bool
	RecoveryDue       bool
}

// One statement leases a whole batch under a single token. The partial unique
// index on ready ordered rows keeps at most one claimable event per ordering
// key, so a batch never holds two events that must stay ordered relative to
// each other.
func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]ClaimOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, arg.LeaseToken, arg.LeaseMilliseconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxEventsRow
	for rows.Next() {
		var i ClaimOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Source,
			&i.Destination,
			&i.SchemaName,
			&i.OccurredAt,
			&i.Payload,
			&i.Metadata,
			&i.OrderingKey,
			&i.OrderingSequence,
			&i.CreatedAt,
			&i.AvailableAt,
			&i.CycleAttemptCount,
			&i.TotalAttemptCount,
			&i.LastAttemptAt,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.PublishedAt,
			&i.PoisonedAt,
			&i.LastErrorClass,
			&i.RedriveCount,
			&i.LastRedriveID,
			&i.LastRedrivenAt,
			&i.OrderingReady,
			&i.RecoveryDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupPublishedOutboxEvents = `-- name: CleanupPublishedOutboxEvents :execrows
WITH expired AS (
    SELECT id
    FROM outbox_events
    WHERE published_at < statement_timestamp()
        - $1::double precision * interval '1 millisecond'
    ORDER BY published_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
DELETE FROM outbox_events AS event
USING expired
WHERE event.id = expired.id
`

type CleanupPublishedOutboxEventsParams struct {
	RetentionMilliseconds float64
	BatchSize             int32
}

func (q *Queries) CleanupPublishedOutboxEvents(ctx context.Context, arg CleanupPublishedOutboxEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupPublishedOutboxEvents, arg.RetentionMilliseconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOutboxRedrive = `-- name: FindOutboxRedrive :one
SELECT event_id FROM outbox_redrives WHERE audit_id = $1
`

func (q *Queries) FindOutboxRedrive(ctx context.Context, auditID string) (string, error) {
	row := q.db.QueryRow(ctx, findOutboxRedrive, auditID)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const getOutboxEvent = `-- name: GetOutboxEvent :one
SELECT id, event_type, source, destination, schema_name, occurred_at, payload, metadata, ordering_key, ordering_sequence, created_at, available_at, cycle_attempt_count, total_attempt_count, last_attempt_at, lease_token, lease_expires_at, published_at, poisoned_at, last_error_class, redrive_count, last_redrive_id, last_redriven_at, ordering_ready FROM outbox_events WHERE id = $1
`

func (q *Queries) GetOutboxEvent(ctx context.Context, id string) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Source,
		&i.Destination,
		&i.SchemaName,
		&i.OccurredAt,
		&i.Payload,
		&i.Metadata,
		&i.OrderingKey,
		&i.OrderingSequence,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.CycleAttemptCount,
		&i.TotalAttemptCount,
		&i.LastAttemptAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.PublishedAt,
		&i.PoisonedAt,
		&i.LastErrorClass,
		&i.RedriveCount,
		&i.LastRedriveID,
		&i.LastRedrivenAt,
		&i.OrderingReady,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id,
    event_type,
    source,
    destination,
    schema_name,
    occurred_at,
    payload,
    metadata,
    ordering_key,
    ordering_sequence,
    ordering_ready
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type InsertOutboxEventParams struct {
	ID               string
	EventType        string
	Source           string
	Destination      string
	SchemaName       string
	OccurredAt       pgtype.Timestamptz
	Payload          []byte
	Metadata         []byte
	OrderingKey      *string
	OrderingSequence *int64
	OrderingReady    bool
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.Source,
		arg.Destination,
		arg.SchemaName,
		arg.OccurredAt,
		arg.Payload,
		arg.Metadata,
		arg.OrderingKey,
		arg.OrderingSequence,
		arg.OrderingReady,
	)
	return err
}

const insertOutboxRedrive = `-- name: InsertOutboxRedrive :exec
INSERT INTO outbox_redrives (audit_id, event_id, cycle_number)
VALUES ($1, $2, $3)
`

type InsertOutboxRedriveParams struct {
	AuditID     string
	EventID     string
	CycleNumber int32
}

func (q *Queries) InsertOutboxRedrive(ctx context.Context, arg InsertOutboxRedriveParams) error {
	_, err := q.db.Exec(ctx, insertOutboxRedrive, arg.AuditID, arg.EventID, arg.CycleNumber)
	return err
}

const lockOutboxEventForRedrive = `-- name: LockOutboxEventForRedrive :one
SELECT id, event_type, source, destination, schema_name, occurred_at, payload, metadata, ordering_key, ordering_sequence, created_at, available_at, cycle_attempt_count, total_attempt_count, last_attempt_at, lease_token, lease_expires_at, published_at, poisoned_at, last_error_class, redrive_count, last_redrive_id, last_redriven_at, ordering_ready FROM outbox_events WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOutboxEventForRedrive(ctx context.Context, id string) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, lockOutboxEventForRedrive, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Source,
		&i.Destination,
		&i.SchemaName,
		&i.OccurredAt,
		&i.Payload,
		&i.Metadata,
		&i.OrderingKey,
		&i.OrderingSequence,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.CycleAttemptCount,
		&i.TotalAttemptCount,
		&i.LastAttemptAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.PublishedAt,
		&i.PoisonedAt,
		&i.LastErrorClass,
		&i.RedriveCount,
		&i.LastRedriveID,
		&i.LastRedrivenAt,
		&i.OrderingReady,
	)
	return i, err
}

const markOrderedOutboxPublished = `-- name: MarkOrderedOutboxPublished :one
WITH locked_head AS MATERIALIZED (
    SELECT head.ordering_key, head.current_sequence, head.last_sequence
    FROM outbox_ordering_heads AS head
    WHERE head.ordering_key = $1
      AND head.current_sequence = $2
    FOR UPDATE
), next_event AS MATERIALIZED (
    SELECT event.id, event.ordering_sequence
    FROM outbox_events AS event
    JOIN locked_head AS head ON head.ordering_key = event.ordering_key
    WHERE event.ordering_sequence > head.current_sequence
      AND event.published_at IS NULL
    ORDER BY event.ordering_sequence
    LIMIT 1
), marked AS (
    UPDATE outbox_events AS event
    SET published_at = statement_timestamp(),
        lease_token = NULL,
        lease_expires_at = NULL,
        last_error_class = NULL
    WHERE event.id = $3
      AND event.lease_token = $4
      AND event.ordering_key = $1
      AND event.ordering_sequence = $2
      AND event.lease_expires_at > statement_timestamp()
      AND event.published_at IS NULL
      AND event.poisoned_at IS NULL
      AND EXISTS (SELECT 1 FROM locked_head)
      AND EXISTS (
          SELECT 1
          FROM locked_head AS head
          WHERE head.current_sequence = head.last_sequence
             OR EXISTS (SELECT 1 FROM next_event)
      )
    RETURNING event.id
), advanced AS (
    UPDATE outbox_ordering_heads AS head
    SET current_sequence = (SELECT ordering_sequence FROM next_event),
        updated_at = statement_timestamp()
    WHERE head.ordering_key = $1
      AND EXISTS (SELECT 1 FROM marked)
    RETURNING head.current_sequence
), unblocked AS (
    UPDATE outbox_events AS event
    SET ordering_ready = true
    WHERE event.id = (SELECT id FROM next_event)
      AND EXISTS (SELECT 1 FROM advanced)
    RETURNING event.id
)
SELECT
    (SELECT count(*) FROM marked)::bigint AS marked_count,
    (SELECT count(*) FROM advanced)::bigint AS advanced_count,
    (SELECT count(*) FROM unblocked)::bigint AS unblocked_count,
    (SELECT current_sequence FROM advanced) AS current_sequence,
    EXISTS (
        SELECT 1
        FROM locked_head AS head
        WHERE head.current_sequence < head.last_sequence
          AND NOT EXISTS (SELECT 1 FROM next_event)
    ) AS snapshot_conflict
`

type MarkOrderedOutboxPublishedParams struct {
	OrderingKey      string
	OrderingSequence *int64
	ID               string
	LeaseToken       *string
}

type MarkOrderedOutboxPublishedRow struct {
	MarkedCount      int64
	AdvancedCount    int64
	UnblockedCount   int64
	CurrentSequence  *int64
	SnapshotConflict bool
}

func (q *Queries) MarkOrderedOutboxPublished(ctx context.Context, arg MarkOrderedOutboxPublishedParams) (MarkOrderedOutboxPublishedRow, error) {
	row := q.db.QueryRow(ctx, markOrderedOutboxPublished,
		arg.OrderingKey,
		arg.OrderingSequence,
		arg.ID,
		arg.LeaseToken,
	)
	var i MarkOrderedOutboxPublishedRow
	err := row.Scan(
		&i.MarkedCount,
		&i.AdvancedCount,
		&i.UnblockedCount,
		&i.CurrentSequence,
		&i.SnapshotConflict,
	)
	return i, err
}

const markOutboxPoisonedBatch = `-- name: MarkOutboxPoisonedBatch :execrows
UPDATE outbox_events AS event
SET poisoned_at = statement_timestamp(),
    lease_token = NULL,
    lease_expires_at = NULL,
    last_error_class = poison.error_class
FROM (
    SELECT
        unnest($2::text[]) AS id,
        unnest($3::text[]) AS error_class
) AS poison
WHERE event.id = poison.id
  AND event.lease_token = $1
  AND event.lease_expires_at > statement_timestamp()
  AND event.published_at IS NULL
  AND event.poisoned_at IS NULL
`

type MarkOutboxPoisonedBatchParams struct {
	LeaseToken   *string
	Ids          []string
	ErrorClasses []string
}

func (q *Queries) MarkOutboxPoisonedBatch(ctx context.Context, arg MarkOutboxPoisonedBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPoisonedBatch, arg.LeaseToken, arg.Ids, arg.ErrorClasses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox_events
SET published_at = statement_timestamp(),
    lease_token = NULL,
    lease_expires_at = NULL,
    last_error_class = NULL
WHERE id = $1
  AND lease_token = $2
  AND ordering_key IS NOT DISTINCT FROM $3
  AND ordering_sequence IS NOT DISTINCT FROM $4
  AND lease_expires_at > statement_timestamp()
  AND published_at IS NULL
  AND poisoned_at IS NULL
`

type MarkOutboxPublishedParams struct {
	ID               string
	LeaseToken       *string
	OrderingKey      *string
	OrderingSequence *int64
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished,
		arg.ID,
		arg.LeaseToken,
		arg.OrderingKey,
		arg.OrderingSequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublishedBatch = `-- name: MarkOutboxPublishedBatch :execrows
UPDATE outbox_events AS event
SET published_at = statement_timestamp(),
    lease_token = NULL,
    lease_expires_at = NULL,
    last_error_class = NULL
WHERE event.id = ANY($1::text[])
  AND event.lease_token = $2
  AND event.ordering_key IS NULL
  AND event.lease_expires_at > statement_timestamp()
  AND event.published_at IS NULL
  AND event.poisoned_at IS NULL
`

type MarkOutboxPublishedBatchParams struct {
	Ids        []string
	LeaseToken *string
}

// Unordered events finalize together because none of them owns an ordering
// head. A short row count means at least one lease was lost, which the caller
// resolves per event against durable state.
func (q *Queries) MarkOutboxPublishedBatch(ctx context.Context, arg MarkOutboxPublishedBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublishedBatch, arg.Ids, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const observeOutbox = `-- name: ObserveOutbox :one
WITH pending AS (
    SELECT
        event.created_at,
        CASE
            WHEN event.poisoned_at IS NOT NULL THEN 'poison'
            WHEN event.lease_expires_at > statement_timestamp() THEN 'in_progress'
            WHEN event.lease_expires_at IS NOT NULL THEN 'recovery_due'
            WHEN event.ordering_key IS NOT NULL AND NOT event.ordering_ready THEN 'ordering_blocked'
            WHEN event.available_at > statement_timestamp() THEN 'retry_wait'
            ELSE 'eligible'
        END AS state
    FROM outbox_events AS event
    WHERE event.published_at IS NULL
), backlog AS (
    SELECT
        count(*)::bigint AS pending_count,
        count(*) FILTER (WHERE state = 'eligible')::bigint AS eligible_count,
        coalesce(extract(epoch FROM min(created_at) FILTER (
            WHERE state = 'eligible'
        )), 0)::double precision AS eligible_oldest_unix,
        count(*) FILTER (WHERE state = 'in_progress')::bigint AS in_progress_count,
        coalesce(extract(epoch FROM min(created_at) FILTER (
            WHERE state = 'in_progress'
        )), 0)::double precision AS in_progress_oldest_unix,
        count(*) FILTER (WHERE state = 'retry_wait')::bigint AS retry_wait_count,
        coalesce(extract(epoch FROM min(created_at) FILTER (
            WHERE state = 'retry_wait'
        )), 0)::double precision AS retry_wait_oldest_unix,
        count(*) FILTER (WHERE state = 'recovery_due')::bigint AS recovery_due_count,
        coalesce(extract(epoch FROM min(created_at) FILTER (
            WHERE state = 'recovery_due'
        )), 0)::double precision AS recovery_due_oldest_unix,
        count(*) FILTER (WHERE state = 'ordering_blocked')::bigint AS ordering_blocked_count,
        coalesce(extract(epoch FROM min(created_at) FILTER (
            WHERE state = 'ordering_blocked'
        )), 0)::double precision AS ordering_blocked_oldest_unix,
        count(*) FILTER (WHERE state = 'poison')::bigint AS poison_count,
        coalesce(extract(epoch FROM min(created_at) FILTER (
            WHERE state = 'poison'
        )), 0)::double precision AS poison_oldest_unix
    FROM pending
)
SELECT
    backlog.eligible_count,
    backlog.eligible_oldest_unix,
    backlog.in_progress_count,
    backlog.in_progress_oldest_unix,
    backlog.retry_wait_count,
    backlog.retry_wait_oldest_unix,
    backlog.recovery_due_count,
    backlog.recovery_due_oldest_unix,
    backlog.ordering_blocked_count,
    backlog.ordering_blocked_oldest_unix,
    backlog.poison_count,
    backlog.poison_oldest_unix,
    greatest(
        coalesce((
            SELECT nullif(class.reltuples, -1)
            FROM pg_catalog.pg_class AS class
            WHERE class.oid = 'outbox_events'::regclass
        ), 0) - backlog.pending_count,
        0
    )::bigint AS published_retained_estimate,
    coalesce((
        SELECT extract(epoch FROM min(event.published_at))
        FROM outbox_events AS event
        WHERE event.published_at IS NOT NULL
    ), 0)::double precision AS published_retained_oldest_unix,
    (SELECT count(*)::bigint FROM outbox_ordering_heads) AS ordering_head_count,
    pg_total_relation_size('outbox_events')::bigint AS events_bytes,
    pg_indexes_size('outbox_events')::bigint AS events_index_bytes,
    pg_total_relation_size('outbox_ordering_heads')::bigint AS ordering_heads_bytes,
    pg_indexes_size('outbox_ordering_heads')::bigint AS ordering_heads_index_bytes,
    pg_total_relation_size('outbox_redrives')::bigint AS redrives_bytes,
    pg_indexes_size('outbox_redrives')::bigint AS redrives_index_bytes
FROM backlog
`

type ObserveOutboxRow struct {
	EligibleCount               int64
	EligibleOldestUnix          float64
	InProgressCount             int64
	InProgressOldestUnix        float64
	RetryWaitCount              int64
	RetryWaitOldestUnix         float64
	RecoveryDueCount            int64
	RecoveryDueOldestUnix       float64
	OrderingBlockedCount        int64
	OrderingBlockedOldestUnix   float64
	PoisonCount                 int64
	PoisonOldestUnix            float64
	PublishedRetainedEstimate   int64
	PublishedRetainedOldestUnix float64
	OrderingHeadCount           int64
	EventsBytes                 int64
	EventsIndexBytes            int64
	OrderingHeadsBytes          int64
	OrderingHeadsIndexBytes     int64
	RedrivesBytes               int64
	RedrivesIndexBytes          int64
}

// Backlog states are exact and read only unpublished rows through the pending
// partial index, so observation cost tracks backlog rather than retention
// volume. Retained published rows are reported as the planner's own row
// estimate minus that exact pending count, because counting them would scan
// the entire retention window on every observation.
func (q *Queries) ObserveOutbox(ctx context.Context) (ObserveOutboxRow, error) {
	row := q.db.QueryRow(ctx, observeOutbox)
	var i ObserveOutboxRow
	err := row.Scan(
		&i.EligibleCount,
		&i.EligibleOldestUnix,
		&i.InProgressCount,
		&i.InProgressOldestUnix,
		&i.RetryWaitCount,
		&i.RetryWaitOldestUnix,
		&i.RecoveryDueCount,
		&i.RecoveryDueOldestUnix,
		&i.OrderingBlockedCount,
		&i.OrderingBlockedOldestUnix,
		&i.PoisonCount,
		&i.PoisonOldestUnix,
		&i.PublishedRetainedEstimate,
		&i.PublishedRetainedOldestUnix,
		&i.OrderingHeadCount,
		&i.EventsBytes,
		&i.EventsIndexBytes,
		&i.OrderingHeadsBytes,
		&i.OrderingHeadsIndexBytes,
		&i.RedrivesBytes,
		&i.RedrivesIndexBytes,
	)
	return i, err
}

const redriveOutboxEvent = `-- name: RedriveOutboxEvent :execrows
UPDATE outbox_events
SET available_at = statement_timestamp(),
    cycle_attempt_count = 0,
    lease_token = NULL,
    lease_expires_at = NULL,
    poisoned_at = NULL,
    last_error_class = NULL,
    redrive_count = redrive_count + 1,
    last_redrive_id = $1,
    last_redriven_at = statement_timestamp()
WHERE id = $2
  AND poisoned_at IS NOT NULL
  AND published_at IS NULL
`

type RedriveOutboxEventParams struct {
	AuditID *string
	ID      string
}

func (q *Queries) RedriveOutboxEvent(ctx context.Context, arg RedriveOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, redriveOutboxEvent, arg.AuditID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleOutboxRetryBatch = `-- name: ScheduleOutboxRetryBatch :execrows
UPDATE outbox_events AS event
SET available_at = statement_timestamp()
        + retry.delay_milliseconds * interval '1 millisecond',
    lease_token = NULL,
    lease_expires_at = NULL,
    last_error_class = retry.error_class
FROM (
    SELECT
        unnest($2::text[]) AS id,
        unnest($3::double precision[]) AS delay_milliseconds,
        unnest($4::text[]) AS error_class
) AS retry
WHERE event.id = retry.id
  AND event.lease_token = $1
  AND event.lease_expires_at > statement_timestamp()
  AND event.published_at IS NULL
  AND event.poisoned_at IS NULL
`

type ScheduleOutboxRetryBatchParams struct {
	LeaseToken        *string
	Ids               []string
	DelayMilliseconds []float64
	ErrorClasses      []string
}

// Each failed event carries its own jittered delay and error class, so one
// statement releases the whole failing part of a batch.
func (q *Queries) ScheduleOutboxRetryBatch(ctx context.Context, arg ScheduleOutboxRetryBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleOutboxRetryBatch,
		arg.LeaseToken,
		arg.Ids,
		arg.DelayMilliseconds,
		arg.ErrorClasses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
