package config

import "github.com/Dankosik/billing-service/internal/observability/otelconfig"

func defaultValues() map[string]any {
	return map[string]any{
		"app.env":     "local",
		"app.version": "dev",

		"http.addr":                        ":8080",
		"http.shutdown_timeout":            "30s",
		"http.readiness_timeout":           "4s",
		"http.readiness_propagation_delay": "15s",
		"http.read_header_timeout":         "5s",
		"http.read_timeout":                "5s",
		"http.write_timeout":               "10s",
		"http.idle_timeout":                "60s",
		"http.max_header_bytes":            16 << 10,
		"http.max_body_bytes":              int64(1 << 20),

		"log.level": "info",

		"postgres.enabled":             false,
		"postgres.dsn":                 "",
		"postgres.connect_timeout":     "3s",
		"postgres.healthcheck_timeout": "3s",
		"postgres.max_open_conns":      25,
		"postgres.max_idle_conns":      10,
		"postgres.conn_max_lifetime":   "30m",

		"redis.enabled":                  false,
		"redis.mode":                     "cache",
		"redis.allow_store_mode":         false,
		"redis.addr":                     "127.0.0.1:6379",
		"redis.username":                 "",
		"redis.password":                 "",
		"redis.db":                       0,
		"redis.dial_timeout":             "2s",
		"redis.read_timeout":             "1s",
		"redis.write_timeout":            "1s",
		"redis.pool_size":                20,
		"redis.key_prefix":               "billing-service",
		"redis.fresh_ttl":                "60s",
		"redis.stale_window":             "0s",
		"redis.negative_ttl":             "10s",
		"redis.ttl_jitter_percent":       10,
		"redis.enable_singleflight":      true,
		"redis.max_fallback_concurrency": 32,

		"mongo.enabled":                  false,
		"mongo.uri":                      "",
		"mongo.database":                 "app",
		"mongo.connect_timeout":          "5s",
		"mongo.server_selection_timeout": "3s",
		"mongo.max_pool_size":            100,

		"service_auth.enabled":  false,
		"service_auth.issuer":   "",
		"service_auth.audience": "",
		"service_auth.jwks_url": "",

		"redpanda.enabled":             false,
		"redpanda.brokers":             "",
		"redpanda.terminal_topic":      "billing.microlease.terminal.v1",
		"redpanda.checkpoint_topic":    "billing.microlease.checkpoint.v1",
		"redpanda.close_topic":         "billing.microlease.close.v1",
		"redpanda.billing_facts_topic": "billing.microlease.facts.v1",
		"redpanda.consumer_group":      "billing-service-microleases",
		"redpanda.healthcheck_timeout": "3s",

		"microlease.enabled":                                   false,
		"microlease.worker_enabled":                            false,
		"microlease.default_admission_state":                   "fail_closed",
		"microlease.max_microlease_usd_atoms":                  int64(100_000_000),
		"microlease.account_microlease_exposure_cap_usd_atoms": int64(200_000_000),
		"microlease.min_safety_floor_usd_atoms":                int64(5_000_000),
		"microlease.ttl":                                       "30s",
		"microlease.debit_cutoff_before_expiry":                "5s",
		"microlease.terminal_deadline":                         "120s",
		"microlease.stale_debit_warning_age":                   "60s",
		"microlease.stale_debit_critical_age":                  "180s",
		"microlease.reconciliation_sla":                        "5m",
		"microlease.admission_control_renewal_interval":        "30s",
		"microlease.admission_control_max_staleness":           "45s",
		"microlease.refill_threshold_percent":                  25,
		"microlease.max_issue_transaction_duration":            "100ms",
		"microlease.max_terminal_transaction_duration":         "250ms",
		"microlease.max_reconciliation_scan_batch_size":        100,
		"microlease.first_rollout_risk_acceptance_recorded":    false,

		"balance_usage_authority.enabled":                               false,
		"balance_usage_authority.mode":                                  "inert_expand",
		"balance_usage_authority.require_worker_ready":                  true,
		"balance_usage_authority.require_redpanda_ready":                true,
		"balance_usage_authority.require_admission_control_fresh":       true,
		"balance_usage_authority.max_admission_control_staleness":       "45s",
		"balance_usage_authority.reject_redis_spend_authority":          true,
		"balance_usage_authority.fail_closed_when_dependency_not_ready": true,

		"observability.otel.service_name":                  "billing-service",
		"observability.otel.traces_sampler":                otelconfig.DefaultTracesSampler,
		"observability.otel.traces_sampler_arg":            otelconfig.DefaultTracesSamplerArg,
		"observability.otel.exporter.otlp_endpoint":        "",
		"observability.otel.exporter.otlp_traces_endpoint": "",
		"observability.otel.exporter.otlp_headers":         "",
		"observability.otel.exporter.otlp_protocol":        otelconfig.DefaultOTLPProtocol,

		"feature_flags.postgres_readiness_probe": true,
		"feature_flags.mongo_readiness_probe":    false,
		"feature_flags.redis_readiness_probe":    false,
		"feature_flags.redpanda_readiness_probe": false,
	}
}
