DROP TABLE IF EXISTS audit_events CASCADE;
DROP TABLE IF EXISTS reconciliation_cases CASCADE;
DROP TABLE IF EXISTS legacy_balance_imports CASCADE;
DROP TABLE IF EXISTS legacy_import_batches CASCADE;
DROP TABLE IF EXISTS ledger_entries CASCADE;
DROP TABLE IF EXISTS payment_evidence CASCADE;
DROP TABLE IF EXISTS payment_attempts CASCADE;
DROP TABLE IF EXISTS topup_operations CASCADE;
DROP TABLE IF EXISTS qualified_inference_evidence CASCADE;
DROP TABLE IF EXISTS usage_terminal_outcomes CASCADE;
DROP TABLE IF EXISTS usage_holds CASCADE;
DROP TABLE IF EXISTS usage_operations CASCADE;
DROP TABLE IF EXISTS operation_outcomes CASCADE;
DROP TABLE IF EXISTS idempotency_records CASCADE;
DROP TABLE IF EXISTS account_balances CASCADE;
DROP TABLE IF EXISTS billing_accounts CASCADE;
DROP FUNCTION IF EXISTS prevent_ledger_money_mutation();
