// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Article defines model for Article.
type Article struct {
	Slug    string `json:"slug"`
	Summary string `json:"summary"`
	Title   string `json:"title"`
}

// ArticleDraft defines model for ArticleDraft.
type ArticleDraft struct {
	Slug    string `json:"slug"`
	Summary string `json:"summary"`
	Title   string `json:"title"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	//
	// Example: not_found
	Code string `json:"code"`

	// Detail Example: article was not found
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying this occurrence when the service exposes one.
	Instance *string `json:"instance,omitempty"`

	// RequestId Correlation identifier echoed from X-Request-ID.
	//
	// Example: 9ccecdfd92c94665a46406f8ba73cd77
	RequestId *string `json:"request_id,omitempty"`

	// Status Example: 404
	Status int32 `json:"status"`

	// Title Example: not found
	Title string `json:"title"`

	// Type Stable URI reference identifying the problem class.
	//
	// Example: https://www.rfc-editor.org/rfc/rfc9110#section-15.5.5
	Type string `json:"type"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Conflict defines model for Conflict.
type Conflict = Problem

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// CreateArticleJSONRequestBody defines body for CreateArticle for application/json ContentType.
type CreateArticleJSONRequestBody = ArticleDraft

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateArticle Create an article
	// (POST /api/v1/articles)
	CreateArticle(w http.ResponseWriter, r *http.Request)
	// GetArticle Get an article
	// (GET /api/v1/articles/{slug})
	GetArticle(w http.ResponseWriter, r *http.Request, slug string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// CreateArticle Create an article
// (POST /api/v1/articles)
func (_ Unimplemented) CreateArticle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetArticle Get an article
// (GET /api/v1/articles/{slug})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateArticle operation middleware
func (siw *ServerInterfaceWrapper) CreateArticle(w http.ResponseWriter, r *http.Request) {
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArticle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {
	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/articles", wrapper.CreateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/articles/{slug}", wrapper.GetArticle)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type CreateArticleRequestObject struct {
	Body *CreateArticleJSONRequestBody
}

type CreateArticleResponseObject interface {
	VisitCreateArticleResponse(w http.ResponseWriter) error
}

type CreateArticle201ResponseHeaders struct {
	Location string
}

type CreateArticle201JSONResponse struct {
	Body    Article
	Headers CreateArticle201ResponseHeaders
}

func (response CreateArticle201JSONResponse) VisitCreateArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateArticle400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateArticle400ApplicationProblemPlusJSONResponse) VisitCreateArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateArticle401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateArticle401ApplicationProblemPlusJSONResponse) VisitCreateArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateArticle403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateArticle403ApplicationProblemPlusJSONResponse) VisitCreateArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateArticle409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateArticle409ApplicationProblemPlusJSONResponse) VisitCreateArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateArticle500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response CreateArticle500ApplicationProblemPlusJSONResponse) VisitCreateArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetArticleRequestObject struct {
	Slug string `json:"slug"`
}

type GetArticleResponseObject interface {
	VisitGetArticleResponse(w http.ResponseWriter) error
}

type GetArticle200JSONResponse Article

func (response GetArticle200JSONResponse) VisitGetArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetArticle400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetArticle400ApplicationProblemPlusJSONResponse) VisitGetArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetArticle404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetArticle404ApplicationProblemPlusJSONResponse) VisitGetArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetArticle500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetArticle500ApplicationProblemPlusJSONResponse) VisitGetArticleResponse(w http.ResponseWriter) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateArticle Create an article
	// (POST /api/v1/articles)
	CreateArticle(ctx context.Context, request CreateArticleRequestObject) (CreateArticleResponseObject, error)
	// GetArticle Get an article
	// (GET /api/v1/articles/{slug})
	GetArticle(ctx context.Context, request GetArticleRequestObject) (GetArticleResponseObject, error)
}

type (
	StrictHandlerFunc    func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
	StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc
)

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateArticle operation middleware
func (sh *strictHandler) CreateArticle(w http.ResponseWriter, r *http.Request) {
	var request CreateArticleRequestObject

	var body CreateArticleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateArticle(ctx, request.(CreateArticleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateArticle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateArticleResponseObject); ok {
		if err := validResponse.VisitCreateArticleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArticle operation middleware
func (sh *strictHandler) GetArticle(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetArticleRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticle(ctx, request.(GetArticleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticleResponseObject); ok {
		if err := validResponse.VisitGetArticleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFddb9u4Ev0rBNuneyXLTpz0xvepH9siQHdRtFtggcBb0OTIZiGR2uEojhv4vy+G+rJdJ2m7RfahjUVp",
	"yJkz58wMb6X2ZeUdOApydisRQuVdgPjwQpn38FcNgfhJe0fg4k9VVYXViqx3WYV+UUD538/BO34X9ApK",
	"xb+eIuRyJp9kwxFZ8zZk7xorud1uE2kgaLQVbydnEpsjhQ2iVEXusQQjPArrrlVhjdwm8qV3eWH1o7ql",
	"nFBIVhcg1pZWglY2iFDUS6EKBGU2Am5soMD+vfa4sMaAe0wHNYIBR1YVQSgEEdESi5qE8yQqwNISQcTv",
	"0hGgU8UHwGvAXxA9PqantYObCjSBESF6IHJlixqBffvN02tfO/Ooue0Sq0IEK48ObBP50amaVh7tFzD/",
	"Zi5LG4J1yz0ZbJP2nKjV500I0TNjLO+jinfoK0CyLOdcFQESWe0s3UrmL/+lTQVyJgOhdUsOPNRlqXBz",
	"9B1Zag46eLNNonYtMlZXzd7d18OO86Sz84vPoIl3bJ1/hSqnH4ygVDdvwS1pJWfn00SW1nWPk0RWipjw",
	"cib/vFLplzn/N04v0vl/nsrk3uB3tj0bjw/3vRuaHbuTB+1+HLiOQt+HmfYmOrnPuQ+kFgWIUumVdZBy",
	"TYsLwOVBsM1IJhJuVFlxjNJ5+tQI5QgQBkjZgg8ZDI6r7IixdYGU00d8/Pj+UiDkgOA0CBs1km9YGbEc",
	"e61rbN6tV+AErSBWGKtBwE3lAwThXYyD+4oiLkZo037LY960/eiTNV/789IjQhGLQOeNBRSgVx6MyNGX",
	"4o+07aHp5at9AC+0Bm1yc3GiL6bn52dqej4dn+f/W6hnp9o8e3aUmqSoDnu4TsfTnXCso9OTwdI6giXg",
	"Hjf3Unh3FpqFO1hyXyJAtPVQ6EKFsB/0iqgKsyxbr9cjzHUKxpLHkcdlhrnmfxeTyfhJAM0HppOz0dno",
	"7DvydaClSPX2ox1JNSh+rShGGHSNljYfuLY2elmAQsDnNav3EI9XUHoXCBsONF+KoXyL3GOEZACrxUJ4",
	"V2xG4rlAUEXPUoSqUBpCw+c4aFgKwq87ftFGGAh26f4vAoAwXocstxgordCbukEtB0U1wqg0DH7sEhxl",
	"492AGeei6T7W5Z5jK6wGF2LanYo2v17+LhNZY7GTO1+BC75GDTFvrVHI+NuBaLIPOW2Vn7ZRykReA4YG",
	"wPFoMhqzGe+qKitn8nQ0Hp3KWLZXMQGZqmx2PcnafeJa5ZuxlAtbBP/SsCARFEHXDHvxvvBmc0///r6+",
	"vdettvuMI6whLuyM0Sfjyc8++74hRkcIWNIrUAYw+vDWN8cdL6k+jxxtLbs5Vx4Gluw4+c16ZEen4/Fd",
	"gfVIZTu3jWgyedhkbzyLRqcPGw3DebS4eNiiv25sE3n2LaEcm693a4ucXe1Xlav5dr4zd7Q0FsOdg4FV",
	"y8AlrRfBPJE3abdlakDb0GY49jqep2fc+SmO2pxN1QwIvL5GSxCEXim3BBHIIxjRUlQoZ0SbeqGEVkUB",
	"2NefhnuHksxueWzZ8ulLOCLMN0CDKiuFqgSK3Ly6lZZ5yGKXSVd22hnobv79vHmPkT/Q6/gx9dpfNn5I",
	"JdOHTfob1T+mb8/PN0A/hZz1orD6gJk8eKbcHPtO2dEytkPnh07oUVRor1kqRpFqq01zp2yodXCtitMh",
	"9d3Wo11a1/e3TDIX2lAObd/3DXzPHe9ANGFwIzdROnGt052IShsN1O4h2s63fwcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
