//nolint:dupl // OpenAPI response wrappers intentionally mirror generated status-specific response types.
package httpx

import (
	"context"
	"net/http"

	"github.com/Dankosik/billing-service/internal/api"
)

func resolveBillingAccountProblemResponse(ctx context.Context, err error) api.ResolveBillingAccountResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ResolveBillingAccount400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ResolveBillingAccount401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ResolveBillingAccount403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusLocked:
		return api.ResolveBillingAccount423ApplicationProblemPlusJSONResponse{LockedApplicationProblemPlusJSONResponse: api.LockedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ResolveBillingAccount503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ResolveBillingAccount500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func readBillingBalanceProblemResponse(ctx context.Context, err error) api.ReadBillingBalanceResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ReadBillingBalance400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ReadBillingBalance401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ReadBillingBalance403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusLocked:
		return api.ReadBillingBalance423ApplicationProblemPlusJSONResponse{LockedApplicationProblemPlusJSONResponse: api.LockedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ReadBillingBalance503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ReadBillingBalance500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func reserveUsageProblemResponse(ctx context.Context, err error) api.ReserveUsageResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ReserveUsage400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ReserveUsage401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ReserveUsage403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusConflict:
		return api.ReserveUsage409ApplicationProblemPlusJSONResponse{ConflictApplicationProblemPlusJSONResponse: api.ConflictApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnprocessableEntity:
		return api.ReserveUsage422ApplicationProblemPlusJSONResponse{UnprocessableEntityApplicationProblemPlusJSONResponse: api.UnprocessableEntityApplicationProblemPlusJSONResponse(problem)}
	case http.StatusLocked:
		return api.ReserveUsage423ApplicationProblemPlusJSONResponse{LockedApplicationProblemPlusJSONResponse: api.LockedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusTooManyRequests:
		return api.ReserveUsage429ApplicationProblemPlusJSONResponse{TooManyRequestsApplicationProblemPlusJSONResponse: api.TooManyRequestsApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ReserveUsage503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ReserveUsage500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func finalizeUsageProblemResponse(ctx context.Context, err error) api.FinalizeUsageResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.FinalizeUsage400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.FinalizeUsage401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.FinalizeUsage403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusConflict:
		return api.FinalizeUsage409ApplicationProblemPlusJSONResponse{ConflictApplicationProblemPlusJSONResponse: api.ConflictApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnprocessableEntity:
		return api.FinalizeUsage422ApplicationProblemPlusJSONResponse{UnprocessableEntityApplicationProblemPlusJSONResponse: api.UnprocessableEntityApplicationProblemPlusJSONResponse(problem)}
	case http.StatusLocked:
		return api.FinalizeUsage423ApplicationProblemPlusJSONResponse{LockedApplicationProblemPlusJSONResponse: api.LockedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.FinalizeUsage503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.FinalizeUsage500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func writeOffUsageProblemResponse(ctx context.Context, err error) api.WriteOffUsageResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.WriteOffUsage400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.WriteOffUsage401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.WriteOffUsage403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusConflict:
		return api.WriteOffUsage409ApplicationProblemPlusJSONResponse{ConflictApplicationProblemPlusJSONResponse: api.ConflictApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnprocessableEntity:
		return api.WriteOffUsage422ApplicationProblemPlusJSONResponse{UnprocessableEntityApplicationProblemPlusJSONResponse: api.UnprocessableEntityApplicationProblemPlusJSONResponse(problem)}
	case http.StatusLocked:
		return api.WriteOffUsage423ApplicationProblemPlusJSONResponse{LockedApplicationProblemPlusJSONResponse: api.LockedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.WriteOffUsage503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.WriteOffUsage500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func reverseUsageProblemResponse(ctx context.Context, err error) api.ReverseUsageResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ReverseUsage400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ReverseUsage401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ReverseUsage403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusConflict:
		return api.ReverseUsage409ApplicationProblemPlusJSONResponse{ConflictApplicationProblemPlusJSONResponse: api.ConflictApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnprocessableEntity:
		return api.ReverseUsage422ApplicationProblemPlusJSONResponse{UnprocessableEntityApplicationProblemPlusJSONResponse: api.UnprocessableEntityApplicationProblemPlusJSONResponse(problem)}
	case http.StatusLocked:
		return api.ReverseUsage423ApplicationProblemPlusJSONResponse{LockedApplicationProblemPlusJSONResponse: api.LockedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ReverseUsage503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ReverseUsage500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func readUsageOperationProblemResponse(ctx context.Context, err error) api.ReadUsageOperationResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ReadUsageOperation400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ReadUsageOperation401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ReadUsageOperation403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ReadUsageOperation503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ReadUsageOperation500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func listReconciliationCasesProblemResponse(ctx context.Context, err error) api.ListReconciliationCasesResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ListReconciliationCases400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ListReconciliationCases401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ListReconciliationCases403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ListReconciliationCases503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ListReconciliationCases500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func readAdminLedgerProblemResponse(ctx context.Context, err error) api.ReadAdminLedgerResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ReadAdminLedger400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ReadAdminLedger401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ReadAdminLedger403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ReadAdminLedger503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ReadAdminLedger500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}

func readAdminExposureProblemResponse(ctx context.Context, err error) api.ReadAdminExposureResponseObject {
	status, problem := problemFromError(ctx, err)
	switch status {
	case http.StatusBadRequest:
		return api.ReadAdminExposure400ApplicationProblemPlusJSONResponse{BadRequestApplicationProblemPlusJSONResponse: api.BadRequestApplicationProblemPlusJSONResponse(problem)}
	case http.StatusUnauthorized:
		return api.ReadAdminExposure401ApplicationProblemPlusJSONResponse{UnauthorizedApplicationProblemPlusJSONResponse: api.UnauthorizedApplicationProblemPlusJSONResponse(problem)}
	case http.StatusForbidden:
		return api.ReadAdminExposure403ApplicationProblemPlusJSONResponse{ForbiddenApplicationProblemPlusJSONResponse: api.ForbiddenApplicationProblemPlusJSONResponse(problem)}
	case http.StatusServiceUnavailable:
		return api.ReadAdminExposure503ApplicationProblemPlusJSONResponse{ServiceUnavailableApplicationProblemPlusJSONResponse: api.ServiceUnavailableApplicationProblemPlusJSONResponse(problem)}
	default:
		return api.ReadAdminExposure500ApplicationProblemPlusJSONResponse{InternalServerErrorApplicationProblemPlusJSONResponse: api.InternalServerErrorApplicationProblemPlusJSONResponse(problem)}
	}
}
